import { decryptSecret, encryptSecret, maskSecret } from "./secret-vault.server.js";

const MAP_PROVIDER="google-maps";
const CAPTCHA_PROVIDERS=Object.freeze({v2:"google-recaptcha-v2",v3:"google-recaptcha-v3"});
function parse(raw,fallback={}){try{const value=JSON.parse(String(raw||"{}"));return value&&typeof value==="object"&&!Array.isArray(value)?value:fallback;}catch{return fallback;}}
async function rowFor(db,shop,provider,formKey="global"){return db.builderIntegration.findFirst({where:{shop,provider,formKey},orderBy:{updatedAt:"desc"}}).catch(()=>null);}
async function decryptRowSecret(shop,row,key){const raw=parse(row?.secretJson,{});if(!raw?.[key])return"";try{return decryptSecret(shop,raw[key]);}catch{return"";}}

export async function loadGoogleMapsSettings(db,shop){const row=await rowFor(db,shop,MAP_PROVIDER,"global");const apiKey=await decryptRowSecret(shop,row,"apiKey")||String(process.env.GOOGLE_MAPS_API_KEY||"").trim();return{enabled:row?row.enabled!==false:true,configured:Boolean(apiKey),maskedApiKey:apiKey?maskSecret(apiKey):"",source:row&&parse(row.secretJson,{}).apiKey?"store":apiKey?"environment":"none",updatedAt:row?.updatedAt?.toISOString?.()||null};}
export async function loadGoogleMapsApiKey(db,shop){const row=await rowFor(db,shop,MAP_PROVIDER,"global");if(row&&row.enabled===false)return"";return await decryptRowSecret(shop,row,"apiKey")||String(process.env.GOOGLE_MAPS_API_KEY||"").trim();}
export async function saveGoogleMapsSettings(db,shop,input={}){const existing=await rowFor(db,shop,MAP_PROVIDER,"global");const currentSecrets=parse(existing?.secretJson,{});const nextKey=String(input.apiKey||"").trim();const secretJson=JSON.stringify({...currentSecrets,...(nextKey?{apiKey:encryptSecret(shop,nextKey)}:{})});const data={name:"Google Maps",formKey:"global",enabled:input.enabled!==false,configJson:JSON.stringify({embedApi:true}),secretJson};if(existing)await db.builderIntegration.update({where:{id:existing.id},data});else await db.builderIntegration.create({data:{shop,provider:MAP_PROVIDER,...data}});return loadGoogleMapsSettings(db,shop);}

async function captchaRowPublic(db,shop,version){const provider=CAPTCHA_PROVIDERS[version];const row=await rowFor(db,shop,provider,"forms");const config=parse(row?.configJson,{});const secret=await decryptRowSecret(shop,row,"secretKey")||String(process.env[version==="v2"?"VSN_RECAPTCHA_V2_SECRET_KEY":"VSN_RECAPTCHA_V3_SECRET_KEY"]||"").trim();const siteKey=String(config.siteKey||process.env[version==="v2"?"VSN_RECAPTCHA_V2_SITE_KEY":"VSN_RECAPTCHA_V3_SITE_KEY"]||"").trim();return{version,enabled:row?row.enabled!==false:true,siteKey,siteKeyConfigured:Boolean(siteKey),secretConfigured:Boolean(secret),maskedSecretKey:secret?maskSecret(secret):"",source:row?"store":siteKey||secret?"environment":"none",threshold:version==="v3"?Math.max(0,Math.min(1,Number(config.threshold??0.5))):null,action:version==="v3"?String(config.action||"form_submit").replace(/[^A-Za-z0-9_/]/g,"").slice(0,80)||"form_submit":null,updatedAt:row?.updatedAt?.toISOString?.()||null};}
export async function loadGoogleCaptchaSettings(db,shop){const [v2,v3]=await Promise.all([captchaRowPublic(db,shop,"v2"),captchaRowPublic(db,shop,"v3")]);return{v2,v3};}
export async function loadGoogleCaptchaRuntime(db,shop,version){if(!["v2","v3"].includes(version))throw new Error("Unknown reCAPTCHA version.");const publicRow=await captchaRowPublic(db,shop,version);const row=await rowFor(db,shop,CAPTCHA_PROVIDERS[version],"forms");const secretKey=await decryptRowSecret(shop,row,"secretKey")||String(process.env[version==="v2"?"VSN_RECAPTCHA_V2_SECRET_KEY":"VSN_RECAPTCHA_V3_SECRET_KEY"]||"").trim();return{...publicRow,secretKey};}
export async function saveGoogleCaptchaSettings(db,shop,version,input={}){if(!["v2","v3"].includes(version))throw new Error("Unknown reCAPTCHA version.");const provider=CAPTCHA_PROVIDERS[version];const existing=await rowFor(db,shop,provider,"forms");const currentSecrets=parse(existing?.secretJson,{});const secretKey=String(input.secretKey||"").trim();const siteKey=String(input.siteKey||parse(existing?.configJson,{}).siteKey||"").trim().slice(0,500);const threshold=version==="v3"?Math.max(0,Math.min(1,Number(input.threshold??parse(existing?.configJson,{}).threshold??0.5))):null;const action=version==="v3"?(String(input.action||parse(existing?.configJson,{}).action||"form_submit").replace(/[^A-Za-z0-9_/]/g,"").slice(0,80)||"form_submit"):null;const configJson=JSON.stringify({siteKey,...(version==="v3"?{threshold,action}:{})});const secretJson=JSON.stringify({...currentSecrets,...(secretKey?{secretKey:encryptSecret(shop,secretKey)}:{})});const data={name:version==="v2"?"Google reCAPTCHA v2":"Google reCAPTCHA v3",formKey:"forms",enabled:input.enabled!==false,configJson,secretJson};if(existing)await db.builderIntegration.update({where:{id:existing.id},data});else await db.builderIntegration.create({data:{shop,provider,...data}});return captchaRowPublic(db,shop,version);}
