export async function deleteVsnShopData(db, shop, { includeSessions = true } = {}) {
  if (!shop) return { deleted: false, reason: "missing-shop" };
  const operations = [
    db.builderRevision.deleteMany({ where: { shop } }),
    db.builderAuditLog.deleteMany({ where: { shop } }),
    db.builderDiagnosticEvent.deleteMany({ where: { shop } }),
    db.builderRequestLog.deleteMany({ where: { shop } }),
    db.builderCleanupRun.deleteMany({ where: { shop } }),
    db.builderSupportMessage.deleteMany({ where: { shop } }),
    db.builderSupportTicket.deleteMany({ where: { shop } }),
    db.builderNotification.deleteMany({ where: { shop } }),
    db.builderPresence.deleteMany({ where: { shop } }),
    db.builderComment.deleteMany({ where: { shop } }),
    db.builderReviewLink.deleteMany({ where: { shop } }),
    db.builderPageLock.deleteMany({ where: { shop } }),
    db.builderBranch.deleteMany({ where: { shop } }),
    db.builderPageTranslation.deleteMany({ where: { shop } }),
    db.builderLocalizationConfig.deleteMany({ where: { shop } }),
    db.builderAiUsage.deleteMany({ where: { shop } }),
    db.builderExperimentEvent.deleteMany({ where: { shop } }),
    db.builderExperimentAssignment.deleteMany({ where: { shop } }),
    db.builderExperiment.deleteMany({ where: { shop } }),
    db.builderAutomationLog.deleteMany({ where: { shop } }),
    db.builderFormUpload.deleteMany({ where: { shop } }),
    db.builderFormSubmission.deleteMany({ where: { shop } }),
    db.builderFormConfig.deleteMany({ where: { shop } }),
    db.builderStockSearchCache.deleteMany({ where: { shop } }),
    db.builderIntegration.deleteMany({ where: { shop } }),
    db.builderWebhookEndpoint.deleteMany({ where: { shop } }),
    db.builderSvgAsset.deleteMany({ where: { shop } }),
    db.builderCustomFont.deleteMany({ where: { shop } }),
    db.builderMarketplaceFavorite.deleteMany({ where: { shop } }),
    db.builderMarketplaceInstall.deleteMany({ where: { shop } }),
    db.builderBrandKit.deleteMany({ where: { shop } }),
    db.builderMotionPreset.deleteMany({ where: { shop } }),
    db.builderGraphqlSavedQuery.deleteMany({ where: { shop } }),
    db.builderGraphqlHistory.deleteMany({ where: { shop } }),
    db.builderGlobalCodeRevision.deleteMany({ where: { shop } }),
    db.builderGlobalCode.deleteMany({ where: { shop } }),
    db.builderWishlist.deleteMany({ where: { shop } }),
    db.builderEmailTemplate.deleteMany({ where: { shop } }),
    db.builderVisitorSession.deleteMany({ where: { shop } }),
    db.builderLibraryItem.deleteMany({ where: { shop } }),
    db.builderTemplateRule.deleteMany({ where: { shop } }),
    db.builderBackup.deleteMany({ where: { shop } }),
    db.builderSubscription.deleteMany({ where: { shop } }),
    db.builderShopSetting.deleteMany({ where: { shop } }),
    db.builderPage.deleteMany({ where: { shop } }),
  ];
  if (includeSessions) operations.push(db.session.deleteMany({ where: { shop } }));
  await db.$transaction(operations);
  return { deleted: true };
}
