import { loadStockProviderCredentials } from "./stock-image-integrations.server.js";
import { trackedStockFetch } from "./stock-api-usage.server.js";

function int(value,fallback,min,max){const n=Math.floor(Number(value));return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function sourceSearch(provider,kind,query){const q=encodeURIComponent(String(query||"").trim());if(provider==="shutterstock")return kind==="video"?`https://www.shutterstock.com/search/${q}?image_type=video`:kind==="audio"?`https://www.shutterstock.com/music/search/${q}`:`https://www.shutterstock.com/search/${q}`;return kind==="video"?`https://www.istockphoto.com/videos/${q}`:`https://www.istockphoto.com/search/2/image?phrase=${q}`;}
function displayUrl(item){const sizes=item?.display_sizes||item?.displaySizes||[];const preferred=["high_res_comp","comp","preview","mid_res_comp","thumb"];for(const name of preferred){const hit=sizes.find((row)=>String(row?.name||row?.display_name||"").toLowerCase()===name);if(hit?.uri||hit?.url)return hit.uri||hit.url;}return sizes.find((row)=>row?.uri||row?.url)?.uri||sizes.find((row)=>row?.uri||row?.url)?.url||"";}
function thumbUrl(item){const sizes=item?.display_sizes||item?.displaySizes||[];const hit=sizes.find((row)=>/thumb/i.test(String(row?.name||row?.display_name||"")));return hit?.uri||hit?.url||displayUrl(item);}

function shutterstockHeaders(auth){if(auth.oauthToken)return{Authorization:`Bearer ${auth.oauthToken}`,Accept:"application/json","User-Agent":"VSN-Builder"};const token=Buffer.from(`${auth.consumerKey||""}:${auth.consumerSecret||""}`).toString("base64");return{Authorization:`Basic ${token}`,Accept:"application/json","User-Agent":"VSN-Builder"};}
function gettyHeaders(auth){return{"Api-Key":auth.apiKey,Accept:"application/json",...(auth.accessToken?{Authorization:`Bearer ${auth.accessToken}`}:{})};}

function shutterstockImage(row,query){const a=row.assets||{},preview=a.preview_1000||a.preview_1500||a.preview||a.huge_thumb||a.mosaic||{};return{provider:"shutterstock",providerLabel:"Shutterstock",providerId:String(row.id),width:Number(preview.width||0),height:Number(preview.height||0),thumbUrl:a.huge_thumb?.url||a.mosaic?.url||preview.url||"",previewUrl:preview.url||"",alt:row.description||"",title:row.description||`Shutterstock image ${row.id}`,author:`Contributor ${row.contributor?.id||""}`.trim(),authorUrl:"",sourceUrl:sourceSearch("shutterstock","image",query||row.description||row.id),importAllowed:false,licenseRequired:true,licenseMessage:"License/download this asset through your Shutterstock API subscription before importing the final file."};}
function shutterstockVideo(row,query){const a=row.assets||{};return{provider:"shutterstock",providerLabel:"Shutterstock",providerId:String(row.id),title:row.description||`Shutterstock video ${row.id}`,previewUrl:a.preview_jpg?.url||a.thumb_jpg?.url||"",sourceUrl:sourceSearch("shutterstock","video",query||row.description||row.id),author:`Contributor ${row.contributor?.id||""}`.trim(),authorUrl:"",duration:Number(row.duration||0),width:0,height:0,files:[{id:"preview",quality:"preview",mimeType:"video/mp4",width:0,height:0,fps:0,size:0,url:a.preview_mp4?.url||a.thumb_mp4?.url||""}].filter((file)=>file.url),importAllowed:false,licenseRequired:true,licenseMessage:"Shutterstock search previews are not final licensed media. License the video through your Shutterstock subscription first."};}
function shutterstockAudio(row,query){const a=row.assets||{};return{provider:"shutterstock",providerLabel:"Shutterstock",providerId:String(row.id),title:row.title||row.description||`Shutterstock audio ${row.id}`,previewUrl:a.preview_mp3?.url||a.preview_ogg?.url||"",waveformUrl:a.waveform?.url||"",sourceUrl:sourceSearch("shutterstock","audio",query||row.title||row.id),author:(row.artists||[]).map((a)=>a?.name).filter(Boolean).join(", ")||`Contributor ${row.contributor?.id||""}`.trim(),duration:Number(row.duration||0),license:"Shutterstock license required",licenseLabel:"Premium license",commercialSafe:true,importAllowed:false,licenseRequired:true,licenseMessage:"License/download the track through your Shutterstock API subscription before importing the final audio file."};}
function gettyImage(row,query){const preview=displayUrl(row),thumb=thumbUrl(row);return{provider:"getty",providerLabel:"Getty/iStock",providerId:String(row.id),width:Number(row.max_dimensions?.width||0),height:Number(row.max_dimensions?.height||0),thumbUrl:thumb,previewUrl:preview,alt:row.caption||row.title||"",title:row.title||row.caption||`Getty/iStock image ${row.id}`,author:row.artist||row.credit_line||"Getty/iStock contributor",authorUrl:"",sourceUrl:sourceSearch("getty","image",query||row.title||row.id),importAllowed:false,licenseRequired:true,licenseMessage:"Getty/iStock downloads are governed by the API key's license agreement and elevated download authorization."};}
function gettyVideo(row,query){const preview=displayUrl(row),thumb=thumbUrl(row);return{provider:"getty",providerLabel:"Getty/iStock",providerId:String(row.id),title:row.title||row.caption||`Getty/iStock video ${row.id}`,previewUrl:thumb,sourceUrl:sourceSearch("getty","video",query||row.title||row.id),author:row.artist||row.credit_line||"Getty/iStock contributor",authorUrl:"",duration:Number(row.clip_length||row.duration||0),width:0,height:0,files:preview?[{id:"preview",quality:"preview",mimeType:"video/mp4",width:0,height:0,fps:0,size:0,url:preview}]:[],importAllowed:false,licenseRequired:true,licenseMessage:"Getty/iStock video downloads require an API license agreement and elevated download authorization."};}

export async function searchShutterstock(db,shop,kind,input={}){const auth=await loadStockProviderCredentials(db,shop,"shutterstock");if(!auth.enabled||!auth.configured)return{provider:"shutterstock",results:[],total:0,skipped:true,reason:"not-configured"};const query=String(input.query||"").trim(),page=int(input.page,1,1,1000),perPage=int(input.perPage,24,1,100);const path=kind==="video"?"videos":kind==="audio"?"audio":"images";const params=new URLSearchParams({query:query||"business",page:String(page),per_page:String(perPage)});if(input.orientation&&input.orientation!=="any"&&kind!=="audio")params.set("orientation",String(input.orientation));if(input.order||input.sort)params.set("sort",String(input.order||input.sort));if(kind==="video"){if(Number(input.minDuration)>0)params.set("duration_from",String(Number(input.minDuration)));if(Number(input.maxDuration)>0)params.set("duration_to",String(Number(input.maxDuration)));}const url=`https://api.shutterstock.com/v2/${path}/search?${params}`;const response=await trackedStockFetch(db,{shop,provider:"shutterstock",mediaKind:kind,url,options:{headers:shutterstockHeaders(auth),signal:AbortSignal.timeout?.(12000)}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Shutterstock ${kind} search failed (${response.status}): ${payload?.message||"API error"}`);const mapper=kind==="video"?shutterstockVideo:kind==="audio"?shutterstockAudio:shutterstockImage;return{provider:"shutterstock",results:(payload.data||[]).map((row)=>mapper(row,query)),total:Number(payload.total_count||0),totalPages:Math.max(1,Math.ceil(Number(payload.total_count||0)/perPage)),rateLimit:{limit:response.headers.get("x-ratelimit-limit"),remaining:response.headers.get("x-ratelimit-remaining"),reset:response.headers.get("x-ratelimit-reset")}};}

export async function searchGetty(db,shop,kind,input={}){if(kind==="audio")return{provider:"getty",results:[],total:0,skipped:true,reason:"unsupported"};const auth=await loadStockProviderCredentials(db,shop,"getty");if(!auth.enabled||!auth.configured)return{provider:"getty",results:[],total:0,skipped:true,reason:"not-configured"};const query=String(input.query||"").trim(),page=int(input.page,1,1,1000);const validSizes=new Set([1,2,3,4,5,6,10,12,15,20,25,30,50,60,75,100]);let perPage=int(input.perPage,24,1,100);if(!validSizes.has(perPage))perPage=[...validSizes].sort((a,b)=>Math.abs(a-perPage)-Math.abs(b-perPage))[0];const resource=kind==="video"?"videos":"images";const params=new URLSearchParams({phrase:query||"business",page:String(page),page_size:String(perPage),fields:"display_set"});const url=`https://api.gettyimages.com/v3/search/${resource}/creative?${params}`;const response=await trackedStockFetch(db,{shop,provider:"getty",mediaKind:kind,url,options:{headers:gettyHeaders(auth),signal:AbortSignal.timeout?.(12000)}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Getty/iStock ${kind} search failed (${response.status}): ${payload?.ErrorMessage||payload?.message||"API error"}`);const list=kind==="video"?(payload.videos||[]):(payload.images||[]),mapper=kind==="video"?gettyVideo:gettyImage;return{provider:"getty",results:list.map((row)=>mapper(row,query)),total:Number(payload.result_count||0),totalPages:Math.max(1,Math.ceil(Number(payload.result_count||0)/perPage))};}
