import crypto from "node:crypto";
import { loadStockProviderCredentials, STOCK_AUDIO_IMPORT_PROVIDERS, STOCK_AUDIO_PROVIDERS } from "./stock-image-integrations.server.js";
import { trackedStockFetch } from "./stock-api-usage.server.js";
import { searchShutterstock } from "./stock-premium-providers.server.js";
import { createShopifyMediaFile, createStagedMediaUpload, deleteShopifyMediaFile, downloadStockMedia, updateShopifyMediaFile } from "./stock-media-shopify.server.js";

const CACHE_TTL_MS = Object.freeze({ freesound: 300_000, shutterstock: 300_000 });
const PROVIDER_LABELS = Object.freeze({ freesound:"Freesound", shutterstock:"Shutterstock" });
const AUDIO_HOSTS = ["freesound.org","cdn.freesound.org","cdn1.freesound.org","cdn2.freesound.org"];
const AUDIO_MIMES = new Set(["audio/mpeg","audio/mp3","audio/ogg","audio/mp4","audio/x-m4a"]);
const MAX_AUDIO_BYTES = 19 * 1024 * 1024;

function safeJson(raw,fallback={}){try{return JSON.parse(String(raw||""));}catch{return fallback;}}
function int(value,fallback,min,max){const n=Math.floor(Number(value));return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function cacheKey(input){return crypto.createHash("sha256").update(JSON.stringify(input)).digest("hex");}
function licenseLabel(value){const raw=String(value||"");if(/by-nc/i.test(raw)||/noncommercial/i.test(raw))return"NonCommercial";if(/cc0/i.test(raw))return"CC0";if(/by\/|attribution/i.test(raw))return"Attribution";return raw?"See license":"Unknown";}
function commercialLicense(value){return !/(by-nc|noncommercial)/i.test(String(value||""));}
function sourceUrl(value){try{const url=new URL(String(value||""));if(url.protocol!=="https:"||!(url.hostname==="freesound.org"||url.hostname.endsWith(".freesound.org")))return"";return url.toString();}catch{return"";}}
function soundResult(sound){const previews=sound.previews||{};return{provider:"freesound",providerLabel:"Freesound",providerId:String(sound.id),title:sound.name||`Freesound ${sound.id}`,previewUrl:previews["preview-hq-mp3"]||previews["preview-lq-mp3"]||previews["preview-hq-ogg"]||"",waveformUrl:sound.images?.waveform_m||sound.images?.spectral_m||"",sourceUrl:sourceUrl(sound.url),author:sound.username||"Freesound contributor",duration:Number(sound.duration||0),license:String(sound.license||""),licenseLabel:licenseLabel(sound.license),commercialSafe:commercialLicense(sound.license),type:String(sound.type||""),filesize:Number(sound.filesize||0),tags:Array.isArray(sound.tags)?sound.tags.slice(0,16):[],downloads:Number(sound.num_downloads||0),rating:Number(sound.avg_rating||0),importAllowed:true,licenseRequired:false};}

async function cached(db,shop,provider,key,loader){const cacheProvider=`audio:${provider}`,now=new Date(),found=await db.builderStockSearchCache.findUnique({where:{shop_provider_cacheKey:{shop,provider:cacheProvider,cacheKey:key}}}).catch(()=>null);if(found&&found.expiresAt>now)return{...safeJson(found.responseJson,{}),cached:true};const value=await loader(),expiresAt=new Date(Date.now()+(CACHE_TTL_MS[provider]||300_000));await db.builderStockSearchCache.upsert({where:{shop_provider_cacheKey:{shop,provider:cacheProvider,cacheKey:key}},create:{shop,provider:cacheProvider,cacheKey:key,responseJson:JSON.stringify(value),expiresAt},update:{responseJson:JSON.stringify(value),expiresAt}}).catch(()=>null);return{...value,cached:false};}

async function searchFreesound(db,shop,input={}){
  const auth=await loadStockProviderCredentials(db,shop,"freesound");
  if(!auth.enabled||!auth.apiKey||auth.config?.commercialApiLicensed!==true)return{provider:"freesound",results:[],total:0,skipped:true,reason:!auth.enabled?"disabled":!auth.apiKey?"not-configured":"commercial-api-license-required"};
  const query=String(input.query||"").trim().slice(0,120),page=int(input.page,1,1,1000),perPage=int(input.perPage,auth.config?.audioPageSize||auth.config?.pageSize||24,6,100),sort=String(input.sort||auth.config.sort||"score"),commercialOnly=input.commercialOnly==null?auth.config.commercialOnly!==false:String(input.commercialOnly)!=="false",minDuration=Math.max(0,Number(input.minDuration||0)||0),maxDuration=Math.max(minDuration,Number(input.maxDuration||600)||600),tag=String(input.tag||"").trim().slice(0,80);
  const normalized={query,page,perPage,sort,commercialOnly,minDuration,maxDuration,tag};
  return cached(db,shop,"freesound",cacheKey(normalized),async()=>{
    const fields="id,name,tags,username,license,duration,previews,images,type,filesize,url,num_downloads,avg_rating";
    const params=new URLSearchParams({query:query||"music",page:String(page),page_size:String(Math.min(150,commercialOnly?Math.max(perPage*2,perPage):perPage)),fields,sort:["score","duration_asc","duration_desc","created_desc","downloads_desc","rating_desc"].includes(sort)?sort:"score"});
    const filters=[];if(minDuration>0||maxDuration<600)filters.push(`duration:[${minDuration} TO ${maxDuration}]`);if(tag)filters.push(`tag:${JSON.stringify(tag)}`);if(filters.length)params.set("filter",filters.join(" "));
    const url=`https://freesound.org/apiv2/search/?${params}`;
    const response=await trackedStockFetch(db,{shop,provider:"freesound",mediaKind:"audio",url,options:{headers:{Authorization:`Token ${auth.apiKey}`,Accept:"application/json"},signal:AbortSignal.timeout?.(12000)}});
    const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Freesound search failed (${response.status}): ${payload?.detail||"API error"}`);
    let results=(payload.results||[]).map(soundResult);if(commercialOnly)results=results.filter((row)=>row.commercialSafe);results=results.slice(0,perPage);
    return{provider:"freesound",results,total:Number(payload.count||0),totalPages:payload.next?page+1:page,hasMore:Boolean(payload.next),rateLimit:{limit:response.headers.get("x-ratelimit-limit"),remaining:response.headers.get("x-ratelimit-remaining"),reset:response.headers.get("x-ratelimit-reset")}};
  });
}

async function searchProvider(db,shop,provider,input){if(provider==="shutterstock")return searchShutterstock(db,shop,"audio",input);return searchFreesound(db,shop,input);}
function roundRobin(groups,limit){const lists=groups.map((row)=>[...(row.results||[])]),out=[];while(out.length<limit&&lists.some((list)=>list.length))for(const list of lists){if(out.length>=limit)break;if(list.length)out.push(list.shift());}return out;}

export async function searchStockAudio(db,shop,input={}){
  await db.builderStockSearchCache.deleteMany({where:{shop,expiresAt:{lt:new Date()}}}).catch(()=>null);
  const requested=String(input.provider||"all"),provider=STOCK_AUDIO_PROVIDERS.includes(requested)?requested:"all",page=int(input.page,1,1,1000),perPage=int(input.perPage,24,6,100),providers=provider==="all"?STOCK_AUDIO_PROVIDERS:[provider],share=provider==="all"?Math.max(6,Math.ceil(perPage/providers.length)):perPage;
  const settled=await Promise.all(providers.map(async(name)=>{try{return await searchProvider(db,shop,name,{...input,page,perPage:share});}catch(error){return{provider:name,results:[],total:0,error:error instanceof Error?error.message:String(error)};}}));
  return{query:String(input.query||""),provider,page,perPage,results:provider==="all"?roundRobin(settled,perPage):(settled[0]?.results||[]),sourceStates:Object.fromEntries(settled.map((row)=>[row.provider,{total:row.total||0,totalPages:row.totalPages||1,error:row.error||null,skipped:row.skipped||false,reason:row.reason||null,cached:row.cached===true,rateLimit:row.rateLimit||null}])),hasMore:settled.some((row)=>row.hasMore===true||page<Number(row.totalPages||1))};
}

async function providerSound(db,shop,provider,id){if(!STOCK_AUDIO_IMPORT_PROVIDERS.includes(provider))throw new Error(`${PROVIDER_LABELS[provider]||provider} search is available, but licensed final-download import is not enabled.`);const auth=await loadStockProviderCredentials(db,shop,"freesound");if(!auth.enabled||!auth.apiKey)throw new Error("Freesound API is not configured.");if(auth.config?.commercialApiLicensed!==true)throw new Error("Freesound commercial API permission/license must be confirmed before importing audio into Shopify.");const fields="id,name,tags,username,license,duration,previews,images,type,filesize,url,num_downloads,avg_rating",url=`https://freesound.org/apiv2/sounds/${encodeURIComponent(id)}/?fields=${encodeURIComponent(fields)}`;const response=await trackedStockFetch(db,{shop,provider:"freesound",mediaKind:"audio",url,options:{headers:{Authorization:`Token ${auth.apiKey}`,Accept:"application/json"},signal:AbortSignal.timeout?.(12000)}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Freesound sound lookup failed (${response.status}).`);const result=soundResult(payload);if(!result.commercialSafe)throw new Error("This Freesound item uses a NonCommercial license and cannot be imported into a Shopify store by VSN.");if(!result.previewUrl)throw new Error("Freesound did not provide an MP3/OGG preview for this sound.");return result;}

function mediaKey(provider,id){return`stock-audio:${provider}:${id}`;}
function serialize(row){const data=safeJson(row.contentJson,{});return{id:row.id,provider:data.provider||row.source?.replace(/^stock-audio:/,"")||"",providerId:data.providerId||"",title:row.title,thumbnail:row.thumbnail||data.waveformUrl||"",isFavorite:row.isFavorite===true,imported:Boolean(data.shopifyFileId),shopifyFileId:data.shopifyFileId||"",shopifyUrl:data.shopifyUrl||"",fileStatus:data.fileStatus||"",author:data.author||"",sourceUrl:data.sourceUrl||"",updatedAt:row.updatedAt?.toISOString?.()||null,data};}
async function find(db,shop,provider,id){return db.builderLibraryItem.findFirst({where:{shop,kind:"stock-audio",sourceKey:mediaKey(provider,id),deletedAt:null}});}
export async function listStockAudioLibrary(db,shop){const rows=await db.builderLibraryItem.findMany({where:{shop,kind:"stock-audio",deletedAt:null},orderBy:[{isFavorite:"desc"},{updatedAt:"desc"}],take:300});const items=rows.map(serialize);return{favorites:items.filter((r)=>r.isFavorite),imports:items.filter((r)=>r.imported)};}
export async function toggleStockAudioFavorite(db,shop,provider,id,favorite,metadata={}){if(!STOCK_AUDIO_PROVIDERS.includes(provider))throw new Error("Unknown stock audio provider.");const existing=await find(db,shop,provider,id);const clean={provider,providerId:id,title:String(metadata.title||"Stock audio").slice(0,180),waveformUrl:String(metadata.waveformUrl||"").slice(0,1200),previewUrl:String(metadata.previewUrl||"").slice(0,1200),author:String(metadata.author||"").slice(0,180),sourceUrl:String(metadata.sourceUrl||"").slice(0,1200),duration:Number(metadata.duration||0),license:String(metadata.license||""),licenseLabel:String(metadata.licenseLabel||""),commercialSafe:metadata.commercialSafe!==false,importAllowed:metadata.importAllowed!==false,licenseRequired:metadata.licenseRequired===true,licenseMessage:String(metadata.licenseMessage||"").slice(0,400)};if(existing){const current=safeJson(existing.contentJson,{});return serialize(await db.builderLibraryItem.update({where:{id:existing.id},data:{isFavorite:favorite===true,title:clean.title||existing.title,thumbnail:clean.waveformUrl||existing.thumbnail,contentJson:JSON.stringify({...current,...clean})}}));}if(!favorite)return null;return serialize(await db.builderLibraryItem.create({data:{shop,title:clean.title,kind:"stock-audio",category:"Stock Audio",syncMode:"local",contentJson:JSON.stringify(clean),thumbnail:clean.waveformUrl||null,isFavorite:true,sourceKey:mediaKey(provider,id),source:`stock-audio:${provider}`,description:`${PROVIDER_LABELS[provider]} stock audio reference`}}));}
function filename(result,mime){const ext=mime.includes("ogg")?"ogg":mime.includes("mp4")||mime.includes("m4a")?"m4a":"mp3",slug=String(result.title||"stock-audio").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,60)||"audio";return`freesound-${result.providerId}-${slug}.${ext}`;}
export async function importStockAudio({db,admin,shop,provider="freesound",providerId,actor=null,update=false}){if(!STOCK_AUDIO_IMPORT_PROVIDERS.includes(provider))throw new Error(`${PROVIDER_LABELS[provider]||provider} requires a licensed final-download workflow before Shopify import.`);const result=await providerSound(db,shop,provider,providerId);const downloaded=await downloadStockMedia({url:result.previewUrl,allowedHosts:AUDIO_HOSTS,allowedMimeTypes:AUDIO_MIMES,maxBytes:MAX_AUDIO_BYTES,label:"stock audio",timeoutMs:45_000});const fileName=filename(result,downloaded.contentType),stagedUrl=await createStagedMediaUpload(admin,{filename:fileName,contentType:downloaded.contentType,bytes:downloaded.bytes,resource:"FILE"}),existing=await find(db,shop,provider,providerId),current=safeJson(existing?.contentJson,{});let file;if(update){if(!existing||!current.shopifyFileId)throw new Error("Import this audio file before updating it.");file=await updateShopifyMediaFile(admin,{fileId:current.shopifyFileId,stagedUrl,filename:fileName,alt:result.title});}else file=await createShopifyMediaFile(admin,{stagedUrl,filename:fileName,alt:result.title,contentType:"FILE"});const content={...current,...result,shopifyFileId:file.id,shopifyUrl:file.url||current.shopifyUrl||"",fileStatus:file.fileStatus,filename:fileName,importedAt:new Date().toISOString(),importQuality:"Freesound high-quality preview"};const data={title:result.title,kind:"stock-audio",category:"Stock Audio",syncMode:"local",contentJson:JSON.stringify(content),thumbnail:result.waveformUrl||existing?.thumbnail||null,sourceKey:mediaKey(provider,providerId),source:`stock-audio:${provider}`,createdBy:actor};return serialize(existing?await db.builderLibraryItem.update({where:{id:existing.id},data}):await db.builderLibraryItem.create({data:{shop,isFavorite:false,...data}}));}
export async function deleteImportedStockAudio({db,admin,shop,provider="freesound",providerId}){const existing=await find(db,shop,provider,providerId);if(!existing)throw new Error("Stock audio record was not found.");const content=safeJson(existing.contentJson,{});if(!content.shopifyFileId)throw new Error("This audio file is not imported to Shopify Files.");await deleteShopifyMediaFile(admin,content.shopifyFileId);const next={...content,shopifyFileId:"",shopifyUrl:"",fileStatus:"DELETED",deletedFromShopifyAt:new Date().toISOString()};if(!existing.isFavorite){await db.builderLibraryItem.update({where:{id:existing.id},data:{deletedAt:new Date(),contentJson:JSON.stringify(next)}});return null;}return serialize(await db.builderLibraryItem.update({where:{id:existing.id},data:{contentJson:JSON.stringify(next)}}));}
