import { useMemo, useState } from "react";
import { Copy, Link2, Link2Off, Plus, Save, Trash2 } from "lucide-react";
import { VsnInput } from "../ui/VsnToolkit.jsx";

const human=(value)=>String(value||"").replaceAll("-"," ").replace(/\b\w/g,(c)=>c.toUpperCase());

export function EmailSavedPane({document,selected,savedBlocks=[],onCreateSymbol,onInsertSymbol,onDetachSymbol,onDeleteSymbol,onSaveBlock,onInsertSavedBlock,onDeleteSavedBlock,busy=false}){
  const [symbolName,setSymbolName]=useState("");const [blockName,setBlockName]=useState("");
  const symbols=useMemo(()=>document.symbols||[],[document.symbols]);
  return <div className="vsn-email-studio-side-scroll"><section className="vsn-email-saved-section"><div className="vsn-email-saved-head"><div><strong>Reusable symbols</strong><small>Linked instances stay synchronized inside this email.</small></div><Link2 size={15}/></div>{selected&&!selected.symbolId?<div className="vsn-email-saved-create"><VsnInput hideLabel label="Symbol name" value={symbolName} placeholder={`${human(selected.type)} symbol`} onChange={(e)=>setSymbolName(e.target.value)}/><button type="button" onClick={()=>{onCreateSymbol?.(symbolName.trim()||`${human(selected.type)} symbol`);setSymbolName("")}}><Plus size={12}/>Create from selected</button></div>:selected?.symbolId?<div className="vsn-email-symbol-linked"><span><Link2 size={12}/><b>{selected.symbolName||"Reusable symbol"}</b></span><button type="button" onClick={()=>onDetachSymbol?.(selected.id)}><Link2Off size={12}/>Detach selected</button></div>:<p className="vsn-email-saved-note">Select a block to convert it into a linked symbol.</p>}<div className="vsn-email-saved-list">{symbols.map(symbol=><article key={symbol.id}><div><strong>{symbol.name}</strong><small>{human(symbol.block?.type)} · {(document.blocks||[]).filter(block=>block.symbolId===symbol.id).length} linked instance(s)</small></div><div><button type="button" title="Insert linked instance" onClick={()=>onInsertSymbol?.(symbol.id)}><Copy size={12}/></button><button type="button" className="danger" title="Delete symbol definition" onClick={()=>onDeleteSymbol?.(symbol.id)}><Trash2 size={12}/></button></div></article>)}{!symbols.length?<p className="vsn-email-saved-note">No symbols in this email yet.</p>:null}</div></section><section className="vsn-email-saved-section"><div className="vsn-email-saved-head"><div><strong>Saved content blocks</strong><small>Merchant library blocks reusable across email templates.</small></div><Save size={15}/></div>{selected?<div className="vsn-email-saved-create"><VsnInput hideLabel label="Saved block name" value={blockName} placeholder={`${human(selected.type)} block`} onChange={(e)=>setBlockName(e.target.value)}/><button type="button" disabled={busy} onClick={()=>{onSaveBlock?.(blockName.trim()||`${human(selected.type)} block`,selected);setBlockName("")}}><Save size={12}/>Save selected</button></div>:null}<div className="vsn-email-saved-list">{savedBlocks.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{human(item.block?.type)} · reusable across emails</small></div><div><button type="button" title="Insert block" onClick={()=>onInsertSavedBlock?.(item)}><Plus size={12}/></button><button type="button" className="danger" title="Remove saved block" onClick={()=>onDeleteSavedBlock?.(item.id)}><Trash2 size={12}/></button></div></article>)}{!savedBlocks.length?<p className="vsn-email-saved-note">Save a selected block to build your reusable email library.</p>:null}</div></section></div>;
}
