import { useEffect, useState } from "react";
import { useFetcher } from "react-router";
import { Sparkles, WandSparkles } from "lucide-react";

export function EmailAiAssistant({document,meta,aiStatus,onReplaceEmail,onInsertBlocks,onApplyMeta}){
  const fetcher=useFetcher();const [operation,setOperation]=useState("email");const [prompt,setPrompt]=useState("");const [result,setResult]=useState(null);const busy=fetcher.state!=="idle";
  useEffect(()=>{if(fetcher.data?.intent==="ai-generate"){if(fetcher.data?.ok)setResult(fetcher.data);else setResult({error:fetcher.data?.error||"AI Email Studio failed."});}},[fetcher.data]);
  const generate=()=>{const fd=new FormData();fd.set("intent","ai-generate");fd.set("operation",operation);fd.set("prompt",prompt);fd.set("document",JSON.stringify(document||{}));fd.set("meta",JSON.stringify(meta||{}));fetcher.submit(fd,{method:"post",action:"/app/email-builder"});};
  return <div className="vsn-email-studio-side-scroll"><div className="vsn-email-ai-head"><Sparkles size={18}/><div><strong>VSN AI Email</strong><span>Structured output only — no HTML, scripts or opaque code.</span></div></div><div className="vsn-email-ai-form"><label><span>Task</span><select value={operation} onChange={(e)=>setOperation(e.target.value)}><option value="email">Generate complete email</option><option value="section">Generate section</option><option value="rewrite">Rewrite current concept</option><option value="subjects">Subject line ideas</option></select></label><label><span>Brief</span><textarea rows={7} value={prompt} onChange={(e)=>setPrompt(e.target.value)} placeholder="Audience, offer, tone, products, goal and anything that must be included..."/></label><div className="vsn-email-ai-quota"><span>{aiStatus?.configured?`${aiStatus.remaining??"—"} AI generations remaining this month`:`AI is not configured on this server`}</span><small>{aiStatus?.model||"VSN structured AI"}</small></div><button className="vsn-email-ai-generate" type="button" disabled={busy||!aiStatus?.configured||(operation!=="subjects"&&prompt.trim().length<3)} onClick={generate}><WandSparkles size={14}/>{busy?"Generating…":"Generate"}</button></div>{result?.error?<div className="vsn-email-ai-error">{result.error}</div>:result?.ok?<div className="vsn-email-ai-result"><div><strong>{result.name||"AI email"}</strong><p>{result.summary||"Structured email proposal ready."}</p></div>{result.subject?<section><b>Recommended subject</b><span>{result.subject}</span><small>{result.preheader}</small><button type="button" onClick={()=>onApplyMeta?.({subject:result.subject,preheader:result.preheader,name:result.name})}>Apply subject + preheader</button></section>:null}{result.subjectVariants?.length?<section><b>Subject variants</b>{result.subjectVariants.map((subject,index)=><button className="vsn-email-ai-subject" key={index} type="button" onClick={()=>onApplyMeta?.({subject})}>{subject}</button>)}</section>:null}{operation==="section"?<button type="button" className="vsn-email-ai-apply" onClick={()=>onInsertBlocks?.(result.document?.blocks||[])}>Insert generated blocks</button>:operation!=="subjects"?<button type="button" className="vsn-email-ai-apply" onClick={()=>onReplaceEmail?.(result.document,{name:result.name,subject:result.subject,preheader:result.preheader})}>Apply generated email</button>:null}</div>:null}</div>;
}
