import { useEffect, useState } from "react";
import { AlignCenter, AlignLeft, AlignRight, Trash2 } from "lucide-react";
import { EMAIL_BINDING_GROUPS } from "../../email/emailBindings.js";
import { plainTextFromEmailRichText } from "../../email/emailRichText.js";
import { VsnButton, VsnCard, VsnInput, VsnSelect, VsnTextarea } from "../ui/VsnToolkit.jsx";
import { EmailLogicInspector } from "./EmailLogicInspector.jsx";
import { EmailRichTextEditor } from "./EmailRichTextEditor.jsx";

const human=(value)=>String(value||"").replaceAll("-"," ").replace(/\b\w/g,(c)=>c.toUpperCase());
function TokenPicker({onInsert}){return <select className="vsn-email-token-inline" value="" onChange={(e)=>{if(e.target.value)onInsert(`{{ ${e.target.value} }}`)}}><option value="">+ Dynamic data</option>{EMAIL_BINDING_GROUPS.map(group=><optgroup key={group.key} label={group.label}>{group.tokens.map(([path,label])=><option key={path} value={path}>{label}</option>)}</optgroup>)}</select>}
function BoundInput({label,value,onChange,textarea=false,rows=3,type="text"}){const append=(token)=>onChange(`${String(value||"")}${value?" ":""}${token}`);return <div className="vsn-email-bound-field">{textarea?<VsnTextarea label={label} rows={rows} value={value||""} onChange={(e)=>onChange(e.target.value)}/>:<VsnInput type={type} label={label} value={value||""} onChange={(e)=>onChange(e.target.value)}/>}<TokenPicker onInsert={append}/></div>}
function AlignControl({value="left",onChange}){return <div className="vsn-email-align-control"><button type="button" className={value==="left"?"active":""} onClick={()=>onChange("left")}><AlignLeft size={14}/></button><button type="button" className={value==="center"?"active":""} onClick={()=>onChange("center")}><AlignCenter size={14}/></button><button type="button" className={value==="right"?"active":""} onClick={()=>onChange("right")}><AlignRight size={14}/></button></div>}

function RichBody({block,set}){const c=block.content||{};return <EmailRichTextEditor label="Rich text" value={c.textHtml||""} plainFallback={c.text||""} onChange={(html)=>set("textHtml",html,{text:plainTextFromEmailRichText(html)})}/>}

function ContentInspector({block,onChange}){
  const c=block.content||{};const set=(key,value,extra={})=>onChange({...block,content:{...c,[key]:value,...extra}});
  return <div className="vsn-email-inspector-stack">
    {block.type==="logo"?<><BoundInput label="Logo URL" value={c.src} onChange={(v)=>set("src",v)}/><BoundInput label="Alt text" value={c.alt} onChange={(v)=>set("alt",v)}/><VsnInput type="number" label="Logo width" min="60" max="360" value={c.width||140} onChange={(e)=>set("width",Number(e.target.value)||140)}/></>:null}
    {block.type==="header"?<BoundInput label="Header text" value={c.text} onChange={(v)=>set("text",v)}/>:null}
    {["hero","section","text","testimonial","image-text"].includes(block.type)?<><BoundInput label="Heading" value={c.heading} onChange={(v)=>set("heading",v)}/><RichBody block={block} set={set}/></>:null}
    {["hero","section","image-text"].includes(block.type)?<><BoundInput label="Button label" value={c.buttonText} onChange={(v)=>set("buttonText",v)}/><BoundInput label="Button URL" value={c.buttonUrl} onChange={(v)=>set("buttonUrl",v)}/></>:null}
    {block.type==="testimonial"?<><BoundInput label="Author" value={c.author} onChange={(v)=>set("author",v)}/><BoundInput label="Role / company" value={c.role} onChange={(v)=>set("role",v)}/></>:null}
    {block.type==="image-text"?<><BoundInput label="Image URL" value={c.image} onChange={(v)=>set("image",v)}/><VsnSelect label="Image position" value={c.imagePosition||"left"} onChange={(e)=>set("imagePosition",e.target.value)}><option value="left">Left</option><option value="right">Right</option></VsnSelect></>:null}
    {block.type==="image"?<><BoundInput label="Image URL" value={c.src} onChange={(v)=>set("src",v)}/><BoundInput label="Alt text" value={c.alt} onChange={(v)=>set("alt",v)}/><VsnInput type="number" label="Width" min="120" max="1200" value={c.width||560} onChange={(e)=>set("width",Number(e.target.value)||560)}/></>:null}
    {block.type==="button"?<><BoundInput label="Button label" value={c.text} onChange={(v)=>set("text",v)}/><BoundInput label="Button URL" value={c.url} onChange={(v)=>set("url",v)}/></>:null}
    {block.type==="navbar"?<div className="vsn-email-repeater"><span>Navigation links</span>{(c.links||[]).map((link,index)=><div key={index} className="vsn-email-repeater-row"><VsnInput hideLabel label="Label" value={link.label||""} onChange={(e)=>set("links",c.links.map((x,i)=>i===index?{...x,label:e.target.value}:x))}/><VsnInput hideLabel label="URL" value={link.url||""} onChange={(e)=>set("links",c.links.map((x,i)=>i===index?{...x,url:e.target.value}:x))}/><button type="button" className="vsn-email-mini-danger" onClick={()=>set("links",c.links.filter((_,i)=>i!==index))}><Trash2 size={13}/></button></div>)}<VsnButton size="xs" onClick={()=>set("links",[...(c.links||[]),{label:"Link",url:"{{ shop.url }}"}])}>Add link</VsnButton></div>:null}
    {block.type==="product"?<><BoundInput label="Image" value={c.image} onChange={(v)=>set("image",v)}/><BoundInput label="Title" value={c.title} onChange={(v)=>set("title",v)}/><BoundInput label="Price" value={c.price} onChange={(v)=>set("price",v)}/><BoundInput label="Product URL" value={c.url} onChange={(v)=>set("url",v)}/><BoundInput label="Button label" value={c.buttonText} onChange={(v)=>set("buttonText",v)}/></>:null}
    {block.type==="product-grid"?<><VsnInput type="number" label="Items" min="2" max="4" value={c.count||2} onChange={(e)=>set("count",Math.max(2,Math.min(4,Number(e.target.value)||2)))}/><BoundInput label="Heading" value={c.heading} onChange={(v)=>set("heading",v)}/><BoundInput label="Button label" value={c.buttonText} onChange={(v)=>set("buttonText",v)}/><BoundInput label="Button URL" value={c.url} onChange={(v)=>set("url",v)}/>{Array.isArray(c.items)&&c.items.length?<div className="vsn-email-product-items"><div className="vsn-email-inspector-title"><strong>Catalog products</strong><span>Edit products imported from the Commerce browser.</span></div>{c.items.map((item,index)=><VsnCard key={index} title={`Product ${index+1}`}><BoundInput label="Image" value={item.image} onChange={(v)=>set("items",c.items.map((x,i)=>i===index?{...x,image:v}:x))}/><BoundInput label="Title" value={item.title} onChange={(v)=>set("items",c.items.map((x,i)=>i===index?{...x,title:v}:x))}/><BoundInput label="Price" value={item.price} onChange={(v)=>set("items",c.items.map((x,i)=>i===index?{...x,price:v}:x))}/><BoundInput label="URL" value={item.url} onChange={(v)=>set("items",c.items.map((x,i)=>i===index?{...x,url:v}:x))}/><VsnButton size="xs" variant="danger" onClick={()=>set("items",c.items.filter((_,i)=>i!==index))}>Remove product</VsnButton></VsnCard>)}<VsnButton size="xs" onClick={()=>set("items",[])}>Use dynamic product placeholders</VsnButton></div>:null}</>:null}
    {block.type==="order-summary"?<><BoundInput label="Heading" value={c.heading} onChange={(v)=>set("heading",v)}/><BoundInput label="Line items" value={c.items} onChange={(v)=>set("items",v)}/><BoundInput label="Total" value={c.total} onChange={(v)=>set("total",v)}/></>:null}
    {block.type==="coupon"?<><BoundInput label="Label" value={c.label} onChange={(v)=>set("label",v)}/><BoundInput label="Coupon code" value={c.code} onChange={(v)=>set("code",v)}/></>:null}
    {block.type==="spacer"?<VsnInput type="number" label="Height" min="4" max="200" value={c.height||24} onChange={(e)=>set("height",Number(e.target.value)||24)}/>:null}
    {block.type==="social"?<div className="vsn-email-repeater"><span>Social links</span>{(c.links||[]).map((link,index)=><div key={index} className="vsn-email-repeater-row"><VsnInput hideLabel label="Label" value={link.label||""} onChange={(e)=>set("links",c.links.map((x,i)=>i===index?{...x,label:e.target.value}:x))}/><VsnInput hideLabel label="URL" value={link.url||""} onChange={(e)=>set("links",c.links.map((x,i)=>i===index?{...x,url:e.target.value}:x))}/><button type="button" className="vsn-email-mini-danger" onClick={()=>set("links",c.links.filter((_,i)=>i!==index))}><Trash2 size={13}/></button></div>)}<VsnButton size="xs" onClick={()=>set("links",[...(c.links||[]),{label:"Link",url:"https://"}])}>Add link</VsnButton></div>:null}
    {block.type==="columns"?<div className="vsn-email-columns-inspector"><VsnSelect label="Columns" value={String((c.columns||[]).length||2)} onChange={(e)=>{const count=Number(e.target.value);const next=[...(c.columns||[])];while(next.length<count)next.push({heading:`Column ${next.length+1}`,text:"Column text",textHtml:"",buttonText:"Learn more",buttonUrl:"{{ shop.url }}",width:Math.round(100/count)});const width=Math.round(100/count*100)/100;set("columns",next.slice(0,count).map((col,index)=>({...col,width:index===count-1?Math.round((100-width*(count-1))*100)/100:width})))}}><option value="2">2 columns</option><option value="3">3 columns</option></VsnSelect><div className="vsn-email-column-presets"><span>Width presets</span><div><button type="button" onClick={()=>{const rows=c.columns||[];if(rows.length===2)set("columns",rows.map((col,index)=>({...col,width:index===0?50:50})));else {const width=33.33;set("columns",rows.map((col,index)=>({...col,width:index===rows.length-1?33.34:width})))}}}>Equal</button>{(c.columns||[]).length===2?<><button type="button" onClick={()=>set("columns",c.columns.map((col,index)=>({...col,width:index===0?33:67})))}>33 / 67</button><button type="button" onClick={()=>set("columns",c.columns.map((col,index)=>({...col,width:index===0?67:33})))}>67 / 33</button></>:null}<button type="button" onClick={()=>{const rows=c.columns||[];const total=rows.reduce((sum,col)=>sum+Math.max(1,Number(col.width)||1),0)||100;let used=0;set("columns",rows.map((col,index)=>{const width=index===rows.length-1?Math.round((100-used)*100)/100:Math.round((Math.max(1,Number(col.width)||1)/total*100)*100)/100;used+=width;return {...col,width}}))}}>Normalize</button></div></div><label className="vsn-email-dark-toggle"><input type="checkbox" checked={c.mobileStack!==false} onChange={(e)=>set("mobileStack",e.target.checked)}/><span><strong>Stack on mobile</strong><small>Recommended for narrow email clients.</small></span></label>{(c.columns||[]).map((column,index)=><VsnCard key={index} title={`Column ${index+1} · ${Math.round(Number(column.width||0))}%`}><VsnInput type="number" label="Width %" min="10" max="90" value={Math.round(Number(column.width||0))} onChange={(e)=>set("columns",c.columns.map((x,i)=>i===index?{...x,width:Number(e.target.value)||10}:x))}/><BoundInput label="Heading" value={column.heading} onChange={(v)=>set("columns",c.columns.map((x,i)=>i===index?{...x,heading:v}:x))}/><EmailRichTextEditor label="Column text" value={column.textHtml||""} plainFallback={column.text||""} onChange={(html)=>set("columns",c.columns.map((x,i)=>i===index?{...x,textHtml:html,text:plainTextFromEmailRichText(html)}:x))}/><BoundInput label="Image URL" value={column.image} onChange={(v)=>set("columns",c.columns.map((x,i)=>i===index?{...x,image:v}:x))}/></VsnCard>)}</div>:null}
    {block.type==="footer"?<EmailRichTextEditor label="Footer content" value={c.textHtml||""} plainFallback={c.text||""} onChange={(html)=>set("textHtml",html,{text:plainTextFromEmailRichText(html)})}/>:null}
  </div>;
}

function StyleInspector({block,onChange}){const s=block.style||{};const set=(key,value)=>onChange({...block,style:{...s,[key]:value}});const alignable=["logo","header","hero","section","text","image","button","social","navbar","testimonial","footer","product-grid"].includes(block.type);return <div className="vsn-email-inspector-stack">{alignable?<div className="vsn-email-inspector-field"><span>Alignment</span><AlignControl value={s.align||"left"} onChange={(v)=>set("align",v)}/></div>:null}<VsnInput label="Padding" value={s.padding||"24px 28px"} onChange={(e)=>set("padding",e.target.value)}/><VsnInput label="Background" type="color" value={s.background||"#ffffff"} onChange={(e)=>set("background",e.target.value)}/>{["header","hero","section","text","testimonial","footer","product-grid"].includes(block.type)?<><VsnInput label="Text color" type="color" value={s.color||"#202223"} onChange={(e)=>set("color",e.target.value)}/><VsnInput type="number" label="Body size" min="10" max="32" value={s.fontSize||16} onChange={(e)=>set("fontSize",Number(e.target.value)||16)}/></>:null}{["hero","section","text","testimonial","product-grid"].includes(block.type)?<VsnInput type="number" label="Heading size" min="16" max="56" value={s.headingSize||26} onChange={(e)=>set("headingSize",Number(e.target.value)||26)}/>:null}{["button","hero","section","image-text","product","product-grid"].includes(block.type)?<><VsnInput label="Button background" type="color" value={s.buttonBackground||s.background||"#111827"} onChange={(e)=>set("buttonBackground",e.target.value)}/><VsnInput label="Button text" type="color" value={s.buttonColor||s.color||"#ffffff"} onChange={(e)=>set("buttonColor",e.target.value)}/><VsnInput type="number" label="Button radius" min="0" max="40" value={s.buttonRadius??s.radius??8} onChange={(e)=>set("buttonRadius",Number(e.target.value)||0)}/></>:null}{["image","logo","image-text","product","product-grid"].includes(block.type)?<VsnInput type="number" label="Image radius" min="0" max="40" value={s.radius||0} onChange={(e)=>set("radius",Number(e.target.value)||0)}/>:null}{block.type==="divider"?<VsnInput label="Divider color" type="color" value={s.color||"#e5e7eb"} onChange={(e)=>set("color",e.target.value)}/>:null}</div>}

function DocumentInspector({document,onChange}){const s=document.settings||{};const set=(key,value)=>onChange({...document,settings:{...s,[key]:value}});return <div className="vsn-email-inspector-stack"><div className="vsn-email-inspector-title"><strong>Global styles</strong><span>Email-safe defaults applied to every block.</span></div><VsnInput label="Canvas background" type="color" value={s.backgroundColor||"#f4f4f5"} onChange={(e)=>set("backgroundColor",e.target.value)}/><VsnInput label="Content background" type="color" value={s.contentBackground||"#ffffff"} onChange={(e)=>set("contentBackground",e.target.value)}/><VsnInput label="Content width" type="number" min="320" max="760" value={s.contentWidth||600} onChange={(e)=>set("contentWidth",Number(e.target.value)||600)}/><VsnInput label="Text color" type="color" value={s.textColor||"#202223"} onChange={(e)=>set("textColor",e.target.value)}/><VsnInput label="Link color" type="color" value={s.linkColor||"#166534"} onChange={(e)=>set("linkColor",e.target.value)}/><VsnSelect label="Email font" value={s.fontFamily||"Arial, Helvetica, sans-serif"} onChange={(e)=>set("fontFamily",e.target.value)}><option value="Arial, Helvetica, sans-serif">Arial</option><option value="Helvetica, Arial, sans-serif">Helvetica</option><option value="Georgia, serif">Georgia</option><option value="Verdana, Geneva, sans-serif">Verdana</option><option value="Tahoma, Geneva, sans-serif">Tahoma</option><option value="'Trebuchet MS', Arial, sans-serif">Trebuchet MS</option></VsnSelect><VsnInput type="number" label="Base font size" min="12" max="22" value={s.baseFontSize||16} onChange={(e)=>set("baseFontSize",Number(e.target.value)||16)}/><VsnInput type="number" label="Content radius" min="0" max="32" value={s.contentRadius||0} onChange={(e)=>set("contentRadius",Number(e.target.value)||0)}/><hr/><label className="vsn-email-dark-toggle"><input type="checkbox" checked={s.darkModeEnabled!==false} onChange={(e)=>set("darkModeEnabled",e.target.checked)}/><span><strong>Email dark mode</strong><small>Color-scheme metadata plus supported client overrides.</small></span></label>{s.darkModeEnabled!==false?<><VsnInput label="Dark canvas" type="color" value={s.darkBackgroundColor||"#0f172a"} onChange={(e)=>set("darkBackgroundColor",e.target.value)}/><VsnInput label="Dark content" type="color" value={s.darkContentBackground||"#111827"} onChange={(e)=>set("darkContentBackground",e.target.value)}/><VsnInput label="Dark text" type="color" value={s.darkTextColor||"#f3f4f6"} onChange={(e)=>set("darkTextColor",e.target.value)}/><VsnInput label="Dark links" type="color" value={s.darkLinkColor||"#b7dd70"} onChange={(e)=>set("darkLinkColor",e.target.value)}/></>:null}</div>}

export function EmailStudioInspector({document,onDocumentChange,selected,onBlockChange}){const [tab,setTab]=useState(selected?"content":"global");useEffect(()=>{setTab(selected?"content":"global")},[selected?.id]);const current=selected?(["content","style","logic"].includes(tab)?tab:"content"):"global";return <aside className="vsn-email-inspector vsn-email-studio-inspector"><div className="vsn-email-studio-inspector-head"><div><strong>{selected?human(selected.type):"Email design"}</strong><span>{selected?"Selected block":"Global styles"}</span></div>{selected?<div className="vsn-email-studio-inspector-tabs"><button type="button" className={current==="content"?"active":""} onClick={()=>setTab("content")}>Content</button><button type="button" className={current==="style"?"active":""} onClick={()=>setTab("style")}>Style</button><button type="button" className={current==="logic"?"active":""} onClick={()=>setTab("logic")}>Logic</button></div>:null}</div><div className="vsn-email-studio-inspector-scroll">{!selected?<DocumentInspector document={document} onChange={onDocumentChange}/>:current==="content"?<ContentInspector block={selected} onChange={onBlockChange}/>:current==="style"?<StyleInspector block={selected} onChange={onBlockChange}/>:<EmailLogicInspector block={selected} onChange={onBlockChange}/>}</div></aside>}
