import { normalizeEmailDocument } from "./emailSchema.js";
import { describeEmailLogic } from "./emailLogic.js";
import { sanitizeEmailRichText } from "./emailRichText.js";

function esc(value=""){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function safe(value=""){return esc(String(value??""));}
function align(value="left"){return ["left","center","right"].includes(String(value))?String(value):"left";}
function bg(style,settings){return safe(style.background||settings.contentBackground);}
function padding(style,fallback="12px 28px"){return safe(style.padding||fallback);}

function textBlock(content,style,settings){const heading=content.heading?`<mj-text align="${align(style.align)}" font-size="${Number(style.headingSize||26)}px" font-weight="700" color="${safe(style.headingColor||style.color||settings.textColor)}" padding-bottom="6px">${safe(content.heading)}</mj-text>`:"";const body=content.textHtml?sanitizeEmailRichText(content.textHtml):safe(content.text||"");return `${heading}<mj-text css-class="vsn-email-rich" align="${align(style.align)}" font-size="${Number(style.fontSize||settings.baseFontSize||16)}px" line-height="1.6" color="${safe(style.color||settings.textColor)}">${body}</mj-text>`;}
function button(content,style,settings,labelKey="text",urlKey="url"){if(!content[labelKey])return "";return `<mj-button align="${align(style.align||"center")}" href="${safe(content[urlKey]||"#")}" background-color="${safe(style.buttonBackground||"#111827")}" color="${safe(style.buttonColor||"#ffffff")}" border-radius="${Number(style.buttonRadius??8)}px" font-weight="700">${safe(content[labelKey])}</mj-button>`;}
function section(inner,s,settings){return `<mj-section background-color="${bg(s,settings)}" padding="${padding(s)}">${inner}</mj-section>`;}
function visibilityClass(block){const v=block?.visibility||{};const desktop=v.desktop!==false,mobile=v.mobile!==false;if(!desktop&&!mobile)return "vsn-email-hidden-all";if(desktop&&!mobile)return "vsn-email-desktop-only";if(!desktop&&mobile)return "vsn-email-mobile-only";return "";}
function applyVisibility(block,rendered){const cls=visibilityClass(block);if(!cls||!rendered)return rendered;return rendered.replace(/^<mj-section/,`<mj-section css-class="${cls}"`);}

function renderBlock(block,settings){const c=block.content||{},s=block.style||{};
  if(block.type==="logo")return section(`<mj-column><mj-image align="${align(s.align||"center")}" src="${safe(c.src||"")}" alt="${safe(c.alt||"")}" width="${Number(c.width||140)}px" border-radius="${Number(s.radius||0)}px" /></mj-column>`,s,settings);
  if(block.type==="header")return section(`<mj-column><mj-text align="${align(s.align||"center")}" font-size="${Number(s.fontSize||22)}px" font-weight="700" color="${safe(s.color||settings.textColor)}">${safe(c.text||"Your brand")}</mj-text></mj-column>`,s,settings);
  if(block.type==="navbar")return section(`<mj-column><mj-text align="${align(s.align||"center")}" font-size="${Number(s.fontSize||13)}px">${(c.links||[]).slice(0,8).map(link=>`<a href="${safe(link.url||"#")}" style="color:${safe(settings.linkColor)};text-decoration:none;margin:0 8px;font-weight:700;">${safe(link.label||"Link")}</a>`).join(" ")}</mj-text></mj-column>`,s,settings);
  if(block.type==="text")return section(`<mj-column>${textBlock(c,s,settings)}</mj-column>`,s,settings);
  if(block.type==="image")return section(`<mj-column><mj-image align="${align(s.align||"center")}" src="${safe(c.src||"")}" alt="${safe(c.alt||"")}" width="${Number(c.width||560)}px" border-radius="${Number(s.radius||0)}px" /></mj-column>`,s,settings);
  if(block.type==="button"){const legacyButtonStyle={...s,buttonBackground:s.buttonBackground||s.background||"#111827",buttonColor:s.buttonColor||s.color||"#ffffff",buttonRadius:s.buttonRadius??s.radius??8};return section(`<mj-column>${button(c,legacyButtonStyle,settings)}</mj-column>`,s,settings);}
  if(block.type==="divider")return section(`<mj-column><mj-divider border-color="${safe(s.color||"#e5e7eb")}" /></mj-column>`,s,settings);
  if(block.type==="spacer")return `<mj-section background-color="${bg(s,settings)}" padding="0"><mj-column><mj-spacer height="${Number(c.height||24)}px" /></mj-column></mj-section>`;
  if(block.type==="hero"||block.type==="section"){const body=c.textHtml?sanitizeEmailRichText(c.textHtml):safe(c.text||"");return section(`<mj-column><mj-text align="${align(s.align||"center")}" font-size="${Number(s.headingSize||(block.type==="hero"?34:24))}px" font-weight="800" color="${safe(s.color||settings.textColor)}">${safe(c.heading||"")}</mj-text><mj-text css-class="vsn-email-rich" align="${align(s.align||"center")}" font-size="${Number(s.fontSize||16)}px" line-height="1.6" color="${safe(s.color||settings.textColor)}">${body}</mj-text>${button({text:c.buttonText,url:c.buttonUrl},s,settings)}</mj-column>`,s,settings);}
  if(block.type==="columns")return section((c.columns||[]).slice(0,3).map(column=>`<mj-column width="${Math.max(10,Math.min(90,Number(column.width)||100/Math.max(1,c.columns.length)))}%">${column.image?`<mj-image src="${safe(column.image)}" border-radius="8px" />`:""}${column.heading?`<mj-text font-size="18px" font-weight="700">${safe(column.heading)}</mj-text>`:""}${column.textHtml?`<mj-text css-class="vsn-email-rich" font-size="14px" line-height="1.6">${sanitizeEmailRichText(column.textHtml)}</mj-text>`:column.text?`<mj-text font-size="14px" line-height="1.6">${safe(column.text)}</mj-text>`:""}${column.buttonText?`<mj-button href="${safe(column.buttonUrl||"#")}" background-color="${safe(settings.linkColor)}">${safe(column.buttonText)}</mj-button>`:""}</mj-column>`).join(""),s,settings);
  if(block.type==="image-text"){const image=`<mj-column width="46%"><mj-image src="${safe(c.image||"")}" border-radius="${Number(s.radius||8)}px" /></mj-column>`;const body=c.textHtml?sanitizeEmailRichText(c.textHtml):safe(c.text||"");const copy=`<mj-column width="54%"><mj-text font-size="${Number(s.headingSize||24)}px" font-weight="800" color="${safe(s.color||settings.textColor)}">${safe(c.heading||"")}</mj-text><mj-text css-class="vsn-email-rich" font-size="${Number(s.fontSize||15)}px" line-height="1.6" color="${safe(s.color||settings.textColor)}">${body}</mj-text>${button({text:c.buttonText,url:c.buttonUrl},{...s,align:"left"},settings)}</mj-column>`;return section(c.imagePosition==="right"?`${copy}${image}`:`${image}${copy}`,s,settings);}
  if(block.type==="testimonial"){const quote=c.textHtml?sanitizeEmailRichText(c.textHtml):safe(c.text||"");return section(`<mj-column><mj-text align="${align(s.align||"left")}" font-size="${Number(s.headingSize||18)}px" font-weight="800" color="${safe(s.color||settings.textColor)}">${safe(c.heading||"Customer story")}</mj-text><mj-text css-class="vsn-email-rich" align="${align(s.align||"left")}" font-size="${Number(s.fontSize||17)}px" font-style="italic" line-height="1.65" color="${safe(s.color||settings.textColor)}">${quote}</mj-text><mj-text align="${align(s.align||"left")}" font-size="13px" font-weight="700">${safe(c.author||"Customer")}${c.role?`<br/><span style="font-weight:400;opacity:.7">${safe(c.role)}</span>`:""}</mj-text></mj-column>`,s,settings);}
  if(block.type==="social")return section(`<mj-column><mj-text align="${align(s.align||"center")}">${(c.links||[]).slice(0,8).map(link=>`<a href="${safe(link.url||"#")}" style="color:${safe(settings.linkColor)};text-decoration:none;margin:0 8px;">${safe(link.label||"Link")}</a>`).join(" ")}</mj-text></mj-column>`,s,settings);
  if(block.type==="product")return section(`<mj-column>${c.image?`<mj-image src="${safe(c.image)}" width="180px" border-radius="8px" />`:""}<mj-text font-size="18px" font-weight="700">${safe(c.title||"{{ product.title }}")}</mj-text><mj-text color="${safe(settings.textColor)}">${safe(c.price||"{{ product.price }}")}</mj-text>${c.buttonText?`<mj-button href="${safe(c.url||"{{ product.url }}")}" background-color="${safe(s.buttonBackground||settings.linkColor)}" border-radius="${Number(s.buttonRadius??8)}px">${safe(c.buttonText)}</mj-button>`:""}</mj-column>`,s,settings);
  if(block.type==="product-grid"){const explicit=(Array.isArray(c.items)?c.items:[]).slice(0,4);const count=explicit.length||Math.max(2,Math.min(4,Number(c.count||2)));const items=explicit.length?explicit:Array.from({length:count}).map((_,index)=>({title:`${c.title||"{{ product.title }}"}${count>1?` ${index+1}`:""}`,price:c.price||"{{ product.price }}",url:c.url||"{{ product.url }}",image:"",alt:""}));return section(`<mj-column width="100%"><mj-text align="${align(s.align||"center")}" font-size="${Number(s.headingSize||24)}px" font-weight="800">${safe(c.heading||"Featured products")}</mj-text></mj-column>${items.map((item)=>`<mj-column>${item.image?`<mj-image src="${safe(item.image)}" href="${safe(item.url||"#")}" alt="${safe(item.alt||item.title||"Product")}" border-radius="7px" />`:""}<mj-text font-size="15px" font-weight="700">${safe(item.title||"Product")}</mj-text><mj-text font-size="13px">${safe(item.price||"")}</mj-text></mj-column>`).join("")}${c.buttonText?`<mj-column width="100%">${button({text:c.buttonText,url:c.url||"{{ shop.url }}"},s,settings)}</mj-column>`:""}`,s,settings);}
  if(block.type==="order-summary")return section(`<mj-column><mj-text font-weight="700">${safe(c.heading||"Order summary")}</mj-text><mj-text>${safe(c.items||"{{ order.line_items }}")}<br/>Total: ${safe(c.total||"{{ order.total_price }}")}</mj-text></mj-column>`,s,settings);
  if(block.type==="coupon")return section(`<mj-column><mj-text align="center" font-size="13px">${safe(c.label||"Use code")}</mj-text><mj-text align="center" font-size="24px" font-weight="800" letter-spacing="2px">${safe(c.code||"WELCOME10")}</mj-text></mj-column>`,s,settings);
  if(block.type==="footer"){const body=c.textHtml?sanitizeEmailRichText(c.textHtml):safe(c.text||"");return section(`<mj-column><mj-text css-class="vsn-email-rich" align="${align(s.align||"center")}" font-size="${Number(s.fontSize||12)}px" line-height="1.6" color="${safe(s.color||"#6b7280")}">${body}</mj-text></mj-column>`,s,settings);}
  return "";
}

export function renderEmailMjml(documentInput,{subject="Email",preheader=""}={}){
  const document=normalizeEmailDocument(documentInput);const s=document.settings;const body=document.blocks.map(block=>{const rendered=applyVisibility(block,renderBlock(block,s));const logic=describeEmailLogic(block);return logic.length?`<!-- VSN logic: ${safe(logic.join(" | "))} -->\n${rendered}`:rendered}).join("\n");
  return `<mjml>\n  <mj-head>\n    <mj-title>${safe(subject)}</mj-title>\n    <mj-preview>${safe(preheader)}</mj-preview>\n    <mj-attributes>\n      <mj-all font-family="${safe(s.fontFamily)}" color="${safe(s.textColor)}" font-size="${Number(s.baseFontSize||16)}px" />\n      <mj-section background-color="${safe(s.contentBackground)}" />\n    </mj-attributes>\n    ${s.darkModeEnabled?`<mj-style inline="inline">@media (prefers-color-scheme: dark){.vsn-dark-bg{background:${safe(s.darkBackgroundColor)}!important}.vsn-dark-card{background:${safe(s.darkContentBackground)}!important;color:${safe(s.darkTextColor)}!important}}</mj-style>`:""}
    <mj-style inline="inline">.vsn-email-mobile-only,.vsn-email-hidden-all{display:none!important}@media only screen and (max-width:520px){.vsn-email-desktop-only{display:none!important}.vsn-email-mobile-only{display:block!important}.vsn-email-hidden-all{display:none!important}}</mj-style>\n  </mj-head>\n  <mj-body width="${s.contentWidth}px" background-color="${safe(s.backgroundColor)}">\n${body.split("\n").map(line=>`    ${line}`).join("\n")}\n  </mj-body>\n</mjml>`;
}
