import { normalizeEmailDocument } from "./emailSchema.js";
import { resolveEmailTokens } from "./emailBindings.js";
import { describeEmailLogic, materializeEmailBlocks } from "./emailLogic.js";
import { plainTextFromEmailRichText, renderEmailRichText } from "./emailRichText.js";

function esc(value=""){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function safeUrl(value=""){const raw=String(value||"").trim();if(!raw)return "#";if(/^\{\{[\s\S]+\}\}$/.test(raw))return raw;if(/^(https?:|mailto:|tel:|\/)/i.test(raw))return raw;return "#";}
function align(value="left"){return ["left","center","right"].includes(String(value))?String(value):"left";}
function px(value,fallback){const n=Number(value);return Number.isFinite(n)?`${Math.max(0,Math.min(1200,n))}px`:fallback;}
function value(input,bindings){return bindings?resolveEmailTokens(String(input??""),bindings):String(input??"");}
function cell(inner,{padding="12px 28px",align:textAlign="left",background="transparent",className=""}={}){return `<tr><td class="${esc(className)}" align="${esc(textAlign)}" style="padding:${esc(padding)};background:${esc(background)};">${inner}</td></tr>`;}
function textClass(extra=""){return `vsn-email-copy${extra?` ${extra}`:""}`;}
function headingClass(extra=""){return `vsn-email-heading${extra?` ${extra}`:""}`;}
function linkClass(extra=""){return `vsn-email-link${extra?` ${extra}`:""}`;}

function visibilityClass(block){const v=block?.visibility||{};const desktop=v.desktop!==false,mobile=v.mobile!==false;if(!desktop&&!mobile)return "vsn-email-hidden-all";if(desktop&&!mobile)return "vsn-email-desktop-only";if(!desktop&&mobile)return "vsn-email-mobile-only";return "";}
function applyBlockVisibility(block,rendered){const cls=visibilityClass(block);if(!cls||!rendered)return rendered;return rendered.replace(/^<tr(?=[\s>])/,`<tr class="${cls}"`);}

function bulletproofButton({href,label,background="#111827",color="#ffffff",radius=8,fontSize=15,padding="13px 22px",alignValue="center"}){
  const url=esc(safeUrl(href));const text=esc(label);const bg=esc(background);const fg=esc(color);const r=Math.max(0,Number(radius)||0);const fs=Math.max(10,Number(fontSize)||15);
  const outlook=`<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="${url}" style="height:42px;v-text-anchor:middle;width:180px;" arcsize="${Math.min(50,Math.round(r*2))}%" stroke="f" fillcolor="${bg}"><w:anchorlock/><center style="color:${fg};font-family:Arial,sans-serif;font-size:${fs}px;font-weight:bold;">${text}</center></v:roundrect><![endif]-->`;
  const html=`<!--[if !mso]><!--><a class="${linkClass("vsn-email-button")}" href="${url}" style="display:inline-block;background:${bg};color:${fg};text-decoration:none;font-size:${fs}px;font-weight:700;padding:${esc(padding)};border-radius:${r}px;">${text}</a><!--<![endif]-->`;
  return `<div style="text-align:${esc(alignValue)};">${outlook}${html}</div>`;
}

function renderColumn(column,settings,bindings){
  const c=column&&typeof column==="object"?column:{};
  const image=c.image?`<img src="${esc(safeUrl(value(c.image,bindings)))}" alt="" style="display:block;width:100%;max-width:100%;height:auto;border:0;border-radius:8px;margin-bottom:12px;"/>`:"";
  const heading=c.heading?`<div class="${headingClass()}" style="font-size:18px;line-height:1.3;font-weight:700;margin:0 0 8px;color:${esc(settings.textColor)};">${esc(value(c.heading,bindings))}</div>`:"";
  const text=c.textHtml?`<div class="${textClass()} vsn-email-rich" style="font-size:14px;line-height:1.6;color:${esc(settings.textColor)};opacity:.78;">${renderEmailRichText(c.textHtml,bindings)}</div>`:c.text?`<div class="${textClass()}" style="font-size:14px;line-height:1.6;color:${esc(settings.textColor)};opacity:.78;">${esc(value(c.text,bindings))}</div>`:"";
  const button=c.buttonText?`<div style="margin-top:12px;"><a class="${linkClass()}" href="${esc(safeUrl(value(c.buttonUrl,bindings)))}" style="color:${esc(settings.linkColor)};font-size:14px;font-weight:700;text-decoration:none;">${esc(value(c.buttonText,bindings))}</a></div>`:"";
  return `${image}${heading}${text}${button}`;
}

function renderBlock(block,settings,bindings){
  const c=block.content||{},s=block.style||{};const background=s.background||settings.contentBackground;const padding=s.padding||"12px 28px";
  if(block.type==="logo")return cell(c.src?`<img src="${esc(safeUrl(value(c.src,bindings)))}" alt="${esc(value(c.alt||"",bindings))}" width="${Math.min(360,Number(c.width||140)||140)}" style="display:inline-block;max-width:100%;height:auto;border:0;border-radius:${px(s.radius,"0px")};"/>`:`<div class="${headingClass()}" style="font-size:18px;font-weight:800;color:${esc(settings.textColor)};">${esc(value(c.alt||"Brand",bindings))}</div>`,{align:align(s.align||"center"),padding,background,className:"vsn-email-surface"});
  if(block.type==="header")return cell(`<div class="${headingClass()}" style="font-size:${px(s.fontSize,"22px")};font-weight:700;color:${esc(s.color||settings.textColor)};">${esc(value(c.text||"Your brand",bindings))}</div>`,{align:align(s.align||"center"),padding,background,className:"vsn-email-surface"});
  if(block.type==="navbar")return cell((Array.isArray(c.links)?c.links:[]).slice(0,8).map(item=>`<a class="${linkClass()}" href="${esc(safeUrl(value(item.url,bindings)))}" style="color:${esc(settings.linkColor)};text-decoration:none;margin:0 9px;font-size:${px(s.fontSize,"13px")};font-weight:700;">${esc(value(item.label||"Link",bindings))}</a>`).join(""),{align:align(s.align||"center"),padding,background,className:"vsn-email-surface"});
  if(block.type==="text"){
    const heading=c.heading?`<div class="${headingClass()}" style="font-size:${px(s.headingSize,"26px")};line-height:1.25;font-weight:700;margin:0 0 12px;color:${esc(s.headingColor||s.color||settings.textColor)};">${esc(value(c.heading,bindings))}</div>`:"";
    const body=c.textHtml?renderEmailRichText(c.textHtml,bindings):esc(value(c.text||"",bindings));return cell(`${heading}<div class="${textClass()} vsn-email-rich" style="font-size:${px(s.fontSize,`${settings.baseFontSize||16}px`)};line-height:${esc(s.lineHeight||"1.6")};color:${esc(s.color||settings.textColor)};${c.textHtml?"":"white-space:pre-line;"}">${body}</div>`,{align:align(s.align),padding,background,className:"vsn-email-surface"});
  }
  if(block.type==="image")return cell(`<img src="${esc(safeUrl(value(c.src,bindings)))}" alt="${esc(value(c.alt||"",bindings))}" width="${Math.min(1200,Number(c.width||560)||560)}" style="display:block;max-width:100%;height:auto;border:0;margin:0 auto;border-radius:${px(s.radius,"0px")};"/>`,{align:align(s.align||"center"),padding,background,className:"vsn-email-surface"});
  if(block.type==="button")return cell(bulletproofButton({href:value(c.url,bindings),label:value(c.text||"Learn more",bindings),background:s.buttonBackground||s.background||"#111827",color:s.buttonColor||s.color||"#ffffff",radius:s.buttonRadius??s.radius??8,fontSize:s.fontSize||15,padding:"13px 22px",alignValue:align(s.align||"center")}),{align:align(s.align||"center"),padding,background,className:"vsn-email-surface"});
  if(block.type==="divider")return cell(`<div style="height:1px;background:${esc(s.color||"#e5e7eb")};font-size:0;line-height:0;">&nbsp;</div>`,{padding,background,className:"vsn-email-surface"});
  if(block.type==="spacer")return `<tr><td class="vsn-email-surface" height="${Math.round(Number(c.height||24)||24)}" style="height:${px(c.height,"24px")};font-size:0;line-height:0;background:${esc(background)};">&nbsp;</td></tr>`;
  if(block.type==="hero"){
    const cta=c.buttonText?bulletproofButton({href:value(c.buttonUrl,bindings),label:value(c.buttonText,bindings),background:s.buttonBackground||"#111827",color:s.buttonColor||"#ffffff",radius:s.buttonRadius??8,fontSize:15,padding:"13px 22px",alignValue:align(s.align||"center")}):"";
    const body=c.textHtml?renderEmailRichText(c.textHtml,bindings):esc(value(c.text||"",bindings));return cell(`<div class="${headingClass()}" style="font-size:${px(s.headingSize,"34px")};line-height:1.15;font-weight:800;color:${esc(s.color||settings.textColor)};margin-bottom:12px;">${esc(value(c.heading||"A better email experience",bindings))}</div><div class="${textClass()} vsn-email-rich" style="font-size:${px(s.fontSize,"16px")};line-height:1.6;color:${esc(s.color||settings.textColor)};opacity:.78;margin-bottom:18px;${c.textHtml?"":"white-space:pre-line;"}">${body}</div>${cta}`,{align:align(s.align||"center"),padding,background,className:"vsn-email-surface"});
  }
  if(block.type==="section"){
    const cta=c.buttonText?`<div style="margin-top:16px;">${bulletproofButton({href:value(c.buttonUrl,bindings),label:value(c.buttonText,bindings),background:s.buttonBackground||settings.linkColor,color:s.buttonColor||"#ffffff",radius:s.buttonRadius??7,fontSize:14,padding:"11px 18px",alignValue:align(s.align||"left")})}</div>`:"";
    const body=c.textHtml?renderEmailRichText(c.textHtml,bindings):esc(value(c.text||"",bindings));return cell(`<div class="${headingClass()}" style="font-size:${px(s.headingSize,"24px")};font-weight:800;line-height:1.3;color:${esc(s.color||settings.textColor)};margin-bottom:10px;">${esc(value(c.heading||"Section heading",bindings))}</div><div class="${textClass()} vsn-email-rich" style="font-size:${px(s.fontSize,"15px")};line-height:1.65;color:${esc(s.color||settings.textColor)};opacity:.78;${c.textHtml?"":"white-space:pre-line;"}">${body}</div>${cta}`,{align:align(s.align||"left"),padding,background,className:"vsn-email-surface"});
  }
  if(block.type==="columns"){
    const cols=(Array.isArray(c.columns)?c.columns:[]).slice(0,3);
    return cell(`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr>${cols.map(column=>{const width=Math.max(10,Math.min(90,Number(column.width)||100/Math.max(1,cols.length)));return `<td class="vsn-email-column ${c.mobileStack===false?"vsn-email-no-stack":""}" width="${width}%" valign="top" style="width:${width}%;padding:${esc(s.gap||"8px")};">${renderColumn(column,settings,bindings)}</td>`}).join("")}</tr></table>`,{padding,background,className:"vsn-email-surface"});
  }
  if(block.type==="image-text"){
    const image=`<td class="vsn-email-column" width="46%" valign="middle" style="width:46%;padding:8px;"><img src="${esc(safeUrl(value(c.image||"",bindings)))}" alt="" style="display:block;width:100%;max-width:100%;height:auto;border:0;border-radius:${px(s.radius,"8px")};"/></td>`;
    const richBody=c.textHtml?renderEmailRichText(c.textHtml,bindings):esc(value(c.text||"",bindings));const copy=`<td class="vsn-email-column" width="54%" valign="middle" style="width:54%;padding:8px;"><div class="${headingClass()}" style="font-size:${px(s.headingSize,"24px")};font-weight:800;line-height:1.3;color:${esc(s.color||settings.textColor)};margin-bottom:9px;">${esc(value(c.heading||"Image + text",bindings))}</div><div class="${textClass()} vsn-email-rich" style="font-size:${px(s.fontSize,"15px")};line-height:1.6;color:${esc(s.color||settings.textColor)};opacity:.78;">${richBody}</div>${c.buttonText?`<div style="margin-top:14px;">${bulletproofButton({href:value(c.buttonUrl,bindings),label:value(c.buttonText,bindings),background:s.buttonBackground||"#111827",color:s.buttonColor||"#ffffff",radius:s.buttonRadius??8,fontSize:14,padding:"11px 18px",alignValue:"left"})}</div>`:""}</td>`;
    return cell(`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr>${c.imagePosition==="right"?`${copy}${image}`:`${image}${copy}`}</tr></table>`,{padding,background,className:"vsn-email-surface"});
  }
  if(block.type==="testimonial"){const quote=c.textHtml?renderEmailRichText(c.textHtml,bindings):esc(value(c.text||"",bindings));return cell(`<div class="${headingClass()}" style="font-size:${px(s.headingSize,"18px")};font-weight:800;margin-bottom:10px;color:${esc(s.color||settings.textColor)};">${esc(value(c.heading||"Customer story",bindings))}</div><div class="${textClass()} vsn-email-rich" style="font-size:${px(s.fontSize,"17px")};line-height:1.65;color:${esc(s.color||settings.textColor)};font-style:italic;">${quote}</div><div style="margin-top:14px;"><strong class="${headingClass()}" style="font-size:13px;color:${esc(s.color||settings.textColor)};">${esc(value(c.author||"Customer",bindings))}</strong>${c.role?`<div class="${textClass()}" style="font-size:12px;color:${esc(s.color||settings.textColor)};opacity:.68;margin-top:2px;">${esc(value(c.role,bindings))}</div>`:""}</div>`,{align:align(s.align||"left"),padding,background,className:"vsn-email-surface"});}
  if(block.type==="social")return cell((Array.isArray(c.links)?c.links:[]).slice(0,8).map(item=>`<a class="${linkClass()}" href="${esc(safeUrl(value(item.url,bindings)))}" style="color:${esc(settings.linkColor)};text-decoration:none;margin:0 8px;font-size:13px;">${esc(value(item.label||"Link",bindings))}</a>`).join(""),{align:align(s.align||"center"),padding,background,className:"vsn-email-surface"});
  if(block.type==="product")return cell(`<div class="vsn-email-surface" style="border:1px solid #e5e7eb;border-radius:10px;padding:18px;">${value(c.image||"{{ product.image }}",bindings)?`<img src="${esc(safeUrl(value(c.image||"{{ product.image }}",bindings)))}" alt="" style="display:block;max-width:160px;width:100%;height:auto;border:0;border-radius:8px;margin:0 0 12px;"/>`:""}<strong class="${headingClass()}" style="display:block;font-size:18px;color:${esc(settings.textColor)};">${esc(value(c.title||"{{ product.title }}",bindings))}</strong><span class="${textClass()}" style="display:block;margin-top:6px;color:${esc(settings.textColor)};opacity:.7;">${esc(value(c.price||"{{ product.price }}",bindings))}</span>${c.buttonText?`<div style="margin-top:14px;"><a class="${linkClass()}" href="${esc(safeUrl(value(c.url||"{{ product.url }}",bindings)))}" style="color:${esc(settings.linkColor)};font-weight:700;text-decoration:none;">${esc(value(c.buttonText,bindings))}</a></div>`:""}</div>`,{padding,background,className:"vsn-email-surface"});
  if(block.type==="product-grid"){
    const explicit=(Array.isArray(c.items)?c.items:[]).slice(0,4);const count=explicit.length||Math.max(2,Math.min(4,Number(c.count||2)));const width=Math.floor(100/count);const items=explicit.length?explicit:Array.from({length:count}).map((_,index)=>({title:`${c.title||"{{ product.title }}"}${count>1?` ${index+1}`:""}`,price:c.price||"{{ product.price }}",url:c.url||"{{ product.url }}",image:"",alt:""}));const cards=items.map((item)=>`<td class="vsn-email-column" width="${width}%" valign="top" style="width:${width}%;padding:6px;"><div style="border:1px solid #e5e7eb;border-radius:9px;padding:12px;">${item.image?`<a href="${esc(safeUrl(value(item.url||"#",bindings)))}"><img src="${esc(safeUrl(value(item.image,bindings)))}" alt="${esc(value(item.alt||item.title||"Product",bindings))}" style="display:block;width:100%;height:auto;border:0;border-radius:7px;margin:0 0 9px;"/></a>`:""}<div class="${headingClass()}" style="font-size:15px;font-weight:700;color:${esc(settings.textColor)};">${esc(value(item.title||"Product",bindings))}</div><div class="${textClass()}" style="font-size:13px;color:${esc(settings.textColor)};opacity:.7;margin-top:5px;">${esc(value(item.price||"",bindings))}</div></div></td>`).join("");return cell(`<div class="${headingClass()}" style="font-size:${px(s.headingSize,"24px")};font-weight:800;text-align:${align(s.align||"center")};margin-bottom:14px;color:${esc(s.color||settings.textColor)};">${esc(value(c.heading||"Featured products",bindings))}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr>${cards}</tr></table>${c.buttonText?`<div style="margin-top:16px;">${bulletproofButton({href:value(c.url||"{{ shop.url }}",bindings),label:value(c.buttonText,bindings),background:s.buttonBackground||"#111827",color:s.buttonColor||"#ffffff",radius:s.buttonRadius??8,fontSize:14,padding:"11px 18px",alignValue:align(s.align||"center")})}</div>`:""}`,{padding,background,className:"vsn-email-surface"});
  }
  if(block.type==="order-summary")return cell(`<div class="vsn-email-surface" style="border:1px solid #e5e7eb;border-radius:10px;padding:18px;"><strong class="${headingClass()}" style="display:block;margin-bottom:8px;">${esc(value(c.heading||"Order summary",bindings))}</strong><div class="${textClass()}" style="font-size:14px;line-height:1.7;color:${esc(settings.textColor)};opacity:.78;">${esc(value(c.items||"{{ order.line_items }}",bindings))}<br/>Total: ${esc(value(c.total||"{{ order.total_price }}",bindings))}</div></div>`,{padding,background,className:"vsn-email-surface"});
  if(block.type==="coupon")return cell(`<div class="vsn-email-surface" style="border:1px dashed ${esc(s.borderColor||"#9ca3af")};border-radius:10px;padding:18px;text-align:center;"><div class="${textClass()}" style="font-size:13px;color:${esc(settings.textColor)};opacity:.7;">${esc(value(c.label||"Your code",bindings))}</div><div class="${headingClass()}" style="font-size:24px;font-weight:800;letter-spacing:.08em;margin-top:6px;">${esc(value(c.code||"WELCOME10",bindings))}</div></div>`,{padding,background,className:"vsn-email-surface"});
  if(block.type==="footer"){const body=c.textHtml?renderEmailRichText(c.textHtml,bindings):esc(value(c.text||"",bindings));return cell(`<div class="${textClass()} vsn-email-rich" style="font-size:${px(s.fontSize,"12px")};line-height:1.6;color:${esc(s.color||"#6b7280")};${c.textHtml?"":"white-space:pre-line;"}">${body}</div>`,{align:align(s.align||"center"),padding,background,className:"vsn-email-surface"});}
  return "";
}

function darkCss(settings){
  if(!settings.darkModeEnabled)return "";
  const bg=esc(settings.darkBackgroundColor),card=esc(settings.darkContentBackground),text=esc(settings.darkTextColor),link=esc(settings.darkLinkColor);
  return `@media (prefers-color-scheme: dark){body,.vsn-email-bg{background:${bg}!important}.vsn-email-card,.vsn-email-surface{background:${card}!important}.vsn-email-heading{color:${text}!important}.vsn-email-copy{color:${text}!important}.vsn-email-link{color:${link}!important}}[data-ogsc] .vsn-email-bg{background:${bg}!important}[data-ogsc] .vsn-email-card,[data-ogsc] .vsn-email-surface{background:${card}!important}[data-ogsc] .vsn-email-heading,[data-ogsc] .vsn-email-copy{color:${text}!important}[data-ogsc] .vsn-email-link{color:${link}!important}`;
}

export function renderEmailHtml(documentInput,{subject="Email preview",preheader="",bindings=null,appearance="auto"}={}){
  const document=normalizeEmailDocument(documentInput);const raw=document.settings;const forceDark=appearance==="dark";
  const s=forceDark?{...raw,backgroundColor:raw.darkBackgroundColor,contentBackground:raw.darkContentBackground,textColor:raw.darkTextColor,linkColor:raw.darkLinkColor}:raw;
  const rows=materializeEmailBlocks(document.blocks,bindings).map(({block,bindings:localBindings})=>{const rendered=applyBlockVisibility(block,renderBlock(block,s,localBindings));if(bindings)return rendered;const logic=describeEmailLogic(block);return logic.length?`<!-- VSN logic: ${esc(logic.join(" | "))} -->${rendered}`:rendered}).join("\n");
  const resolvedSubject=bindings?resolveEmailTokens(subject,bindings):subject;const resolvedPreheader=bindings?resolveEmailTokens(preheader,bindings):preheader;
  const schemes=raw.darkModeEnabled?'<meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark">':"";
  const forcedDark=appearance==="dark"?`.vsn-email-bg{background:${esc(raw.darkBackgroundColor)}!important}.vsn-email-card,.vsn-email-surface{background:${esc(raw.darkContentBackground)}!important}.vsn-email-heading,.vsn-email-copy{color:${esc(raw.darkTextColor)}!important}.vsn-email-link{color:${esc(raw.darkLinkColor)}!important}`:"";
  const css=`.vsn-email-rich p{margin:0 0 10px}.vsn-email-rich p:last-child{margin-bottom:0}.vsn-email-rich ul,.vsn-email-rich ol{padding-left:20px;margin:8px 0}.vsn-email-rich a{color:inherit}.vsn-email-mobile-only,.vsn-email-hidden-all{display:none!important}@media only screen and (max-width:520px){.vsn-email-column:not(.vsn-email-no-stack){display:block!important;width:100%!important;box-sizing:border-box!important}.vsn-email-desktop-only{display:none!important}.vsn-email-mobile-only{display:table-row!important}.vsn-email-hidden-all{display:none!important}}${appearance==="auto"?darkCss(raw):forcedDark}`;
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting">${schemes}<title>${esc(resolvedSubject)}</title><style>${css}</style></head><body class="vsn-email-bg" style="margin:0;padding:0;background:${esc(s.backgroundColor)};"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">${esc(resolvedPreheader)}</div><table role="presentation" class="vsn-email-bg" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background:${esc(s.backgroundColor)};"><tr><td align="center" style="padding:24px 12px;"><table role="presentation" class="vsn-email-card" width="${s.contentWidth}" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:${s.contentWidth}px;background:${esc(s.contentBackground)};font-family:${esc(s.fontFamily)};font-size:${Number(s.baseFontSize||16)}px;color:${esc(s.textColor)};border-collapse:separate;border-spacing:0;border-radius:${Number(s.contentRadius||0)}px;overflow:hidden;">${rows}</table></td></tr></table></body></html>`;
}

export function renderEmailPlainText(documentInput,{bindings=null}={}){
  const document=normalizeEmailDocument(documentInput);const lines=[];const add=(v,localBindings=bindings)=>{if(v)lines.push(localBindings?resolveEmailTokens(String(v),localBindings):String(v));};
  for(const {block,bindings:localBindings} of materializeEmailBlocks(document.blocks,bindings)){const c=block.content||{};for(const key of ["heading","title","price","label","code","buttonText","items","total","author","role","alt"]){add(c[key],localBindings)}if(c.textHtml)add(plainTextFromEmailRichText(localBindings?renderEmailRichText(c.textHtml,localBindings):c.textHtml),null);else add(c.text,localBindings);if(["button","product"].includes(block.type))add(c.url,localBindings);if(block.type==="product-grid"&&Array.isArray(c.items)){for(const item of c.items){add(item?.title,localBindings);add(item?.price,localBindings);add(item?.url,localBindings)}}if(["social","navbar"].includes(block.type)&&Array.isArray(c.links)){for(const link of c.links){add(link.label,localBindings);add(link.url,localBindings)}}if(block.type==="columns"&&Array.isArray(c.columns)){for(const col of c.columns){add(col?.heading,localBindings);if(col?.textHtml)add(plainTextFromEmailRichText(localBindings?renderEmailRichText(col.textHtml,localBindings):col.textHtml),null);else add(col?.text,localBindings);add(col?.buttonText,localBindings);add(col?.buttonUrl,localBindings)}}}
  return lines.join("\n\n").replace(/\n{3,}/g,"\n\n").trim();
}
