import { ExternalLink } from 'lucide-react';
import ecosystemManifest from '../../../config/ecosystem-manifest.json';
import { MIGRATION_ROWS } from './docsCatalog.js';

function Card({title,children}){return <section className="vsn-doc-card"><h2>{title}</h2>{children}</section>}
function Steps({children}){return <ol className="vsn-doc-steps">{children}</ol>}
function Head({group,title,children}){return <div className="vsn-doc-article-head"><span>{group}</span><h1>{title}</h1><p>{children}</p></div>}
function Grid({items}){return <div className="vsn-doc-feature-grid">{items.map(([title,text])=><div key={title}><strong>{title}</strong><span>{text}</span></div>)}</div>}
function Code({children}){return <pre className="vsn-doc-code">{children}</pre>}

export default function DocsContent({active}){
  if(active==='getting-started') return <><Head group="Basics" title="Getting Started with VSN Builder">Build through one schema-driven workspace, validate before publishing, and use System Health whenever Shopify/session data is unavailable.</Head><Card title="Recommended workflow"><Steps><li><strong>Choose the goal.</strong><span>Open Setup and choose the page, campaign, experiment or commerce workflow.</span></li><li><strong>Build visually.</strong><span>Use Canvas and verify desktop, tablet and mobile states.</span></li><li><strong>Reuse deliberately.</strong><span>Save merchant-owned resources to Saved Library; install VSN resources from Marketplace.</span></li><li><strong>Validate.</strong><span>Check accessibility, SEO, performance, permissions and storefront integrations.</span></li><li><strong>Publish safely.</strong><span>Use revisions, confirmations and Shopify-managed deployment/billing boundaries.</span></li></Steps></Card></>;
  if(active==='pages') return <><Head group="Builder" title="Pages & Templates">Create, assign, preview, publish and recover storefront documents without bypassing VSN revision and permission contracts.</Head><Card title="Page lifecycle"><Grid items={[["Create","Start blank, from a starter, or from an imported resource package."],["Edit","Use the shared visual editor and responsive states."],["Assign","Use default/resource-specific template assignments where supported."],["Publish","Publish only with the required action permission and a valid preview."],["Trash","Use reversible Trash before permanent deletion."],["Revisions","Restore known-good server revisions when a change regresses."]]}/></Card></>;
  if(active==='native-shopify') return <><Head group="Builder" title="Canvas → Shopify Native Section">Expose supported VSN designs through the Theme App Extension while keeping the shared VSN renderer as the source of truth.</Head><Card title="Workflow"><Steps><li><strong>Create reusable content.</strong><span>Build and save a supported section in VSN.</span></li><li><strong>Validate shared output.</strong><span>Compare Canvas, Preview and Storefront.</span></li><li><strong>Expose through Native Bridge.</strong><span>Publish the supported section bridge without converting the full VSN widget system into native blocks.</span></li><li><strong>Add in Theme Editor.</strong><span>Use the exposed app section in the Shopify theme.</span></li></Steps></Card></>;
  if(active==='media') return <><Head group="Builder" title="Shopify Media">Use the Shopify Files-aware picker and managed VSN media contracts rather than embedding unstable admin URLs.</Head><Card title="Media checklist"><Steps><li><strong>Select.</strong><span>Pick supported Shopify Files or managed VSN assets.</span></li><li><strong>Resolve.</strong><span>VSN resolves file IDs with the current Shopify session/scopes.</span></li><li><strong>Describe.</strong><span>Set alt text, captions and link behavior.</span></li><li><strong>Diagnose.</strong><span>If Files fail, use System Health → Shopify & Permissions.</span></li></Steps></Card></>;
  if(active==='library') return <><Head group="Builder" title="Saved Library & Marketplace">Keep merchant-owned resources and VSN-supplied resources separate even when they share one browsing shell.</Head><Card title="Resource package import"><p><strong>Inspect → Validate → Dependency check → Conflict preview → ID remap → Import → Verify → Rollback.</strong></p><p>Exports carry schema/version/dependency metadata instead of relying on raw JSON dumps.</p></Card></>;
  if(active==='motion') return <><Head group="Builder" title="Motion Library">Apply reusable VSN-native timelines at element, widget, section, component and global scopes.</Head><Card title="Catalog"><Grid items={[["Built-ins",`${ecosystemManifest.counts.motionBuiltins} unique presets`],["Animate.css names",`${ecosystemManifest.counts.animateCssPresets} VSN-native recreations`],["Reference libraries",`${ecosystemManifest.counts.motionReferenceLibraries||0} named-effect sources · ${ecosystemManifest.counts.motionReferencePresets||0} deduplicated presets`],["VSN generated",`${ecosystemManifest.counts.generatedVsnPresets} modern/spring/elastic/robust/cinematic presets`],["Duplicates removed",String(ecosystemManifest.counts.motionDuplicatesRemoved||0)],["Reduced motion","Strobe/flicker references use accessibility-safe adaptations and reduced-motion skip"]]}/></Card><Card title="Use in the editor"><p>Open Advanced → Animation & Interaction, select a Motion Library preset, then customize the copied timeline when the element needs a local variation.</p></Card></>;
  if(active==='widgets') return <><Head group="Builder" title="Widget Studio">Build reusable merchant widgets visually while sharing the same registry, field contracts and renderer pipeline as SDK widgets.</Head><Card title="Current platform inventory"><Grid items={[["Registered widgets",String(ecosystemManifest.counts.widgets)],["Field types",String(ecosystemManifest.counts.customWidgetFieldTypes)],["Template Lab","Protected HTML tokens + scoped CSS"],["SDK registry","One extension architecture; no parallel widget runtime"]]}/></Card></>;
  if(active==='queries') return <><Head group="Builder" title="Loop & Query Builder">Build one item template and repeat it over Shopify or SDK-provided data.</Head><Card title="Workflow"><Steps><li><strong>Choose a source.</strong><span>Products, Collections, Articles, Search, Metaobjects or an SDK provider.</span></li><li><strong>Filter/sort.</strong><span>Configure supported query rules and limits.</span></li><li><strong>Bind children.</strong><span>Bind content to Current Loop Item fields.</span></li><li><strong>Validate cost.</strong><span>Use Query Preview/GraphQL cost diagnostics before publishing.</span></li></Steps></Card></>;
  if(active==='ai-builder') return <><Head group="Builder" title="AI Editable Output">VSN AI output must remain structured VSN schema so generated content stays editable instead of becoming opaque HTML.</Head><Card title="Supported workflow"><p>Generate a Section or Page, transform screenshot/URL inspiration, rewrite selected copy, repair responsive layouts or request accessibility suggestions. Review the proposed structured change before applying it.</p></Card></>;
  if(active==='campaigns') return <><Head group="Growth" title="Campaigns & Floating Elements">Use the visual editor for popup, drawer, flyout and floating experiences, then add triggers, conditions, schedules and frequency caps.</Head><Card title="Targeting"><Grid items={[["Triggers","Delay, exit, scroll, click, cart state and supported events."],["Conditions","URL/product/customer/market conditions."],["Schedule","Start/end windows and active state."],["Frequency","Visitor caps to avoid repeated interruption."]]}/></Card></>;
  if(active==='cro') return <><Head group="Growth" title="CRO Experiments">Test page/section/component variants with persistent assignment, goals, attribution and guarded winner publishing.</Head><Card title="Experiment workflow"><Steps><li><strong>Select target.</strong><span>Choose a supported VSN resource.</span></li><li><strong>Define goal.</strong><span>Purchase, revenue, AOV, add-to-cart, form, click or custom event.</span></li><li><strong>Allocate traffic.</strong><span>Configure variants and visitor distribution.</span></li><li><strong>Respect guardrails.</strong><span>Use sample/confidence warnings before declaring a winner.</span></li></Steps></Card></>;
  if(active==='forms') return <><Head group="Growth" title="Forms & Automation">Build forms, collect submissions and connect supported automation/integration actions without hiding validation or consent behavior.</Head><Card title="Before publish"><Grid items={[["Fields","Validate required fields and error copy."],["Consent","Keep consent explicit where the workflow requires it."],["Submission","Test success/error states."],["Automation","Verify integrations independently from the visual form."]]}/></Card></>;
  if(active==='wishlist') return <><Head group="Commerce" title="Wishlist Commerce">Anonymous visitors use local persistence; authenticated customers use server persistence with signed app-proxy identity and local-to-server merge.</Head><Card title="Editor building blocks"><Grid items={[["Wishlist Button","Product/current-variant add/remove state."],["Wishlist Count","Shared runtime count."],["Wishlist Grid","Customer/local wishlist rendering."],["Empty State","Editable zero-item experience."]]}/></Card></>;
  if(active==='email') return <><Head group="Commerce" title="Email Studio 2.2">Build email-native documents in a full-screen Studio with reusable symbols, saved blocks, Shopify commerce, assets, rich text, visual logic, version history, marketplace templates and structured AI assistance.</Head><Card title="Studio workspace"><Grid items={[["Blocks",`${ecosystemManifest.counts.emailBlocks} email-native blocks`],["Structure","Blocks + Layers + linked Symbols"],["Saved","Merchant reusable blocks across emails"],["Commerce","Authenticated Shopify product + collection browser"],["History","Persistent before-save revisions"],["Exports","HTML, MJML source and plain text"]]}/></Card><Card title="Rich content + dynamic logic"><p>Email-safe rich text supports formatting, lists, links, alignment and merge-tag insertion. Conditions, repeat collections and desktop/mobile visibility are editable visually, while explicit product-grid data can be inserted from the Shopify Commerce browser.</p></Card><Card title="Marketplace + AI"><p>The Email Marketplace adds curated plan-aware layouts beyond basic starters. VSN AI Email uses server-only credentials, plan quotas and strict structured output; it cannot inject arbitrary HTML, scripts or unknown blocks.</p></Card><Card title="Compatibility"><p>Diagnostics cover Gmail, Outlook, Apple Mail and Yahoo patterns, compiled size, accessibility, responsive visibility, column width risks and Outlook-safe CTA fallbacks. Real inbox screenshot testing still requires an external provider.</p></Card></>;
  if(active==='assets') return <><Head group="Assets" title="Fonts & SVG Library">Manage reusable storefront assets with preview, metadata, Trash/recovery and usage-aware deletion discipline.</Head><Card title="SVG workflow"><p>Upload → sanitize/parse → persist → registry refresh → preview → edit source where supported. Preview on light/dark/checker backgrounds before use.</p></Card></>;
  if(active==='localization') return <><Head group="Data" title="Localization & Markets">Translate eligible content and validate market/locale behavior through Shopify Markets-aware data and storefront contexts.</Head><Card title="Validation"><p>Always verify language fallback, market pricing/context and localized URLs on the actual storefront preview before publishing.</p></Card></>;
  if(active==='global-code') return <><Head group="Developer" title="Global CSS & JavaScript">Use Developer Studio for revisioned, scoped storefront code with Safe Mode and rollback instead of editing theme files ad hoc.</Head><Card title="Scopes & safeguards"><Grid items={[["Scopes","Storefront, template/page, market and locale."],["Placement","Head, body start or body end."],["History","Revisions and rollback."],["Recovery","Safe Mode disables generated custom JavaScript while keeping content/styles."]]}/></Card></>;
  if(active==='graphql') return <><Head group="Developer" title="GraphQL Studio">Explore the Shopify schema and run authenticated Admin GraphQL without exceeding the app's real granted scopes.</Head><Card title="Mutation policy"><p>Mutations are disabled by default, require the GraphQL mutation permission and typed confirmation; destructive-looking mutations require the stronger confirmation path.</p></Card></>;
  if(active==='platform-intelligence') return <><Head group="Developer" title="Platform Intelligence & Control">Understand resource usage, design tokens, runtime bindings and release quality before changing shared storefront systems.</Head><Card title="Dependency / Usage Graph"><Grid items={[["Resources","Widgets, components, fonts, SVGs, queries, motion presets, bindings, conditions, email tokens and global-code targets."],["Usage edges","Shows Pages, Library resources, Emails, Experiments or Global Code records that reference each resource."],["Unreferenced","Flags zero known references; verify storefront/custom-code usage before permanent deletion."],["Search & filter","Filter by resource type or search labels/consumers."]]}/></Card><Card title="Design Tokens 2.0"><p>Semantic aliases and dark-mode overrides remain backward compatible with existing design-token storage.</p></Card><Card title="Quality & Release"><Grid items={[["Visual Regression","Structural baselines plus authenticated desktop/tablet/mobile Playwright pixel screenshots."],["Performance Budget","Node, content, media, custom-code and external-origin pressure with pass/warn/fail scoring."],["Extension Sandbox","Validate plugin permissions and network origins without installing the manifest."],["Migration Simulator","Dry-run current page/library schema migrations in memory with zero writes."],["Command Architecture","New platform mutations run in database transactions with command IDs and audit records."]]}/></Card><Card title="Platform controls"><Grid items={[["Command Palette","Ctrl/Cmd + K searches enabled VSN systems."],["Binding Inspector","Advanced → Dynamic Binding Inspector shows source, resolved preview value and fallback state."],["State / Conditions","Cart and inventory rules run across editor and storefront runtimes."],["Permissions","View, token, QA, extension and migration actions are separately server authorized."]]}/></Card></>;
  if(active==='permissions') return <><Head group="System" title="Roles & Permissions">Store owner always has full access. Other roles combine system visibility with server-enforced resource/action grants.</Head><Card title="Permission inventory"><Grid items={[["Resources",String(ecosystemManifest.counts.permissionResources)],["Sensitive actions",String(ecosystemManifest.counts.permissionActions)],["Owner","Guaranteed full access"],["Enforcement","UI state + server authorization"]]}/></Card></>;
  if(active==='health') return <><Head group="System" title="System Health">Use guided diagnostics instead of guessing when sessions, Shopify APIs, migrations or a renderer subsystem fails.</Head><Card title="Finding contract"><p><strong>Problem → Why → Impact → Fix → Verify.</strong> Run the scan again after the fix instead of treating the first successful page render as verification.</p></Card></>;
  if(active==='backups') return <><Head group="System" title="Backups, Import & Export">Protect merchant data before migrations/package upgrades and keep resource packages schema-aware.</Head><Card title="Package inventory"><p>This build contains <strong>{ecosystemManifest.counts.migrations}</strong> Prisma migration directories. Latest packaged migration: <code>{ecosystemManifest.migrations.latest||'none'}</code>.</p></Card></>;
  if(active==='migration') return <><Head group="Guides" title="Migration Guide">Preserve information architecture and design intent; VSN does not promise automatic pixel-perfect conversion from third-party builders.</Head>{MIGRATION_ROWS.map(row=><Card key={row.from} title={`${row.from} → VSN Builder`}><p><strong>Primary mapping:</strong> {row.map}</p><p><strong>Recommended approach:</strong> {row.notes}</p></Card>)}</>;
  if(active==='sdk') return <><Head group="Developers" title="Developer SDK">Extend VSN through reviewed widgets, fields, data providers, controls, renderers, template types and inspector panels.</Head><Card title="Developer commands"><Code>{`npm run plugin:validate -- ./examples/plugins/announcement-card\nnpm run plugin:test\nnpm run qa:phase14`}</Code><a className="vsn-doc-link" href="/app/pages?panel=developer-sdk">Open Plugin SDK <ExternalLink size={13}/></a></Card></>;
  if(active==='engineering') return <><Head group="Developers" title="Engineering & Testing">Architecture boundaries, migrations, security, permissions and regression tests are packaged documentation, not tribal knowledge.</Head><Card title="Release commands"><Code>{`npm run docs:generate\nnpm run qa:milestone-o\nnpm run qa:release\nnpm run migration:check\nnpm run release:check`}</Code></Card><Card title="Client/server rule"><p>Browser-importable code must never depend on <code>.server</code> modules. Sensitive operations must still be authorized again on the server.</p></Card></>;
  if(active==='production-shopify') return <><Head group="Release" title="Shopify Production Integration">Keep the development tunnel configuration separate from the production Shopify app/config and validate OAuth, scopes, webhooks, app proxy, API version and theme activation before deployment.</Head><Card title="Production workflow"><Code>{`SHOPIFY_PRODUCTION_APP_URL=https://your-app.example
SHOPIFY_PRODUCTION_CLIENT_ID=your_client_id
npm run config:production
npm run release:production:check
npm run deploy:production`}</Code></Card><Card title="Release safeguards"><Grid items={[["Named config","Production deploy always targets --config production."],["OAuth","Production callback is <app-url>/auth/callback."],["API","System Health verifies 2026-07 support and detects Shopify fall-forward."],["Webhooks","App-specific and mandatory privacy topics stay declared in TOML."],["App proxy","Storefront root remains /apps/vsn-builder; existing installs may retain a merchant-customized proxy path."],["Theme embed","Use the Theme Active badge to verify the published theme app embed before launch."]]}/></Card></>;
  if(active==='ecosystem') return <><Head group="Release" title="Ecosystem & QA">This page is backed by a source-generated manifest so release documentation can be audited against the codebase.</Head><Card title={`VSN ${ecosystemManifest.version} · Milestone ${ecosystemManifest.milestone}`}><div className="vsn-doc-metrics"><div><b>{ecosystemManifest.counts.widgets}</b><span>Widgets</span></div><div><b>{ecosystemManifest.counts.motionBuiltins}</b><span>Motion presets</span></div><div><b>{ecosystemManifest.counts.emailBlocks}</b><span>Email blocks</span></div><div><b>{ecosystemManifest.counts.customWidgetFieldTypes}</b><span>Widget field types</span></div><div><b>{ecosystemManifest.counts.migrations}</b><span>Migrations</span></div><div><b>{ecosystemManifest.counts.routeModules}</b><span>Route modules</span></div></div></Card><Card title="Documentation coverage"><Grid items={[["User docs",String(ecosystemManifest.counts.userDocs)],["Developer docs",String(ecosystemManifest.counts.developerDocs)],["Engineering docs",String(ecosystemManifest.counts.engineeringDocs)],["Milestone O audit","Manifest drift + required docs + release integration"]]}/></Card></>;
  return <div className="vsn-doc-stack"><Head group="Help" title="Frequently Asked Questions">Common setup and troubleshooting answers.</Head><Card title="Theme Active still looks wrong"><p>VSN reports published-theme app-extension activation. A development/draft theme can be enabled while the published theme remains inactive.</p></Card><Card title="A panel cannot load"><p>Retry once, then use System Health. In development, inspect the first server/client error rather than patching around the visible symptom.</p></Card><Card title="Saved Library or Marketplace?"><p>Saved Library is merchant-owned. Marketplace is VSN/remote-supplied. They can share a shell but not data ownership.</p></Card></div>;
}
