import { useEffect, useMemo, useState } from "react";
import { useFetcher } from "react-router";
import { AlertTriangle, Copy, Download, Info, Monitor, Moon, RotateCcw, Save, ShieldCheck, Smartphone, Sun, X } from "lucide-react";
import { mergeEmailBindings } from "../../email/emailBindings.js";
import { createEmailBlock, normalizeEmailBlock, normalizeEmailDocument } from "../../email/emailSchema.js";
import { analyzeEmailCompatibility } from "../../email/emailCompatibility.js";
import { renderEmailMjml } from "../../email/emailMjml.js";
import { renderEmailHtml, renderEmailPlainText } from "../../email/emailRenderer.js";
import { VsnButton } from "../ui/VsnToolkit.jsx";
import { EmailStudioCanvas } from "../email-studio/EmailStudioCanvas.jsx";
import { EmailStudioInspector } from "../email-studio/EmailStudioInspector.jsx";
import { EmailStudioSidebar } from "../email-studio/EmailStudioSidebar.jsx";
import { useEmailHistory } from "../email-studio/useEmailHistory.js";

const clone=(value)=>JSON.parse(JSON.stringify(value));
const human=(value)=>String(value||"").replaceAll("-"," ").replace(/\b\w/g,(c)=>c.toUpperCase());
function downloadText(name,text,type="text/plain"){const blob=new Blob([String(text||"")],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
function slug(value="email"){return String(value||"email").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"email"}

function CompatibilityPanel({report,onSelectIssue}){
  return <div className="vsn-email-diagnostics"><div className="vsn-email-diagnostic-summary"><div className={`vsn-email-score ${report.score>=90?"good":report.score>=75?"warn":"bad"}`}><ShieldCheck size={20}/><strong>{report.score}</strong><span>Compatibility</span></div><div><strong>{(report.htmlBytes/1024).toFixed(1)} KB compiled HTML</strong><span>{report.counts.danger} critical · {report.counts.warning} warnings · {report.counts.info} notes</span></div></div><div className="vsn-email-client-grid">{report.clients.map(client=><div key={client.key}><strong>{client.label}</strong><span>{client.platform}</span><b className={client.score>=90?"good":client.score>=75?"warn":"bad"}>{client.score}</b></div>)}</div><div className="vsn-email-issue-list">{report.issues.length?report.issues.map((item,index)=><article key={`${item.code}-${item.blockId||index}`} className={`tone-${item.severity} ${item.blockId?"is-clickable":""}`} onClick={()=>item.blockId&&onSelectIssue?.(item.blockId)}>{item.severity==="danger"||item.severity==="warning"?<AlertTriangle size={15}/>:<Info size={15}/>}<div><strong>{item.title}</strong><p>{item.message}</p>{item.clients.length?<small>{item.clients.map(human).join(" · ")}</small>:null}</div></article>):<div className="vsn-email-diagnostic-clean"><ShieldCheck size={18}/><span>No compatibility issues detected by the VSN static analyzer.</span></div>}</div></div>;
}

function SourcePanel({html,mjml,text,fileBase}){
  const [source,setSource]=useState("mjml");const value=source==="html"?html:source==="text"?text:mjml;const ext=source==="html"?"html":source==="text"?"txt":"mjml";
  const copy=async()=>{try{await navigator.clipboard.writeText(value)}catch{}}
  return <div className="vsn-email-source-panel"><div className="vsn-email-source-toolbar"><div>{[["mjml","MJML"],["html","HTML"],["text","Plain text"]].map(([key,label])=><button key={key} type="button" className={source===key?"active":""} onClick={()=>setSource(key)}>{label}</button>)}</div><div><VsnButton size="xs" icon={<Copy size={13}/>} onClick={copy}>Copy</VsnButton><VsnButton size="xs" icon={<Download size={13}/>} onClick={()=>downloadText(`${fileBase}.${ext}`,value,source==="html"?"text/html":"text/plain")}>Download</VsnButton></div></div><pre><code>{value}</code></pre></div>;
}

function PreviewPanel({html,device,appearance}){return <div className={`vsn-email-preview-frame is-${device} is-${appearance}`}><iframe title={`${appearance} email preview`} srcDoc={html}/></div>}

export function EmailVisualEditor({template,previewBindings,savedBlocks=[],commerceCatalog={},aiStatus={},onSave,onClose,busy=false}){
  const initial=useMemo(()=>normalizeEmailDocument(clone(template.document||{})),[template.id]);
  const history=useEmailHistory(initial,{limit:100});
  const emailDocument=history.state;const setDocument=history.setState;
  const [meta,setMeta]=useState(()=>({name:template.name||"Untitled email",category:template.category||"Custom",subject:template.subject||"Untitled email",preheader:template.preheader||"",status:template.status||"draft"}));
  const [selectedId,setSelectedId]=useState(emailDocument.blocks[0]?.id||"");const [view,setView]=useState("design");const [device,setDevice]=useState("desktop");const [appearance,setAppearance]=useState("light");const [zoom,setZoom]=useState(100);const [sideTab,setSideTab]=useState("blocks");const [tokenNotice,setTokenNotice]=useState("");
  const [savedSnapshot,setSavedSnapshot]=useState(()=>JSON.stringify({document:initial,meta}));
  const [versions,setVersions]=useState(()=>Array.isArray(template.versions)?template.versions:[]);const [libraryBlocks,setLibraryBlocks]=useState(()=>Array.isArray(savedBlocks)?savedBlocks:[]);const libraryFetcher=useFetcher();
  const bindings=useMemo(()=>mergeEmailBindings(undefined,previewBindings||{}),[previewBindings]);const selected=emailDocument.blocks.find(block=>block.id===selectedId)||null;
  useEffect(()=>{setLibraryBlocks(Array.isArray(savedBlocks)?savedBlocks:[])},[savedBlocks]);
  useEffect(()=>{const data=libraryFetcher.data;if(!data?.intent)return;if(data.intent==="save-reusable-block"&&data.ok&&data.item){setLibraryBlocks(current=>[data.item,...current.filter(item=>item.id!==data.item.id)]);setTokenNotice("Reusable block saved");}if(data.intent==="delete-reusable-block"&&data.ok){setLibraryBlocks(current=>current.filter(item=>item.id!==data.id));setTokenNotice("Reusable block removed");}if(data.error)setTokenNotice(data.error);const timer=setTimeout(()=>setTokenNotice(""),1800);return()=>clearTimeout(timer)},[libraryFetcher.data]);
  const exportHtml=useMemo(()=>renderEmailHtml(emailDocument,{subject:meta.subject,preheader:meta.preheader}),[emailDocument,meta.subject,meta.preheader]);
  const previewHtml=useMemo(()=>renderEmailHtml(emailDocument,{subject:meta.subject,preheader:meta.preheader,bindings,appearance}),[emailDocument,meta.subject,meta.preheader,bindings,appearance]);
  const plainText=useMemo(()=>renderEmailPlainText(emailDocument),[emailDocument]);const mjml=useMemo(()=>renderEmailMjml(emailDocument,{subject:meta.subject,preheader:meta.preheader}),[emailDocument,meta.subject,meta.preheader]);
  const compatibility=useMemo(()=>analyzeEmailCompatibility(emailDocument,{subject:meta.subject,preheader:meta.preheader,html:exportHtml}),[emailDocument,meta.subject,meta.preheader,exportHtml]);
  const dirty=savedSnapshot!==JSON.stringify({document:emailDocument,meta});const fileBase=slug(meta.name);
  const mutateBlocks=(fn)=>setDocument(current=>({...current,blocks:fn(current.blocks)}));
  const insertBlock=(input,index=emailDocument.blocks.length)=>{const normalized=normalizeEmailBlock(input||createEmailBlock("text"));const block={...clone(normalized),id:createEmailBlock(normalized.type).id};mutateBlocks(blocks=>{const next=[...blocks];next.splice(Math.max(0,Math.min(next.length,index)),0,block);return next});setSelectedId(block.id);setView("design");return block};
  const add=(type,index=emailDocument.blocks.length)=>insertBlock(createEmailBlock(type),index);
  const remove=(id)=>{mutateBlocks(blocks=>blocks.filter(block=>block.id!==id));if(selectedId===id)setSelectedId("")};
  const duplicate=(id)=>{const source=emailDocument.blocks.find(block=>block.id===id);if(!source)return;const index=emailDocument.blocks.findIndex(block=>block.id===id);insertBlock(source,index+1)};
  const move=(id,offset)=>mutateBlocks(blocks=>{const from=blocks.findIndex(block=>block.id===id);const to=Math.max(0,Math.min(blocks.length-1,from+offset));if(from<0||from===to)return blocks;const out=[...blocks];const [item]=out.splice(from,1);out.splice(to,0,item);return out});
  const updateBlock=(input)=>setDocument(current=>{const next=normalizeEmailBlock(input);if(!next.symbolId)return {...current,blocks:current.blocks.map(block=>block.id===next.id?next:block)};const symbolId=next.symbolId,symbolName=next.symbolName||current.symbols?.find(item=>item.id===symbolId)?.name||"Reusable symbol";const blocks=current.blocks.map(block=>block.symbolId===symbolId?{...clone(next),id:block.id,symbolId,symbolName}:block.id===next.id?{...next,symbolName}:block);const symbols=(current.symbols||[]).map(symbol=>symbol.id===symbolId?{...symbol,name:symbolName,block:{...clone(next),id:symbol.block?.id||createEmailBlock(next.type).id,symbolId,symbolName}}:symbol);return {...current,blocks,symbols}});
  const drop=(event,index)=>{event.preventDefault();const type=event.dataTransfer.getData("vsn/email-block-type");const id=event.dataTransfer.getData("vsn/email-block-id");if(type){add(type,index);return}if(id){mutateBlocks(blocks=>{const from=blocks.findIndex(block=>block.id===id);if(from<0)return blocks;const out=[...blocks];const [item]=out.splice(from,1);const target=from<index?index-1:index;out.splice(Math.max(0,Math.min(out.length,target)),0,item);return out});setSelectedId(id)}};
  const save=()=>{if(dirty){try{const previous=JSON.parse(savedSnapshot);setVersions(current=>[{id:`local-${Date.now()}`,label:"Before save",createdAt:new Date().toISOString(),meta:previous.meta,document:previous.document},...current].slice(0,20))}catch{}}onSave?.({...meta,document:emailDocument,versionLabel:"Before save"});setSavedSnapshot(JSON.stringify({document:emailDocument,meta}))};
  const copyToken=async(token)=>{try{await navigator.clipboard.writeText(token);setTokenNotice(`${token} copied`);setTimeout(()=>setTokenNotice(""),1600)}catch{setTokenNotice(token)}};
  const selectIssue=(id)=>{setSelectedId(id);setView("design")};
  const selectedCanUseAsset=Boolean(selected&&["logo","image","image-text","product"].includes(selected.type));
  const useAsset=(asset)=>{if(!selected||!asset?.url)return;const c=selected.content||{};let content=c;if(selected.type==="logo"||selected.type==="image")content={...c,src:asset.url,alt:c.alt||asset.alt||asset.name||""};else if(selected.type==="image-text"||selected.type==="product")content={...c,image:asset.url};updateBlock({...selected,content});setView("design")};
  const createSymbol=(name)=>{if(!selected)return;const symbolId=`symbol-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;const symbolName=String(name||"Reusable symbol").slice(0,100);const linked={...selected,symbolId,symbolName};setDocument(current=>({...current,blocks:current.blocks.map(block=>block.id===selected.id?linked:block),symbols:[...(current.symbols||[]),{id:symbolId,name:symbolName,block:{...clone(linked),id:createEmailBlock(linked.type).id}}]}));setTokenNotice("Reusable symbol created")};
  const insertSymbol=(symbolId)=>{const symbol=emailDocument.symbols?.find(item=>item.id===symbolId);if(!symbol)return;insertBlock({...symbol.block,symbolId:symbol.id,symbolName:symbol.name})};
  const detachSymbol=(id)=>setDocument(current=>({...current,blocks:current.blocks.map(block=>{if(block.id!==id)return block;const next={...block};delete next.symbolId;delete next.symbolName;return next})}));
  const deleteSymbol=(symbolId)=>setDocument(current=>({...current,symbols:(current.symbols||[]).filter(item=>item.id!==symbolId),blocks:current.blocks.map(block=>{if(block.symbolId!==symbolId)return block;const next={...block};delete next.symbolId;delete next.symbolName;return next})}));
  const saveReusableBlock=(name,block)=>{const payload=clone(block);delete payload.symbolId;delete payload.symbolName;const fd=new FormData();fd.set("intent","save-reusable-block");fd.set("name",name);fd.set("block",JSON.stringify(payload));libraryFetcher.submit(fd,{method:"post",action:"/app/email-builder"})};
  const deleteSavedBlock=(id)=>{const fd=new FormData();fd.set("intent","delete-reusable-block");fd.set("id",id);libraryFetcher.submit(fd,{method:"post",action:"/app/email-builder"})};
  const insertSavedBlock=(item)=>{if(item?.block)insertBlock(item.block)};
  const useProduct=(product)=>{let block=selected?.type==="product"?selected:createEmailBlock("product");block={...block,content:{...block.content,image:product.image||"",title:product.title||"Product",price:product.price||"",url:product.url||"{{ shop.url }}",buttonText:block.content?.buttonText||"View product"}};if(selected?.type==="product")updateBlock(block);else insertBlock(block);setSideTab("commerce")};
  const useCollection=(collection)=>{let block=selected?.type==="product-grid"?selected:createEmailBlock("product-grid");const items=(collection.products||[]).slice(0,4).map(item=>({title:item.title,price:item.price,url:item.url,image:item.image,alt:item.alt||item.title}));block={...block,content:{...block.content,heading:collection.title||"Featured collection",count:Math.max(2,items.length||2),items,url:collection.url||"{{ shop.url }}",buttonText:block.content?.buttonText||"Shop collection"}};if(selected?.type==="product-grid")updateBlock(block);else insertBlock(block);setSideTab("commerce")};
  const restoreVersion=(version)=>{if(!version?.document)return;setDocument(normalizeEmailDocument(clone(version.document)));if(version.meta)setMeta(current=>({...current,...version.meta}));setSelectedId(version.document.blocks?.[0]?.id||"");setView("design");setTokenNotice("Version restored locally — review and save")};
  const replaceAiEmail=(doc,patch={})=>{setDocument(normalizeEmailDocument(clone(doc||{})));setMeta(current=>({...current,...Object.fromEntries(Object.entries(patch).filter(([,value])=>value))}));setSelectedId(doc?.blocks?.[0]?.id||"");setView("design");setSideTab("ai")};
  const insertAiBlocks=(blocks)=>{const rows=(Array.isArray(blocks)?blocks:[]).map(input=>{const normalized=normalizeEmailBlock(input||createEmailBlock("text"));return {...clone(normalized),id:createEmailBlock(normalized.type).id}});if(!rows.length)return;setDocument(current=>({...current,blocks:[...current.blocks,...rows]}));setSelectedId(rows[rows.length-1].id);setView("design");setTokenNotice(`${rows.length} AI block${rows.length===1?"":"s"} inserted`)};
  const applyAiMeta=(patch)=>setMeta(current=>({...current,...Object.fromEntries(Object.entries(patch||{}).filter(([,value])=>value))}));

  useEffect(()=>{const key=(event)=>{const target=event.target;const editing=target?.matches?.("input,textarea,select,[contenteditable=true]");if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="s"){event.preventDefault();save();return}if(editing)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();event.shiftKey?history.redo():history.undo();return}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="y"){event.preventDefault();history.redo();return}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="d"&&selectedId){event.preventDefault();duplicate(selectedId);return}if((event.key==="Delete"||event.key==="Backspace")&&selectedId){event.preventDefault();remove(selectedId)}};window.document.addEventListener("keydown",key);return()=>window.document.removeEventListener("keydown",key)},[selectedId,emailDocument,meta,history]);

  return <div className="vsn-email-editor vsn-email-studio">
    <header className="vsn-email-studio-topbar"><div className="vsn-email-studio-title"><div><strong>{meta.name}</strong><span>{dirty?"Unsaved changes":"Saved"} · {emailDocument.blocks.length} blocks</span></div>{tokenNotice?<em>{tokenNotice}</em>:null}</div><div className="vsn-email-studio-center-tools"><button type="button" disabled={!history.canUndo} onClick={history.undo} title="Undo"><RotateCcw size={14}/>Undo</button><button type="button" disabled={!history.canRedo} onClick={history.redo} title="Redo"><RotateCcw size={14} style={{transform:"scaleX(-1)"}}/>Redo</button><span className="vsn-email-studio-divider"/>{[["design","Design"],["preview","Preview"],["diagnostics",`Diagnostics ${compatibility.counts.danger+compatibility.counts.warning||""}`],["source","Code"]].map(([key,label])=><button type="button" key={key} className={view===key?"active":""} onClick={()=>setView(key)}>{label}</button>)}</div><div className="vsn-email-studio-actions"><VsnButton size="xs" variant="primary" icon={<Save size={13}/>} loading={busy} onClick={save}>Save</VsnButton>{onClose?<button className="vsn-email-studio-close" type="button" onClick={onClose} aria-label="Close email editor"><X size={18}/></button>:null}</div></header>

    <EmailStudioSidebar active={sideTab} setActive={setSideTab} document={emailDocument} onDocumentChange={setDocument} meta={meta} setMeta={setMeta} bindings={bindings} selected={selected} selectedId={selectedId} onSelect={setSelectedId} onAdd={add} onMove={move} onDuplicate={duplicate} onRemove={remove} onCopyToken={copyToken} onUseAsset={useAsset} selectedCanUseAsset={selectedCanUseAsset} savedBlocks={libraryBlocks} commerceCatalog={commerceCatalog} aiStatus={aiStatus} versions={versions} onCreateSymbol={createSymbol} onInsertSymbol={insertSymbol} onDetachSymbol={detachSymbol} onDeleteSymbol={deleteSymbol} onSaveBlock={saveReusableBlock} onInsertSavedBlock={insertSavedBlock} onDeleteSavedBlock={deleteSavedBlock} onUseProduct={useProduct} onUseCollection={useCollection} onRestoreVersion={restoreVersion} onReplaceAiEmail={replaceAiEmail} onInsertAiBlocks={insertAiBlocks} onApplyAiMeta={applyAiMeta} busy={libraryFetcher.state!=="idle"}/>

    <main className="vsn-email-stage"><div className="vsn-email-stage-toolbar"><div className="vsn-email-inbox-preview"><span>Inbox preview</span><strong>{meta.subject||"Add a subject line"}</strong><small>{meta.preheader||"Add preheader text to control inbox preview."}</small></div><div className="vsn-email-stage-actions">{view==="preview"?<div className="vsn-email-appearance-toggle"><button type="button" className={appearance==="light"?"active":""} onClick={()=>setAppearance("light")}><Sun size={13}/>Light</button><button type="button" className={appearance==="dark"?"active":""} onClick={()=>setAppearance("dark")}><Moon size={13}/>Dark</button></div>:null}{["design","preview"].includes(view)?<><div className="vsn-email-device-toggle"><button type="button" className={device==="desktop"?"active":""} onClick={()=>setDevice("desktop")}><Monitor size={14}/>Desktop</button><button type="button" className={device==="mobile"?"active":""} onClick={()=>setDevice("mobile")}><Smartphone size={14}/>Mobile</button></div>{view==="design"?<div className="vsn-email-zoom"><button type="button" onClick={()=>setZoom(v=>Math.max(50,v-10))}>−</button><span>{zoom}%</span><button type="button" onClick={()=>setZoom(v=>Math.min(140,v+10))}>+</button></div>:null}</>:null}</div></div>
      {view==="design"?<EmailStudioCanvas document={emailDocument} bindings={bindings} selectedId={selectedId} onSelect={setSelectedId} onChangeBlock={updateBlock} onMove={move} onDuplicate={duplicate} onRemove={remove} onDrop={drop} device={device} zoom={zoom}/>:view==="preview"?<PreviewPanel html={previewHtml} device={device} appearance={appearance}/>:view==="diagnostics"?<CompatibilityPanel report={compatibility} onSelectIssue={selectIssue}/>:<SourcePanel html={exportHtml} mjml={mjml} text={plainText} fileBase={fileBase}/>} 
    </main>

    <EmailStudioInspector document={emailDocument} onDocumentChange={setDocument} selected={selected} onBlockChange={updateBlock}/>

    <footer className="vsn-email-editor-savebar"><div><strong>{compatibility.score}/100 email compatibility</strong><span>{(compatibility.htmlBytes/1024).toFixed(1)} KB HTML · Gmail, Outlook, Apple Mail and Yahoo static checks</span></div><div className="vsn-email-export-actions"><VsnButton size="xs" icon={<Download size={13}/>} onClick={()=>downloadText(`${fileBase}.html`,exportHtml,"text/html")}>HTML</VsnButton><VsnButton size="xs" onClick={()=>downloadText(`${fileBase}.mjml`,mjml,"text/plain")}>MJML</VsnButton><VsnButton size="xs" onClick={()=>downloadText(`${fileBase}.txt`,plainText)}>Text</VsnButton><VsnButton variant="primary" loading={busy} onClick={save}>Save email</VsnButton></div></footer>
  </div>;
}
