import { useState } from "react";
import { Activity, ExternalLink, Eye, EyeOff, KeyRound, RefreshCw, ShieldCheck } from "lucide-react";
import { stockQuotaProgress } from "../../../config/stock-api-usage.js";

const PROVIDERS=Object.freeze([
  {id:"unsplash",name:"Unsplash",docs:"https://unsplash.com/documentation",create:"https://unsplash.com/oauth/applications",capabilities:["Images"],description:"Create an Unsplash developer application, then copy its Access Key and Secret Key.",credentials:[{key:"accessKey",label:"Access Key",help:"Used by VSN for public photo search, lookup and download tracking."},{key:"secretKey",label:"Secret Key",help:"Stored server-side for Unsplash OAuth/user-auth flows; never sent with normal public searches."}]},
  {id:"pexels",name:"Pexels",docs:"https://www.pexels.com/api/documentation/",create:"https://www.pexels.com/api/",capabilities:["Images","Videos"],description:"Create/sign in to a Pexels account and request the API key from the official API page.",credentials:[{key:"apiKey",label:"API Key",help:"Sent server-side in the Pexels Authorization header."}]},
  {id:"pixabay",name:"Pixabay",docs:"https://pixabay.com/api/docs/",create:"https://pixabay.com/api/docs/",capabilities:["Images","Videos"],description:"Sign in on the Pixabay API documentation page to reveal your account API key. The documented API exposes images and videos; website Music/Sound Effects are not exposed by this public API.",credentials:[{key:"apiKey",label:"API Key",help:"Sent server-side as the Pixabay API key parameter."}]},
  {id:"freesound",name:"Freesound",docs:"https://freesound.org/docs/api/authentication.html",create:"https://freesound.org/apiv2/apply/",capabilities:["Audio"],description:"Create a Freesound account and apply for API credentials. Commercial API use must be separately authorized/licensed.",credentials:[{key:"apiKey",label:"API Token",help:"Used server-side for Freesound APIv2 read-only search and preview metadata."}]},
  {id:"shutterstock",name:"Shutterstock",docs:"https://api-reference.shutterstock.com/",create:"https://www.shutterstock.com/account/developers/apps",capabilities:["Images","Videos","Audio"],description:"Create a Shutterstock developer application. Search can use Consumer Key + Consumer Secret; OAuth token can be supplied for licensed/elevated workflows.",credentials:[{key:"consumerKey",label:"Consumer Key",help:"Shutterstock application consumer key."},{key:"consumerSecret",label:"Consumer Secret",help:"Shutterstock application consumer secret."},{key:"oauthToken",label:"OAuth Token (optional)",help:"Optional bearer token for authenticated Shutterstock workflows."}]},
  {id:"getty",name:"Getty/iStock",docs:"https://developers.gettyimages.com/",create:"https://developers.gettyimages.com/",capabilities:["Images","Videos"],description:"Getty Images API provides Getty and iStock content. API access and download rights depend on your Getty/iStock licensing agreement.",credentials:[{key:"apiKey",label:"API Key",help:"Required in the Getty Images Api-Key request header."},{key:"apiSecret",label:"API Secret (optional)",help:"Stored for OAuth/elevated access flows where your Getty agreement enables them."}]},
]);

function maskedFor(item,provider,key){if(provider==="unsplash")return key==="secretKey"?item.maskedSecretKey:(item.maskedAccessKey||item.maskedKey);if(provider==="shutterstock")return key==="consumerKey"?item.maskedConsumerKey:key==="consumerSecret"?item.maskedConsumerSecret:item.maskedOauthToken;if(provider==="getty"&&key==="apiSecret")return item.maskedApiSecret;return item.maskedKey;}
function configuredFor(item,provider,key){if(provider==="unsplash")return key==="secretKey"?item.secretConfigured===true:item.configured===true;if(provider==="shutterstock")return key==="consumerKey"?item.consumerKeyConfigured===true:key==="consumerSecret"?item.consumerSecretConfigured===true:item.oauthTokenConfigured===true;if(provider==="getty"&&key==="apiSecret")return item.secretConfigured===true;return item.configured===true;}
function savedState(item,provider){if(provider==="unsplash")return `${item?.configured?`Access saved ${item.maskedAccessKey||item.maskedKey||""}`:"Access Key not configured"} · ${item?.secretConfigured?`Secret saved ${item.maskedSecretKey||""}`:"Secret Key not configured"}`;if(provider==="shutterstock")return item?.configured?"Shutterstock credentials configured":"Shutterstock credentials not configured";if(provider==="getty")return item?.configured?`API key saved ${item.maskedKey||""}`.trim():"Getty/iStock API key not configured";return item?.configured?`Connected ${item.maskedKey||""}`.trim():"API key not configured";}
function dateLabel(value){if(!value)return"Never used";const d=new Date(value);return Number.isNaN(d.getTime())?"Never used":`Last used ${d.toLocaleString()}`;}

function CredentialField({provider,field,value,configured,maskedValue,onChange}){const[visible,setVisible]=useState(false),inputId=`stock-${provider}-${field.key}`;return <label className="vsn-stock-credential-field" htmlFor={inputId}><span className="vsn-stock-field-label"><KeyRound size={13}/>{field.label}</span><span className="vsn-stock-secret-input"><input id={inputId} type={visible?"text":"password"} autoComplete="new-password" spellCheck={false} value={value||""} onChange={(event)=>{const nextValue=event.currentTarget.value;onChange(nextValue);}} placeholder={configured?`Saved ${maskedValue||"credential"} — leave blank to keep`:`Paste ${field.label}`}/><button type="button" className="vsn-stock-secret-toggle" onClick={()=>setVisible((current)=>!current)} aria-label={`${visible?"Hide":"Show"} ${field.label}`}>{visible?<EyeOff size={14}/>:<Eye size={14}/>}</button></span><small>{field.help}</small></label>;}
function StyledCheckbox({checked,onChange,children}){return <label className="vsn-tool-checkbox vsn-stock-option-checkbox"><input type="checkbox" checked={checked} onChange={(event)=>onChange(event.currentTarget.checked)}/><span className="vsn-tool-checkbox-box" aria-hidden="true"/><span>{children}</span></label>;}
function PageSize({label,value,min=1,max=100,onChange}){return <label><span>{label}</span><input type="number" min={min} max={max} value={value||24} onChange={(event)=>onChange(Math.max(min,Math.min(max,Number(event.currentTarget.value)||24)))}/></label>;}

function ProviderOptions({provider,config,onConfigChange}){const setOption=(key,value)=>onConfigChange({[key]:value});if(provider==="unsplash")return <div className="vsn-stock-provider-options"><PageSize label="Images per page" value={config.imagePageSize||24} min={1} max={30} onChange={(v)=>setOption("imagePageSize",v)}/><label><span>Default order</span><select value={config.orderBy||"relevant"} onChange={(e)=>setOption("orderBy",e.currentTarget.value)}><option value="relevant">Relevant</option><option value="latest">Latest</option></select></label><label><span>Content filter</span><select value={config.contentFilter||"high"} onChange={(e)=>setOption("contentFilter",e.currentTarget.value)}><option value="high">High</option><option value="low">Low</option></select></label></div>;
if(provider==="pexels")return <div className="vsn-stock-provider-options"><PageSize label="Images per page" value={config.imagePageSize||24} max={80} onChange={(v)=>setOption("imagePageSize",v)}/><PageSize label="Videos per page" value={config.videoPageSize||18} max={80} onChange={(v)=>setOption("videoPageSize",v)}/><label><span>Preferred image size</span><select value={config.size||"large"} onChange={(e)=>setOption("size",e.currentTarget.value)}><option value="large">Large</option><option value="medium">Medium</option><option value="small">Small</option></select></label><label><span>Locale</span><input value={config.locale||"en-US"} onChange={(e)=>setOption("locale",e.currentTarget.value)}/></label></div>;
if(provider==="pixabay")return <div className="vsn-stock-provider-options vsn-stock-provider-options-pixabay"><PageSize label="Images per page" value={config.imagePageSize||24} min={3} max={200} onChange={(v)=>setOption("imagePageSize",v)}/><PageSize label="Videos per page" value={config.videoPageSize||18} min={3} max={200} onChange={(v)=>setOption("videoPageSize",v)}/><label><span>Image type</span><select value={config.imageType||"photo"} onChange={(e)=>setOption("imageType",e.currentTarget.value)}><option value="all">All</option><option value="photo">Photo</option><option value="illustration">Illustration</option><option value="vector">Vector</option></select></label><label><span>Order</span><select value={config.order||"popular"} onChange={(e)=>setOption("order",e.currentTarget.value)}><option value="popular">Popular</option><option value="latest">Latest</option></select></label><label><span>Language</span><input value={config.lang||"en"} maxLength={5} onChange={(e)=>setOption("lang",e.currentTarget.value)}/></label><StyledCheckbox checked={config.safeSearch!==false} onChange={(v)=>setOption("safeSearch",v)}>Safe search</StyledCheckbox><StyledCheckbox checked={config.editorsChoice===true} onChange={(v)=>setOption("editorsChoice",v)}>Editors' Choice</StyledCheckbox></div>;
if(provider==="freesound")return <div className="vsn-stock-provider-options"><PageSize label="Audio per page" value={config.audioPageSize||config.pageSize||24} min={6} max={100} onChange={(v)=>{setOption("audioPageSize",v);setOption("pageSize",v);}}/><label><span>Default sort</span><select value={config.sort||"score"} onChange={(e)=>setOption("sort",e.currentTarget.value)}><option value="score">Relevance</option><option value="downloads_desc">Downloads</option><option value="rating_desc">Rating</option><option value="duration_asc">Shortest</option><option value="duration_desc">Longest</option><option value="created_desc">Newest</option></select></label><StyledCheckbox checked={config.commercialOnly!==false} onChange={(v)=>setOption("commercialOnly",v)}>Hide NonCommercial sound licenses</StyledCheckbox><StyledCheckbox checked={config.commercialApiLicensed===true} onChange={(v)=>setOption("commercialApiLicensed",v)}>I have Freesound commercial API permission/license for this app</StyledCheckbox><p className="vsn-stock-provider-compliance-note">Freesound's free API use is non-commercial. Keep this provider disabled unless commercial API use is licensed/authorized.</p></div>;
if(provider==="shutterstock")return <div className="vsn-stock-provider-options"><PageSize label="Images per page" value={config.imagePageSize||24} max={100} onChange={(v)=>setOption("imagePageSize",v)}/><PageSize label="Videos per page" value={config.videoPageSize||18} max={100} onChange={(v)=>setOption("videoPageSize",v)}/><PageSize label="Audio per page" value={config.audioPageSize||24} max={100} onChange={(v)=>setOption("audioPageSize",v)}/><label><span>Default sort</span><select value={config.sort||"popular"} onChange={(e)=>setOption("sort",e.currentTarget.value)}><option value="popular">Popular</option><option value="newest">Newest</option><option value="relevance">Relevance</option><option value="random">Random</option></select></label></div>;
return <div className="vsn-stock-provider-options"><PageSize label="Images per page" value={config.imagePageSize||24} max={100} onChange={(v)=>setOption("imagePageSize",v)}/><PageSize label="Videos per page" value={config.videoPageSize||18} max={100} onChange={(v)=>setOption("videoPageSize",v)}/><label><span>Locale</span><input value={config.locale||"en-US"} onChange={(e)=>setOption("locale",e.currentTarget.value)}/></label></div>;}

function UsageRow({usage}){const calls=Number(usage?.requestCount||0),ok=Number(usage?.successCount||0),errors=Number(usage?.errorCount||0),rate=usage?.rateLimit,quota=stockQuotaProgress(rate);return <div className="vsn-stock-provider-usage"><div className="vsn-stock-provider-usage-meta"><span><Activity size={13}/><b>Usage</b></span><span>{calls} request{calls===1?"":"s"}</span><span>{ok} success</span><span className={errors?"has-error":""}>{errors} errors</span>{rate?.limit||rate?.remaining?<span>{rate.remaining??"?"}/{rate.limit??"?"} remaining</span>:null}<small>{dateLabel(usage?.lastUsedAt)}</small></div>{quota?<div className={`vsn-stock-quota-progress tone-${quota.tone}`}><div className="vsn-stock-quota-progress-head"><span><b>{quota.usedPercentRounded}% used</b> · {quota.used}/{quota.limit} calls</span><span>{quota.remainingPercentRounded}% remaining</span></div><div className="vsn-stock-quota-track" role="progressbar" aria-label="API quota used" aria-valuemin="0" aria-valuemax="100" aria-valuenow={quota.usedPercentRounded}><span style={{width:`${quota.usedPercent}%`}}/></div></div>:null}</div>;}

export default function StockImageIntegrationsSettings({stock={},credentials={},usage={},onCredentialChange,onProviderChange,onTest,testingProvider="",testing=false}){return <div className="vsn-stock-provider-settings">{PROVIDERS.map((definition)=>{const provider=definition.id,item=stock?.[provider]||{},config=item.config||{},drafts=credentials?.[provider]||{},sourceSuffix=item.source==="environment"?" · credentials from environment":"",canTest=item.configured===true&&(provider!=="freesound"||config.commercialApiLicensed===true),providerUsage=usage?.providers?.[provider];return <article className={`vsn-stock-provider-setting vsn-stock-provider-${provider}`} key={provider}><div className="vsn-stock-provider-setting-head"><div className="vsn-stock-provider-identity"><span className="vsn-stock-provider-mark" aria-hidden="true">{definition.name.slice(0,1)}</span><div><strong>{item.name||definition.name}</strong><div className="vsn-stock-capabilities">{definition.capabilities.join(" . ")}</div><small>{savedState(item,provider)}{sourceSuffix}</small></div></div><label className="toggle-switch" title={`Enable ${definition.name}`}><input type="checkbox" checked={item.enabled!==false} onChange={(event)=>onProviderChange(provider,{enabled:event.currentTarget.checked})}/><span className="toggle-slider"/></label></div><p className="vsn-stock-provider-description">{definition.description} <a href={definition.create} target="_blank" rel="noreferrer">Get/create API credentials <ExternalLink size={11}/></a></p><div className={`vsn-stock-credentials ${definition.credentials.length>1?"has-two":""}`}>{definition.credentials.map((field)=><CredentialField key={field.key} provider={provider} field={field} value={drafts[field.key]||""} configured={configuredFor(item,provider,field.key)} maskedValue={maskedFor(item,provider,field.key)} onChange={(value)=>onCredentialChange(provider,field.key,value)}/>)}</div><ProviderOptions provider={provider} config={config} onConfigChange={(patch)=>onProviderChange(provider,{config:patch})}/><UsageRow usage={providerUsage}/><div className="vsn-stock-provider-setting-footer"><a href={definition.docs} target="_blank" rel="noreferrer"><ExternalLink size={12}/> API documentation</a><button type="button" className="dashboard-secondary-action" disabled={!canTest||testing} onClick={()=>onTest(provider)}>{testing&&testingProvider===provider?<RefreshCw size={13} className="vsn-spin"/>:<ShieldCheck size={13}/>} {testing&&testingProvider===provider?"Testing…":"Test saved connection"}</button></div></article>;})}</div>;}
