import { authenticate } from "../shopify.server";
import db from "../db.server.js";
import { normalizeCampaignSettings } from "../builder/campaignSystem.js";
function readSettings(page){try{const nodes=JSON.parse(page.contentJson||"[]");return normalizeCampaignSettings(Array.isArray(nodes)?nodes.find(n=>n?.type==="template-settings")?.props||{}:{},"floating-element")}catch{return normalizeCampaignSettings({},"floating-element")}}
function starter(title){return[{id:`floating-settings-${Date.now()}`,type:"template-settings",label:"Floating settings",props:{...normalizeCampaignSettings({},"floating-element"),campaignTrigger:"delay",campaignDelayMs:500,campaignFloatingPosition:"bottom-right",campaignMaxWidth:360},styles:{},children:[]},{id:`floating-section-${Date.now()}`,type:"section",label:"Floating Element",props:{},styles:{background:{color:"#ffffff"},border:{radius:"14px"},spacing:{paddingTop:"16px",paddingRight:"18px",paddingBottom:"16px",paddingLeft:"18px"},effects:{boxShadow:"0 12px 38px rgba(0,0,0,.18)"}},children:[{id:`floating-text-${Date.now()}`,type:"text",label:"Floating message",props:{text:"Need help choosing? Talk to us."},styles:{},children:[]},{id:`floating-button-${Date.now()}`,type:"button",label:"Floating CTA",props:{text:"Contact us",url:"/pages/contact"},styles:{spacing:{marginTop:"10px"}},children:[]}]}]}
async function uniqueHandle(shop,title){const base=String(title||"floating-element").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"floating-element";let handle=base,i=1;while(await db.builderPage.findFirst({where:{shop,handle}})){i++;handle=`${base}-${i}`}return handle}
export async function loader({request}){const{session}=await authenticate.admin(request);const rows=await db.builderPage.findMany({where:{shop:session.shop,template:"floating-element",deletedAt:null},orderBy:{updatedAt:"desc"}});return{items:rows.map(row=>({...row,settings:readSettings(row)}))}}
export async function action({request}){const{session}=await authenticate.admin(request);const form=await request.formData();const intent=String(form.get("intent")||"");if(intent==="create"){const title=String(form.get("title")||"Floating CTA").trim().slice(0,140)||"Floating CTA";const row=await db.builderPage.create({data:{shop:session.shop,title,handle:await uniqueHandle(session.shop,title),template:"floating-element",status:"draft",workflowStatus:"draft",contentJson:JSON.stringify(starter(title))}});return Response.json({ok:true,intent,pageId:row.id,message:"Floating element created."})}const id=String(form.get("id")||"");const row=await db.builderPage.findFirst({where:{id,shop:session.shop,template:"floating-element",deletedAt:null}});if(!row)return Response.json({ok:false,error:"Floating element not found."},{status:404});if(intent==="duplicate"){const title=`${row.title} Copy`;const copy=await db.builderPage.create({data:{shop:session.shop,title,handle:await uniqueHandle(session.shop,title),template:"floating-element",status:"draft",workflowStatus:"draft",contentJson:row.contentJson}});return Response.json({ok:true,intent,pageId:copy.id,message:"Floating element duplicated."})}if(intent==="trash"){await db.builderPage.update({where:{id},data:{deletedAt:new Date()}});return Response.json({ok:true,intent,id,message:"Floating element moved to Trash."})}return Response.json({ok:false,error:"Unsupported floating element action."},{status:400})}
export default function FloatingElementsRoute(){return null}
