import { authenticate } from "../shopify.server";
import db from "../db.server.js";
import { sanitizeSvg, safeSvgName, safeSvgFileName, serializeSvgAsset } from "../services/svg-assets.server.js";
import { assertTrustedMutationRequest } from "../utils/request-security.server.js";
async function list(shop, deletedAt){const rows=await db.builderSvgAsset.findMany({where:{shop,deletedAt},orderBy:{updatedAt:"desc"}});return rows.map(serializeSvgAsset);}
export async function loader({request}){const {session}=await authenticate.admin(request);const url=new URL(request.url);const active=await list(session.shop,null);if(url.searchParams.get("mode")==="picker")return Response.json({ok:true,files:active,count:active.length});const trash=await list(session.shop,{not:null});return Response.json({ok:true,files:active,trash});}
export async function action({request}){
  assertTrustedMutationRequest(request);const {session}=await authenticate.admin(request);let form;try{form=await request.formData();}catch(error){console.error("VSN SVG upload form parse failed:",error);return Response.json({ok:false,error:"The upload could not be read. Choose the file again; if it still fails, check the file size and restart the development server."},{status:400});}const intent=String(form.get("intent")||"");const id=String(form.get("id")||"");const row=id?await db.builderSvgAsset.findFirst({where:{id,shop:session.shop}}):null;
  if(intent==="trash"){if(!row)return Response.json({ok:false,error:"SVG not found."},{status:404});await db.builderSvgAsset.update({where:{id},data:{deletedAt:new Date()}});return Response.json({ok:true,intent,id,message:"SVG moved to Trash."});}
  if(intent==="restore"){if(!row)return Response.json({ok:false,error:"SVG not found."},{status:404});const asset=await db.builderSvgAsset.update({where:{id},data:{deletedAt:null}});return Response.json({ok:true,intent,id,asset:serializeSvgAsset(asset),message:"SVG restored."});}
  if(intent==="hard-delete"){if(!row)return Response.json({ok:false,error:"SVG not found."},{status:404});await db.builderSvgAsset.delete({where:{id}});return Response.json({ok:true,intent,id,message:"SVG permanently deleted."});}
  if(intent==="update"){if(!row)return Response.json({ok:false,error:"SVG not found."},{status:404});let svgText=row.svgText;const text=String(form.get("svgText")||"").trim();if(text)try{svgText=sanitizeSvg(text)}catch(error){return Response.json({ok:false,error:error.message},{status:400})}const asset=await db.builderSvgAsset.update({where:{id},data:{name:safeSvgName(form.get("name"),row.name),fileName:safeSvgFileName(form.get("fileName"),row.fileName),tags:String(form.get("tags")||"").trim().slice(0,500)||null,svgText}});return Response.json({ok:true,intent,id,asset:serializeSvgAsset(asset),message:"SVG updated."});}
  if(intent==="import-url"){
    const sourceUrl=String(form.get("url")||"").trim();let parsed;try{parsed=new URL(sourceUrl)}catch{return Response.json({ok:false,error:"Invalid Shopify SVG URL."},{status:400})}
    const host=parsed.hostname.toLowerCase();if(parsed.protocol!=="https:"||!(host.endsWith("shopify.com")||host.endsWith("shopifycdn.net")||host.endsWith("cdn.shopify.com")))return Response.json({ok:false,error:"Only Shopify-hosted SVG URLs can be imported."},{status:400});
    const response=await fetch(sourceUrl,{headers:{Accept:"image/svg+xml,text/plain"},signal:AbortSignal.timeout?.(8000)});if(!response.ok)return Response.json({ok:false,error:`Could not read Shopify SVG (${response.status}).`},{status:400});const raw=await response.text();let svgText;try{svgText=sanitizeSvg(raw)}catch(error){return Response.json({ok:false,error:error.message},{status:400})}
    const fileName=safeSvgFileName(form.get("fileName")||parsed.pathname.split("/").pop()||"shopify.svg");const asset=await db.builderSvgAsset.create({data:{shop:session.shop,name:safeSvgName(form.get("name"),fileName.replace(/\.svg$/i,"")),fileName,tags:"shopify-import",svgText}});return Response.json({ok:true,intent,asset:serializeSvgAsset(asset),message:"Shopify SVG imported into the VSN library."});
  }
  if(intent!=="upload")return Response.json({ok:false,error:"Unsupported SVG action."},{status:400});
  const file=form.get("file");let raw=String(form.get("svgText")||"").trim();let fileName=safeSvgFileName(form.get("fileName")||"custom.svg");if(file&&typeof file.text==="function"&&file.size>0){if(file.size>512*1024)return Response.json({ok:false,error:"SVG files must be 512 KB or smaller."},{status:400});raw=await file.text();fileName=safeSvgFileName(file.name);}if(!raw)return Response.json({ok:false,error:"Choose an SVG file or paste SVG markup."},{status:400});let svgText;try{svgText=sanitizeSvg(raw)}catch(error){return Response.json({ok:false,error:error.message},{status:400})}const asset=await db.builderSvgAsset.create({data:{shop:session.shop,name:safeSvgName(form.get("name"),fileName.replace(/\.svg$/i,"")),fileName,tags:String(form.get("tags")||"").trim().slice(0,500)||null,svgText}});return Response.json({ok:true,intent,asset:serializeSvgAsset(asset),message:"SVG added to the VSN library."});
}
export default function SvgAssetsRoute(){return null;}
