import { useLoaderData } from "react-router";
import { authenticate } from "../shopify.server";
import db from "../db.server.js";
import { OVERLAY_CAMPAIGN_TEMPLATE_TYPES, normalizeCampaignSettings, campaignScheduleState, campaignDateMs } from "../builder/campaignSystem.js";

function readSettings(page) { try { const nodes=JSON.parse(page.contentJson||page.publishedJson||"[]"); const settings=Array.isArray(nodes)?nodes.find((node)=>node?.type==="template-settings")?.props||{}:{}; return normalizeCampaignSettings(settings,page.template); } catch { return normalizeCampaignSettings({},page.template); } }
function starterContent(template,title){const settings={id:`campaign-settings-${Date.now()}`,type:"template-settings",label:"Campaign settings",props:normalizeCampaignSettings({},template),styles:{},children:[]};const section={id:`campaign-section-${Date.now()}`,type:"section",label:title,props:{},styles:{spacing:{paddingTop:"36px",paddingRight:"32px",paddingBottom:"36px",paddingLeft:"32px"}},children:[{id:`campaign-heading-${Date.now()}`,type:"heading",label:"Campaign heading",props:{text:title,tag:"h2"},styles:{typography:{fontSize:"32px",fontWeight:"700"}},children:[]},{id:`campaign-text-${Date.now()}`,type:"text",label:"Campaign text",props:{text:"Edit this campaign in the VSN visual builder."},styles:{spacing:{marginTop:"10px",marginBottom:"18px"}},children:[]},{id:`campaign-button-${Date.now()}`,type:"button",label:"Action",props:{text:"Shop now",url:"/collections/all"},styles:{},children:[]}]};return [settings,section]}
async function uniqueHandle(shop,title){const base=String(title||"campaign").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"campaign";let handle=base,i=1;while(await db.builderPage.findFirst({where:{shop,handle}})){i++;handle=`${base}-${i}`}return handle}
export const loader=async({request})=>{const {session}=await authenticate.admin(request);const pages=await db.builderPage.findMany({where:{shop:session.shop,deletedAt:null,template:{in:OVERLAY_CAMPAIGN_TEMPLATE_TYPES}},orderBy:[{updatedAt:"desc"}]});const items=pages.map((page)=>{const settings=readSettings(page);return{id:page.id,title:page.title,template:page.template,status:page.status,updatedAt:page.updatedAt,settings,scheduleState:campaignScheduleState(settings),startMs:campaignDateMs(settings.campaignStart,settings.campaignTimezone),endMs:campaignDateMs(settings.campaignEnd,settings.campaignTimezone)}});for(const item of items)item.conflicts=items.filter((other)=>other.id!==item.id&&item.settings.campaignEnabled!==false&&other.settings.campaignEnabled!==false&&(()=>{const a1=Number.isFinite(item.startMs)?item.startMs:-Infinity,a2=Number.isFinite(item.endMs)?item.endMs:Infinity,b1=Number.isFinite(other.startMs)?other.startMs:-Infinity,b2=Number.isFinite(other.endMs)?other.endMs:Infinity;return Math.max(a1,b1)<=Math.min(a2,b2)})()).map((other)=>({id:other.id,title:other.title}));return{items,templates:OVERLAY_CAMPAIGN_TEMPLATE_TYPES};};
export async function action({request}){const {session}=await authenticate.admin(request);const form=await request.formData();const intent=String(form.get("intent")||"");if(intent==="create"){const template=OVERLAY_CAMPAIGN_TEMPLATE_TYPES.includes(String(form.get("template")))?String(form.get("template")):"popup";const title=String(form.get("title")||`${template.replace(/-/g," ")} campaign`).trim().slice(0,140)||"Campaign";const page=await db.builderPage.create({data:{shop:session.shop,title,handle:await uniqueHandle(session.shop,title),template,isDefault:false,status:"draft",workflowStatus:"draft",contentJson:JSON.stringify(starterContent(template,title))}});return Response.json({ok:true,intent,pageId:page.id,message:"Campaign created."});}const id=String(form.get("id")||"");const row=id?await db.builderPage.findFirst({where:{id,shop:session.shop,template:{in:OVERLAY_CAMPAIGN_TEMPLATE_TYPES},deletedAt:null}}):null;if(!row)return Response.json({ok:false,error:"Campaign not found."},{status:404});if(intent==="duplicate"){const title=`${row.title} Copy`;const copy=await db.builderPage.create({data:{shop:session.shop,title,handle:await uniqueHandle(session.shop,title),template:row.template,isDefault:false,status:"draft",workflowStatus:"draft",contentJson:row.contentJson}});return Response.json({ok:true,intent,pageId:copy.id,message:"Campaign duplicated."});}if(intent==="trash"){await db.builderPage.update({where:{id},data:{deletedAt:new Date()}});return Response.json({ok:true,intent,id,message:"Campaign moved to Trash."});}return Response.json({ok:false,error:"Unsupported campaign action."},{status:400});}
function stateClass(state){return state==="active"?"bg-green-50 text-green-700":state==="scheduled"?"bg-amber-50 text-amber-700":state==="expired"?"bg-slate-100 text-slate-600":"bg-red-50 text-red-700";}
export default function CampaignsRoute(){const{items}=useLoaderData();return <s-page heading="Campaign Calendar"><s-stack direction="block" gap="base"><s-section><p className="text-sm text-[#6d7175]">Popup, modal, drawer, flyout and announcement overlay campaigns.</p></s-section><div className="grid gap-3">{items.map((item)=><article key={item.id} className="rounded-xl border border-[#e3e3e3] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><strong>{item.title}</strong><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${stateClass(item.scheduleState)}`}>{item.scheduleState}</span></div><p className="mt-1 text-xs text-[#6d7175]">{item.template} · {item.status} · {item.settings.campaignTrigger} · {item.settings.campaignFrequency}</p></div><a className="rounded-lg border border-[#c9cccf] px-3 py-2 text-xs font-semibold text-[#202223] no-underline" href={`/app/builder/${encodeURIComponent(item.id)}`}>Edit campaign</a></div></article>)}{!items.length?<div className="rounded-xl border border-dashed border-[#c9cccf] bg-white p-8 text-center text-sm text-[#6d7175]">No campaigns yet.</div>:null}</div></s-stack></s-page>}
