import { useMemo, useState } from "react";
import { ELEMENTS, ELEMENT_CATEGORIES } from "../../data/elements";
import NavigatorPanel from "./NavigatorPanel";
import PropertiesPanel from "./PropertiesPanel";
import EditorRecoveryBoundary from "./EditorRecoveryBoundary";
import { normalizeElementInteractions } from "../../builder/interactionSchema.js";
import PolarisIcon, { WidgetPolarisIcon } from "../ui/PolarisIcon";

function attachDragPreview(event,label){if(typeof document==="undefined"||!event?.dataTransfer)return;document.querySelectorAll("[data-vsn-drag-preview]").forEach(n=>n.remove());const p=document.createElement("div");p.dataset.vsnDragPreview="true";p.textContent=label||"Widget";Object.assign(p.style,{position:"fixed",left:"-10000px",top:"-10000px",zIndex:"99999",padding:"8px 12px",borderRadius:"8px",background:"#1A1F36",color:"#fff",font:"600 12px Inter, system-ui, sans-serif",boxShadow:"0 8px 24px rgba(0,0,0,.22)"});document.body.appendChild(p);event.dataTransfer.setDragImage(p,18,14);setTimeout(()=>p.remove(),0)}

function TipButton({ label, active = false, children, ...props }){return <button type="button" {...props} data-tooltip={label} className={`vsn-editor-icon-button ${active?"is-active":""}`} aria-label={label}>{children}</button>}

function WidgetCard({element,onDragStart,onClick}){return <div role="button" tabIndex={0} draggable onClick={()=>onClick?.(element.type)} onKeyDown={(e)=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onClick?.(element.type)}}} onDragStart={e=>{e.dataTransfer.clearData();e.dataTransfer.effectAllowed="copy";e.dataTransfer.setData("elementType",element.type);e.dataTransfer.setData("vsnDragKind","new-widget");e.dataTransfer.setData("text/plain",`vsn-widget:${element.type}`);attachDragPreview(e,element.label);document.documentElement.dataset.vsnDragging="1";onDragStart?.(element.type)}} onDragEnd={()=>{delete document.documentElement.dataset.vsnDragging}} className="vsn-home-widget-card"><span className="vsn-home-widget-icon"><WidgetPolarisIcon widgetType={element.type} size={19}/></span><span>{element.label}</span></div>}

export default function ElementsSidebar({onDragStart,onWidgetClick,insertTarget=null,onCancelInsertTarget,activeTab,onTabChange,elements=[],selectedId=null,selectedElement=null,onSelect,onMove,onMoveNode,onRename,onToggleHidden,onToggleLocked,onDuplicate,onDelete,width=384,enabledWidgetIds=null,inspectorTab="content",onInspectorTabChange,onUpdate,globalStyles,onGlobalStylesChange,deviceMode,reusableSections=[],libraryItems=[],componentDefinitions=[],componentUsage={},bindingContext={},onApplyLibraryStyle,onSaveCurrentStyle,onUnlinkGlobalSection,onSaveComponentVariant,onUpdateComponentMaster}){
 const [search,setSearch]=useState("");const [openCategories,setOpenCategories]=useState(()=>new Set(ELEMENT_CATEGORIES.map(i=>i.id)));const normalized=search.trim().toLowerCase();
 const available=useMemo(()=>{if(!Array.isArray(enabledWidgetIds))return ELEMENTS;const enabled=new Set(enabledWidgetIds);return ELEMENTS.filter(e=>enabled.has(e.type))},[enabledWidgetIds]);
 const results=useMemo(()=>normalized?available.filter(e=>`${e.label} ${e.type}`.toLowerCase().includes(normalized)):[],[available,normalized]);
 const navigator=activeTab==="navigator"||activeTab==="layers";const inspector=Boolean(selectedElement)&&activeTab==="inspector";const selectedInteractions=normalizeElementInteractions(selectedElement?.interactions);
 const toggleCategory=id=>setOpenCategories(c=>{const n=new Set(c);n.has(id)?n.delete(id):n.add(id);return n});
 return <aside className="vsn-editor-sidebar" style={{width}}>
   <div className="vsn-editor-sidebar-header">
     <div><strong>{inspector?(selectedElement?.label||"Widget settings"):navigator?"Navigator":"Widgets"}</strong><span>{inspector?"Content, style and advanced options":navigator?"Page structure":"Drag widgets to canvas"}</span></div>
     <div className="vsn-editor-sidebar-actions">
       {selectedElement?<TipButton label="All widgets" active={activeTab==="elements"} onClick={()=>onTabChange?.("elements")}><PolarisIcon type="widgets" size={16}/></TipButton>:null}
       <TipButton label="Navigator" active={navigator} onClick={()=>onTabChange?.("navigator")}><PolarisIcon type="navigator" size={16}/></TipButton>
       {selectedElement?<TipButton label="Widget settings" active={inspector} onClick={()=>onTabChange?.("inspector")}><PolarisIcon type="settings" size={16}/></TipButton>:null}
     </div>
   </div>
   {insertTarget && !inspector && !navigator ? <div className="mx-3 mt-3 flex items-center justify-between gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-[11px] text-emerald-800"><span><strong>Add child:</strong> click any widget below.</span><button type="button" onClick={()=>onCancelInsertTarget?.()} className="font-semibold underline">Cancel</button></div> : null}
   {inspector?<div className="vsn-editor-inspector-shell"><EditorRecoveryBoundary resetKey={`${selectedElement?.id || "none"}:${selectedInteractions.sticky?1:0}:${selectedInteractions.stickyBoundary}:${selectedInteractions.stickyOffset}:${selectedInteractions.stickyEndOffset}:${selectedInteractions.stickyZIndex}:${selectedInteractions.parallax?1:0}:${selectedInteractions.entrance}:${selectedInteractions.hover}`}><PropertiesPanel selectedElement={selectedElement} onUpdate={onUpdate} onDelete={onDelete} activeTab={inspectorTab} onTabChange={onInspectorTabChange} globalStyles={globalStyles} onGlobalStylesChange={onGlobalStylesChange} deviceMode={deviceMode} reusableSections={reusableSections} libraryItems={libraryItems} componentDefinitions={componentDefinitions} componentUsage={componentUsage} bindingContext={bindingContext} onApplyLibraryStyle={onApplyLibraryStyle} onSaveCurrentStyle={onSaveCurrentStyle} onUnlinkGlobalSection={onUnlinkGlobalSection} onSaveComponentVariant={onSaveComponentVariant} onUpdateComponentMaster={onUpdateComponentMaster} width="100%"/></EditorRecoveryBoundary></div>:navigator?<NavigatorPanel elements={elements} selectedId={selectedId} onSelect={onSelect} onMove={onMove} onMoveNode={onMoveNode} onRename={onRename} onToggleHidden={onToggleHidden} onToggleLocked={onToggleLocked} onDuplicate={onDuplicate} onDelete={onDelete}/>:<>
     <div className="vsn-editor-search-row"><div className="vsn-editor-search"><PolarisIcon type="search" size={15}/><input value={search} placeholder="Search widgets..." onChange={e=>setSearch(e.target.value)}/>{search?<button type="button" aria-label="Clear search" onClick={()=>setSearch("")}><PolarisIcon type="x" size={14}/></button>:null}</div></div>
     <div className="vsn-editor-sidebar-scroll">{normalized?<div><div className="vsn-editor-result-label"><span>Search results</span><span>{results.length}</span></div><div className="vsn-editor-widget-grid">{results.map(e=><WidgetCard key={e.id} element={e} onDragStart={onDragStart} onClick={onWidgetClick}/>)}</div>{!results.length?<p className="vsn-editor-empty">No widgets found</p>:null}</div>:<div className="vsn-editor-category-list">{ELEMENT_CATEGORIES.map(cat=>{const list=available.filter(e=>e.category===cat.id);const open=openCategories.has(cat.id);return <section key={cat.id} className="vsn-editor-category"><button type="button" className="vsn-editor-category-toggle" onClick={()=>toggleCategory(cat.id)}><span><PolarisIcon type={open?"chevron-down":"chevron-right"} size={14}/>{cat.label}</span><b>{list.length}</b></button>{open?<div className="vsn-editor-widget-grid">{list.map(e=><WidgetCard key={e.id} element={e} onDragStart={onDragStart} onClick={onWidgetClick}/>)}</div>:null}</section>})}</div>}</div>
   </>}
 </aside>
}
