import { useEffect, useMemo, useState } from "react";
import { VsnButton, VsnCheckbox, VsnNumberField, VsnOption, VsnSelect, VsnTextField } from "./EditorUi";
import {
  MOTION_ACTION_OPTIONS,
  MOTION_EASING_OPTIONS,
  MOTION_TARGET_OPTIONS,
  MOTION_TRIGGER_OPTIONS,
  createInteractionPreset,
  createMotionAction,
  createMotionTimeline,
  motionConflictWarnings,
  normalizeElementInteractions,
  normalizeMotionTimeline,
  timelinesFromLegacyPresets,
} from "../../builder/interactionSchema.js";

function Select({ label, value, options, onChange }) {
  return <VsnSelect label={label} value={value ?? ""} onChange={(e)=>onChange?.(e.currentTarget.value)}>{options.map((option)=><VsnOption key={option.value} value={option.value}>{option.label}</VsnOption>)}</VsnSelect>;
}
function NumberField({ label, value, min=0, max=120000, step=1, onChange }) {
  return <VsnNumberField label={label} min={String(min)} max={String(max)} step={String(step)} value={String(value ?? 0)} onInput={(e)=>onChange?.(Number(e.currentTarget.value)||0)}/>;
}
function TimelineOverview({ timeline }) {
  const duration=Math.max(1,Number(timeline?.timeline?.duration||400));
  const actions=Array.isArray(timeline?.actions)?timeline.actions:[];
  return <div className="rounded-lg border border-[#e3e3e3] bg-[#fafafa] p-2.5"><div className="mb-2 flex items-center justify-between"><strong className="text-[10px] uppercase tracking-wide text-[#6d7175]">Visual timeline</strong><span className="text-[10px] text-[#8c9196]">{duration} ms</span></div><div className="space-y-1.5">{actions.map((action,index)=>{const points=action.type==="animate"?[0,...(action.keyframes||[]).map(item=>Math.max(0,Math.min(1,Number(item.offset||0)))),1]:[Math.max(0,Math.min(1,Number(action.delay||0)/duration))];return <div key={action.id||index} className="grid grid-cols-[72px_1fr] items-center gap-2"><span className="truncate text-[9px] font-medium text-[#6d7175]">{action.type} {index+1}</span><div className="relative h-5 rounded bg-white ring-1 ring-[#ececec]"><i className="absolute left-0 top-1/2 h-px w-full -translate-y-1/2 bg-[#dfe3e8]"/>{points.map((point,pointIndex)=><b key={pointIndex} className="absolute top-1/2 h-2.5 w-2.5 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-[#95BF47] shadow-sm" style={{left:`${point*100}%`}}/>)}</div></div>})}{!actions.length?<span className="text-[10px] text-[#8c9196]">Add an action to create a motion track.</span>:null}</div></div>;
}

function ActionEditor({ action, onChange, onRemove }) {
  const patch=(next)=>onChange?.({...action,...next});
  const patchTarget=(next)=>patch({target:{...(action.target||{}),...next}});
  const patchFrame=(key,next)=>patch({[key]:{...(action[key]||{}),...next}});
  const needsSelector=["child","sibling","page-selector"].includes(action.target?.mode);
  return <div className="space-y-2 rounded-lg border border-[#e3e3e3] bg-white p-2.5">
    <div className="grid grid-cols-2 gap-2"><Select label="Action" value={action.type} options={MOTION_ACTION_OPTIONS} onChange={(type)=>patch({type})}/><Select label="Target" value={action.target?.mode||"self"} options={MOTION_TARGET_OPTIONS} onChange={(mode)=>patchTarget({mode})}/></div>
    {needsSelector?<VsnTextField label="Target selector" value={action.target?.selector||""} placeholder=".card / [data-vsn-id=…]" onInput={(e)=>patchTarget({selector:e.currentTarget.value})}/>:null}
    {action.target?.mode==="component-slot"?<VsnTextField label="Component slot" value={action.target?.slot||""} placeholder="content" onInput={(e)=>patchTarget({slot:e.currentTarget.value})}/>:null}
    {action.type==="animate"?<div className="space-y-2 rounded-md bg-[#fafafa] p-2">
      <p className="text-[10px] font-semibold uppercase tracking-wide text-[#6d7175]">From</p>
      <div className="grid grid-cols-3 gap-2"><NumberField label="Opacity" value={action.from?.opacity ?? 1} min={0} max={1} step={0.05} onChange={(opacity)=>patchFrame("from",{opacity})}/><NumberField label="X" value={action.from?.x||0} min={-10000} max={10000} onChange={(x)=>patchFrame("from",{x})}/><NumberField label="Y" value={action.from?.y||0} min={-10000} max={10000} onChange={(y)=>patchFrame("from",{y})}/></div>
      <div className="grid grid-cols-3 gap-2"><NumberField label="Scale" value={action.from?.scale ?? 1} min={0} max={100} step={0.05} onChange={(scale)=>patchFrame("from",{scale})}/><NumberField label="Rotate" value={action.from?.rotate||0} min={-36000} max={36000} onChange={(rotate)=>patchFrame("from",{rotate})}/><VsnTextField label="Filter" value={action.from?.filter||""} placeholder="blur(4px)" onInput={(e)=>patchFrame("from",{filter:e.currentTarget.value})}/></div>
      <p className="text-[10px] font-semibold uppercase tracking-wide text-[#6d7175]">To</p>
      <div className="grid grid-cols-3 gap-2"><NumberField label="Opacity" value={action.to?.opacity ?? 1} min={0} max={1} step={0.05} onChange={(opacity)=>patchFrame("to",{opacity})}/><NumberField label="X" value={action.to?.x||0} min={-10000} max={10000} onChange={(x)=>patchFrame("to",{x})}/><NumberField label="Y" value={action.to?.y||0} min={-10000} max={10000} onChange={(y)=>patchFrame("to",{y})}/></div>
      <div className="grid grid-cols-3 gap-2"><NumberField label="Scale" value={action.to?.scale ?? 1} min={0} max={100} step={0.05} onChange={(scale)=>patchFrame("to",{scale})}/><NumberField label="Rotate" value={action.to?.rotate||0} min={-36000} max={36000} onChange={(rotate)=>patchFrame("to",{rotate})}/><VsnTextField label="Filter" value={action.to?.filter||""} placeholder="blur(0)" onInput={(e)=>patchFrame("to",{filter:e.currentTarget.value})}/></div>
      <div className="mt-2 border-t border-[#e3e3e3] pt-2"><div className="mb-2 flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#6d7175]">Intermediate keyframes</p><VsnButton type="button" size="sm" onClick={()=>patch({keyframes:[...(action.keyframes||[]),{id:`kf-${Date.now()}`,offset:.5,frame:{opacity:1,x:0,y:0,scale:1,rotate:0,filter:""}}]})}>Add Keyframe</VsnButton></div>{(action.keyframes||[]).map((keyframe,index)=><div key={keyframe.id||index} className="mb-2 rounded-md border border-[#ececec] bg-white p-2"><div className="grid grid-cols-3 gap-2"><NumberField label="Position %" value={Math.round(Number(keyframe.offset||.5)*100)} min={1} max={99} onChange={(value)=>patch({keyframes:action.keyframes.map((item,i)=>i===index?{...item,offset:value/100}:item)})}/><NumberField label="X" value={keyframe.frame?.x||0} min={-10000} max={10000} onChange={(x)=>patch({keyframes:action.keyframes.map((item,i)=>i===index?{...item,frame:{...(item.frame||{}),x}}:item)})}/><NumberField label="Y" value={keyframe.frame?.y||0} min={-10000} max={10000} onChange={(y)=>patch({keyframes:action.keyframes.map((item,i)=>i===index?{...item,frame:{...(item.frame||{}),y}}:item)})}/></div><div className="mt-2 grid grid-cols-3 gap-2"><NumberField label="Opacity" value={keyframe.frame?.opacity??1} min={0} max={1} step={.05} onChange={(opacity)=>patch({keyframes:action.keyframes.map((item,i)=>i===index?{...item,frame:{...(item.frame||{}),opacity}}:item)})}/><NumberField label="Scale" value={keyframe.frame?.scale??1} min={0} max={100} step={.05} onChange={(scale)=>patch({keyframes:action.keyframes.map((item,i)=>i===index?{...item,frame:{...(item.frame||{}),scale}}:item)})}/><VsnButton type="button" tone="critical" size="sm" onClick={()=>patch({keyframes:action.keyframes.filter((_,i)=>i!==index)})}>Remove</VsnButton></div></div>)}</div>
    </div>:null}
    {action.type==="class-toggle"?<VsnTextField label="Class name" value={action.className||""} onInput={(e)=>patch({className:e.currentTarget.value})}/>:null}
    {action.type==="style-variable"?<div className="grid grid-cols-2 gap-2"><VsnTextField label="CSS variable" value={action.variable||""} placeholder="--progress" onInput={(e)=>patch({variable:e.currentTarget.value})}/><VsnTextField label="Value" value={action.value||""} placeholder="1" onInput={(e)=>patch({value:e.currentTarget.value})}/></div>:null}
    {action.type==="scroll-to"?<div className="grid grid-cols-2 gap-2"><VsnTextField label="Scroll selector" value={action.selector||""} placeholder="#contact" onInput={(e)=>patch({selector:e.currentTarget.value})}/><Select label="Behavior" value={action.behavior||"smooth"} options={[{value:"smooth",label:"Smooth"},{value:"auto",label:"Instant"}]} onChange={(behavior)=>patch({behavior})}/></div>:null}
    {action.type==="popup-open"?<VsnTextField label="Popup selector" value={action.selector||""} placeholder="Campaign page ID or [data-vsn-campaign-id=…]" onInput={(e)=>patch({selector:e.currentTarget.value})}/>:null}
    {action.type==="custom-event"?<div className="space-y-2"><VsnTextField label="Event name" value={action.eventName||""} placeholder="vsn:custom-event" onInput={(e)=>patch({eventName:e.currentTarget.value})}/><VsnTextField label="Event detail (JSON/text)" value={action.eventDetail||""} onInput={(e)=>patch({eventDetail:e.currentTarget.value})}/></div>:null}
    <div className="grid grid-cols-3 gap-2"><NumberField label="Action delay" value={action.delay||0} max={120000} onChange={(delay)=>patch({delay})}/><NumberField label="Duration override" value={action.duration ?? 0} max={120000} onChange={(duration)=>patch({duration})}/><Select label="Easing" value={action.easing||"inherit"} options={[{value:"inherit",label:"Use Timeline"},...MOTION_EASING_OPTIONS]} onChange={(easing)=>patch({easing})}/></div>
    <VsnButton type="button" tone="critical" size="sm" onClick={onRemove}>Remove Action</VsnButton>
  </div>;
}

export default function InteractionTimelinePanel({ value, elementId, onChange, globalMotionTimeline = null }) {
  const interactions=normalizeElementInteractions(value);
  const [selectedId,setSelectedId]=useState(interactions.timelines[0]?.id||"");
  const [library,setLibrary]=useState([]);
  const [libraryId,setLibraryId]=useState("");
  const [libraryBusy,setLibraryBusy]=useState(false);
  const [libraryMessage,setLibraryMessage]=useState("");
  const loadLibrary=async()=>{try{const response=await fetch("/app/builder-panel/animations",{headers:{Accept:"application/json"},credentials:"same-origin"});const data=await response.json();if(response.ok){setLibrary([...(data.builtins||[]),...(data.presets||[])]);setLibraryMessage("");}else setLibraryMessage(data?.error||"Motion Library could not be loaded.");}catch{setLibraryMessage("Motion Library could not be loaded.");}};
  useEffect(()=>{loadLibrary();},[]);
  const selected=interactions.timelines.find((item)=>item.id===selectedId)||interactions.timelines[0]||null;
  const warnings=useMemo(()=>motionConflictWarnings(interactions),[value]);
  const commit=(timelines)=>onChange?.({timelines:timelines.map(normalizeMotionTimeline)});
  const patchSelected=(patch)=>{if(!selected)return;commit(interactions.timelines.map((item)=>item.id===selected.id?normalizeMotionTimeline({...item,...patch}):item));};
  const add=(preset="")=>{const next=preset?createInteractionPreset(preset):createMotionTimeline();commit([...interactions.timelines,next]);setSelectedId(next.id);};
  const remove=()=>{if(!selected)return;const next=interactions.timelines.filter((item)=>item.id!==selected.id);commit(next);setSelectedId(next[0]?.id||"");};
  const duplicate=()=>{if(!selected)return;const next=createMotionTimeline({...selected,id:undefined,name:`${selected.name} Copy`});commit([...interactions.timelines,next]);setSelectedId(next.id);};
  const applyLibraryPreset=(preset)=>{if(!preset?.timeline)return;const next=createMotionTimeline({...preset.timeline,id:undefined,name:preset.name||preset.timeline.name});commit([...interactions.timelines,next]);setSelectedId(next.id);};
  const saveSelectedToLibrary=async()=>{if(!selected||libraryBusy)return;setLibraryBusy(true);setLibraryMessage("");try{const body=new FormData();body.set("intent","create");body.set("name",selected.name||"Animation");body.set("description","Saved from the VSN visual editor.");body.set("category","custom");body.set("scope","global");body.set("timeline",JSON.stringify(selected));const response=await fetch("/app/builder-panel/animations",{method:"POST",body,credentials:"same-origin",headers:{Accept:"application/json"}});const data=await response.json();if(!response.ok||!data?.ok)throw new Error(data?.error||"Could not save animation.");setLibraryMessage("Saved to Motion Library.");await loadLibrary();}catch(error){setLibraryMessage(error instanceof Error?error.message:"Could not save animation.");}finally{setLibraryBusy(false);}};
  const trigger=selected?.trigger||{}; const timeline=selected?.timeline||{};
  return <div className="space-y-3">
    {(interactions.entrance!=="none"||interactions.hover!=="none")?<div className="rounded-lg border border-sky-200 bg-sky-50 p-2.5 text-[10px] text-sky-900"><div className="flex items-center justify-between gap-2"><span>Legacy animation presets are still supported. Convert them into editable timelines when ready.</span><VsnButton type="button" size="sm" onClick={()=>{const converted=timelinesFromLegacyPresets(interactions);if(converted.length){onChange?.({entrance:"none",hover:"none",timelines:[...interactions.timelines,...converted]});setSelectedId(converted[0].id);}}}>Convert</VsnButton></div></div>:null}
    <div className="rounded-lg border border-[#dfe3e8] bg-[#fafbfb] p-2.5">
      <div className="mb-2 flex items-center justify-between"><div><strong className="text-xs">Interaction Timeline</strong><p className="text-[10px] text-[#6d7175]">Trigger → Conditions → Timeline → Actions</p></div><VsnButton type="button" size="sm" onClick={()=>add()}>Add</VsnButton></div>
      <div className="grid grid-cols-2 gap-2"><Select label="Preset" value="" options={[{value:"",label:"Choose preset"},{value:"fade-up",label:"Fade Up"},{value:"click-scale",label:"Click Scale"},{value:"hover-lift",label:"Hover Lift"},{value:"scroll-progress",label:"Scroll Progress"}]} onChange={(v)=>v&&add(v)}/>{interactions.timelines.length?<Select label="Interaction" value={selected?.id||""} options={interactions.timelines.map((item)=>({value:item.id,label:item.name}))} onChange={setSelectedId}/>:<div className="flex items-end pb-1 text-[10px] text-[#8c9196]">No advanced interactions yet.</div>}</div>
    </div>
    <div className="rounded-lg border border-[#dfe3e8] bg-white p-2.5"><div className="mb-2"><strong className="text-xs">Motion Library</strong><p className="text-[10px] text-[#6d7175]">Reuse saved animations across widgets, elements and pages.</p></div><div className="grid grid-cols-2 gap-2"><Select label="Saved animation" value={libraryId} options={[{value:"",label:"Choose animation"},...library.map((item)=>({value:item.id,label:`${item.builtin?"VSN · ":""}${item.name}`}))]} onChange={setLibraryId}/><div className="flex items-end"><VsnButton type="button" size="sm" disabled={!libraryId} onClick={()=>applyLibraryPreset(library.find((item)=>item.id===libraryId))}>Apply</VsnButton></div></div>{globalMotionTimeline?<div className="mt-2"><VsnButton type="button" size="sm" onClick={()=>applyLibraryPreset({name:"Page Motion Default",timeline:globalMotionTimeline})}>Apply Page Default</VsnButton></div>:null}{libraryMessage?<p className="mt-2 text-[10px] text-[#6d7175]">{libraryMessage}</p>:null}</div>
    {selected?<div className="space-y-3">
      <VsnTextField label="Name" value={selected.name} onInput={(e)=>patchSelected({name:e.currentTarget.value})}/>
      <VsnCheckbox checked={selected.enabled!==false} onChange={(e)=>patchSelected({enabled:e.currentTarget.checked})}>Enabled</VsnCheckbox>
      <div className="rounded-lg border border-[#e3e3e3] p-2.5 space-y-2"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#6d7175]">Trigger</p><Select label="Trigger" value={trigger.type} options={MOTION_TRIGGER_OPTIONS} onChange={(type)=>patchSelected({trigger:{...trigger,type}})}/>{["viewport-enter","viewport-exit"].includes(trigger.type)?<NumberField label="Viewport threshold" value={trigger.threshold??0.15} min={0} max={1} step={0.05} onChange={(threshold)=>patchSelected({trigger:{...trigger,threshold}})}/>:null}{trigger.type==="custom-event"?<VsnTextField label="Event name" value={trigger.eventName||""} placeholder="vsn:custom" onInput={(e)=>patchSelected({trigger:{...trigger,eventName:e.currentTarget.value}})}/>:null}{["click","hover","focus","form-submit"].includes(trigger.type)?<VsnTextField label="Trigger selector (optional)" value={trigger.selector||""} placeholder=".button / form" onInput={(e)=>patchSelected({trigger:{...trigger,selector:e.currentTarget.value}})}/>:null}<VsnCheckbox checked={trigger.once===true} onChange={(e)=>patchSelected({trigger:{...trigger,once:e.currentTarget.checked}})}>Run once</VsnCheckbox></div>
      <div className="rounded-lg border border-[#e3e3e3] p-2.5 space-y-2"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#6d7175]">Conditions</p><VsnButton type="button" size="sm" onClick={()=>patchSelected({conditions:[...(selected.conditions||[]),{type:"media-query",key:"",value:"(min-width: 768px)",negate:false}]})}>Add Condition</VsnButton></div>{!(selected.conditions||[]).length?<p className="text-[10px] text-[#8c9196]">No conditions. This interaction can run whenever its trigger fires.</p>:(selected.conditions||[]).map((condition,index)=><div key={`${condition.type}-${index}`} className="space-y-2 rounded-md bg-[#fafafa] p-2"><Select label="Condition" value={condition.type} options={[{value:"media-query",label:"Media Query"},{value:"selector-exists",label:"Selector Exists"},{value:"attribute-equals",label:"Attribute Equals"},{value:"reduced-motion",label:"Reduced Motion Preference"}]} onChange={(type)=>patchSelected({conditions:selected.conditions.map((item,i)=>i===index?{...item,type}:item)})}/>{condition.type==="attribute-equals"?<div className="grid grid-cols-2 gap-2"><VsnTextField label="Attribute" value={condition.key||""} placeholder="data-state" onInput={(e)=>patchSelected({conditions:selected.conditions.map((item,i)=>i===index?{...item,key:e.currentTarget.value}:item)})}/><VsnTextField label="Equals" value={condition.value||""} placeholder="open" onInput={(e)=>patchSelected({conditions:selected.conditions.map((item,i)=>i===index?{...item,value:e.currentTarget.value}:item)})}/></div>:condition.type!=="reduced-motion"?<VsnTextField label={condition.type==="media-query"?"Media query":"Selector"} value={condition.value||""} placeholder={condition.type==="media-query"?"(min-width: 768px)":".target"} onInput={(e)=>patchSelected({conditions:selected.conditions.map((item,i)=>i===index?{...item,value:e.currentTarget.value}:item)})}/>:null}<VsnCheckbox checked={condition.negate===true} onChange={(e)=>patchSelected({conditions:selected.conditions.map((item,i)=>i===index?{...item,negate:e.currentTarget.checked}:item)})}>Invert condition</VsnCheckbox><VsnButton type="button" tone="critical" size="sm" onClick={()=>patchSelected({conditions:selected.conditions.filter((_,i)=>i!==index)})}>Remove Condition</VsnButton></div>)}</div>
      <div className="rounded-lg border border-[#e3e3e3] p-2.5 space-y-2"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#6d7175]">Timeline</p><div className="grid grid-cols-2 gap-2"><NumberField label="Duration (ms)" value={timeline.duration??400} onChange={(duration)=>patchSelected({timeline:{...timeline,duration}})}/><NumberField label="Delay (ms)" value={timeline.delay??0} onChange={(delay)=>patchSelected({timeline:{...timeline,delay}})}/></div><div className="grid grid-cols-2 gap-2"><NumberField label="Stagger (ms)" value={timeline.stagger??0} max={30000} onChange={(stagger)=>patchSelected({timeline:{...timeline,stagger}})}/><NumberField label="Repeat" value={timeline.repeat??0} max={100} onChange={(repeat)=>patchSelected({timeline:{...timeline,repeat}})}/></div><Select label="Easing" value={timeline.easing||"ease"} options={MOTION_EASING_OPTIONS} onChange={(easing)=>patchSelected({timeline:{...timeline,easing}})}/><Select label="Reduced motion" value={timeline.reducedMotion||"instant"} options={[{value:"instant",label:"Apply final state instantly"},{value:"skip",label:"Skip animation"},{value:"allow",label:"Allow full animation"}]} onChange={(reducedMotion)=>patchSelected({timeline:{...timeline,reducedMotion}})}/><VsnCheckbox checked={timeline.yoyo===true} onChange={(e)=>patchSelected({timeline:{...timeline,yoyo:e.currentTarget.checked}})}>Yoyo / alternate</VsnCheckbox></div>
      <TimelineOverview timeline={selected}/>
      <div className="space-y-2"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#6d7175]">Actions</p><VsnButton type="button" size="sm" onClick={()=>patchSelected({actions:[...(selected.actions||[]),createMotionAction()]})}>Add Action</VsnButton></div>{(selected.actions||[]).map((action,index)=><ActionEditor key={action.id||index} action={action} onChange={(next)=>patchSelected({actions:selected.actions.map((item,i)=>i===index?next:item)})} onRemove={()=>patchSelected({actions:selected.actions.filter((_,i)=>i!==index)})}/>)}</div>
      {warnings.length?<div className="rounded-md border border-amber-200 bg-amber-50 p-2 text-[10px] text-amber-800">{warnings.map((warning)=><div key={warning}>• {warning}</div>)}</div>:null}
      <div className="flex flex-wrap gap-2"><VsnButton type="button" size="sm" onClick={()=>document.dispatchEvent(new CustomEvent("vsn:preview-interaction",{detail:{elementId,timelineId:selected.id}}))}>Preview Interaction</VsnButton><VsnButton type="button" size="sm" onClick={duplicate}>Duplicate</VsnButton><VsnButton type="button" size="sm" disabled={libraryBusy} onClick={saveSelectedToLibrary}>{libraryBusy?"Saving…":"Save to Library"}</VsnButton><VsnButton type="button" tone="critical" size="sm" onClick={remove}>Delete</VsnButton></div>
    </div>:null}
  </div>;
}
