import { useEffect, useMemo, useState } from 'react';
import { useFetcher } from 'react-router';
import { CheckCircle2, ExternalLink, MapPinned, Moon, Monitor, RefreshCw, Save, ShieldCheck, Sun, Trash2 } from 'lucide-react';
import StockImageIntegrationsSettings from '../settings/StockImageIntegrationsSettings';
import { useVsnConfirm } from '../../ui/VsnConfirmProvider';
import { UI_COLOR_SCHEMES, resolveUiTheme } from '../../../config/ui-theme.js';

const ENTERPRISE_DEFAULTS={safeMode:false,criticalCss:true,cssDeduplication:true,lazyImages:true,responsiveImages:true,imageFormatDiagnostics:true,fontSubset:true,fontPreload:'auto',assetMode:'used-only'};
const APP_DEFAULTS={visitorAnalytics:true};
const EMPTY_STOCK_CREDENTIALS=Object.freeze({unsplash:{accessKey:'',secretKey:''},pexels:{apiKey:''},pixabay:{apiKey:''},freesound:{apiKey:''},shutterstock:{consumerKey:'',consumerSecret:'',oauthToken:''},getty:{apiKey:'',apiSecret:''}});
const freshStockCredentials=()=>Object.fromEntries(Object.entries(EMPTY_STOCK_CREDENTIALS).map(([provider,value])=>[provider,{...value}]));
const cloneStock=(value)=>Object.fromEntries(Object.entries(value||{}).map(([key,item])=>[key,{...(item||{}),config:{...(item?.config||{})}}]));

export default function Settings({ darkMode, themePreference='system', onThemePreferenceChange, colorSchemePreference='lime', customAccent='#95BF47', onColorSchemeChange, onCustomAccentChange, onToast, ownerInfo={}, settings={}, isOwner=false }) {
  const [enterprise,setEnterprise]=useState({...ENTERPRISE_DEFAULTS,...(settings?.enterprise||{})});
  const [app,setApp]=useState({...APP_DEFAULTS,...(settings?.app||{})});
  const [stock,setStock]=useState(()=>cloneStock(settings?.stockImages||{}));
  const [stockUsage,setStockUsage]=useState(settings?.stockUsage||{});
  const [stockCredentials,setStockCredentials]=useState(()=>freshStockCredentials());
  const [googleMaps,setGoogleMaps]=useState(settings?.googleMaps||{enabled:true,configured:false,maskedApiKey:''});
  const [googleMapsApiKey,setGoogleMapsApiKey]=useState('');
  const [testingProvider,setTestingProvider]=useState('');
  const settingsFetcher=useFetcher();
  const assetFetcher=useFetcher();
  const libraryFetcher=useFetcher();
  const uninstallFetcher=useFetcher();
  const stockTestFetcher=useFetcher();
  const confirm=useVsnConfirm();
  const saving=settingsFetcher.state!=='idle';
  const rebuildingAssets=assetFetcher.state!=='idle';
  const syncingLibrary=libraryFetcher.state!=='idle';
  useEffect(()=>setEnterprise({...ENTERPRISE_DEFAULTS,...(settings?.enterprise||{})}),[settings?.enterprise]);
  useEffect(()=>setApp({...APP_DEFAULTS,...(settings?.app||{})}),[settings?.app]);
  useEffect(()=>setStock(cloneStock(settings?.stockImages||{})),[settings?.stockImages]);
  useEffect(()=>setStockUsage(settings?.stockUsage||{}),[settings?.stockUsage]);
  useEffect(()=>setGoogleMaps(settings?.googleMaps||{enabled:true,configured:false,maskedApiKey:''}),[settings?.googleMaps]);
  useEffect(()=>{const payload=settingsFetcher.data;if(!payload)return;if(payload.success){if(payload.settings?.enterprise)setEnterprise(payload.settings.enterprise);if(payload.settings?.app)setApp(payload.settings.app);if(payload.settings?.stockImages){setStock(cloneStock(payload.settings.stockImages));setStockCredentials(freshStockCredentials());}if(payload.settings?.googleMaps){setGoogleMaps(payload.settings.googleMaps);setGoogleMapsApiKey('');}onToast?.({type:'success',title:'Settings saved',message:'VSN Builder settings are now active.'});}else if(payload.error)onToast?.({type:'error',title:'Settings need attention',message:payload.error});},[settingsFetcher.data,onToast]);
  useEffect(()=>{const payload=assetFetcher.data;if(!payload)return;if(payload.success)onToast?.({type:'success',title:'Frontend assets rebuilt',message:`${payload.assetBuild?.pageCount??0} published template(s) rebuilt.`});else if(payload.error)onToast?.({type:'error',title:'Frontend asset rebuild needs attention',message:payload.error});},[assetFetcher.data,onToast]);
  useEffect(()=>{const payload=libraryFetcher.data;if(!payload)return;if(payload.success)onToast?.({type:'success',title:'Marketplace starters synchronized',message:payload.message||'Starter catalog checked.'});else if(payload.error)onToast?.({type:'error',title:'Catalog sync failed',message:payload.error});},[libraryFetcher.data,onToast]);
  useEffect(()=>{const payload=uninstallFetcher.data;if(!payload||payload.intent!=='app-uninstall')return;if(payload.success&&payload.redirectUrl)window.top.location.assign(payload.redirectUrl);else if(payload.error)onToast?.({type:'error',title:'Uninstall failed',message:payload.error});},[uninstallFetcher.data,onToast]);
  useEffect(()=>{const payload=stockTestFetcher.data;if(!payload||payload.intent!=='test-stock-provider')return;setTestingProvider('');if(payload.stockUsage)setStockUsage(payload.stockUsage);onToast?.(payload.success?{type:'success',title:`${payload.provider} connected`,message:'Stock media API connection verified.'}:{type:'error',title:'Stock media API test failed',message:payload.error||'Could not verify provider.'});},[stockTestFetcher.data,onToast]);

  const uninstall=async()=>{
    const approved=await confirm({title:'Uninstall VSN Builder?',message:'This removes VSN Builder from this Shopify store. Type UNINSTALL to confirm this irreversible Shopify action.',confirmLabel:'Uninstall app',tone:'danger',requireText:'UNINSTALL'});
    if(!approved)return;
    uninstallFetcher.submit({intent:'app-uninstall',source:'settings'},{method:'POST',action:'/app'});
  };

  const save=()=>settingsFetcher.submit({intent:'save-app-settings',app:JSON.stringify(app),enterprise:JSON.stringify(enterprise),stock:JSON.stringify(Object.fromEntries(['unsplash','pexels','pixabay','freesound','shutterstock','getty'].map((provider)=>{const current=stock?.[provider]||{};return [provider,{enabled:current.enabled!==false,credentials:{...(stockCredentials?.[provider]||{})},config:current.config||{}}];}))),maps:JSON.stringify({enabled:googleMaps.enabled!==false,apiKey:googleMapsApiKey})},{method:'POST'});
  const updateStock=(provider,patch)=>setStock((current)=>({...current,[provider]:{...(current?.[provider]||{}),...patch,config:{...(current?.[provider]?.config||{}),...(patch.config||{})}}}));
  const updateStockCredential=(provider,key,value)=>setStockCredentials((current)=>({...current,[provider]:{...(current?.[provider]||{}),[key]:value}}));
  const testStock=(provider)=>{setTestingProvider(provider);stockTestFetcher.submit({intent:'test-stock-provider',provider},{method:'POST'});};
  const shopDomain=ownerInfo?.myshopifyDomain||'';
  const adminBase=shopDomain?`https://${shopDomain}/admin`:'';
  const storeRows=useMemo(()=>[
    {label:'Store name',value:ownerInfo?.shopName||'Unavailable',href:adminBase?`${adminBase}/settings/general`:''},
    {label:'Currency',value:ownerInfo?.currencyCode||'Managed in Shopify',href:adminBase?`${adminBase}/settings/markets`:''},
    {label:'Timezone',value:ownerInfo?.ianaTimezone||'Managed in Shopify',href:adminBase?`${adminBase}/settings/general`:''},
    {label:'Primary language',value:ownerInfo?.primaryLocale||'Managed in Shopify',href:adminBase?`${adminBase}/settings/languages`:''},
  ],[adminBase,ownerInfo]);
  const Toggle=({label,description,checked,onChange})=><label className="vsn-settings-toggle-row"><span><strong>{label}</strong><small>{description}</small></span><span className="toggle-switch"><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.currentTarget.checked)}/><span className="toggle-slider"/></span></label>;
  return <div className="vsn-settings-page page-fade">
    <header className="vsn-settings-head"><div><h1>Settings</h1><p>Only options that VSN Builder can actually apply are editable here. Shopify-owned store settings remain read-only.</p></div><button type="button" className="dashboard-primary-action" disabled={saving} onClick={save}><Save size={14}/>{saving?'Saving…':'Save changes'}</button></header>

    <section className="vsn-settings-card"><div className="vsn-settings-card-head"><div><strong>Appearance</strong><span>Theme mode and UI accent apply across the VSN Builder management interface.</span></div></div><div className="vsn-settings-card-body"><div className="vsn-appearance-options">{[{id:'light',label:'Light',Icon:Sun},{id:'dark',label:'Dark',Icon:Moon},{id:'system',label:'System',Icon:Monitor}].map(({id,label,Icon})=><button key={id} type="button" className={themePreference===id?'is-active':''} onClick={()=>onThemePreferenceChange?.(id)}><Icon size={17}/><span>{label}</span>{themePreference===id?<CheckCircle2 size={14}/>:null}</button>)}</div><div className="vsn-color-scheme-settings"><div className="vsn-color-scheme-copy"><strong>Interface color</strong><span>Choose a preset or create a custom accent. Text/hover/focus tokens are derived automatically for compatibility.</span></div><div className="vsn-color-scheme-grid">{UI_COLOR_SCHEMES.filter((item)=>item.id!=='custom').map((item)=>{const theme=resolveUiTheme(item.id,customAccent);return <button key={item.id} type="button" className={colorSchemePreference===item.id?'is-active':''} onClick={()=>onColorSchemeChange?.(item.id)} aria-label={`${item.label} interface color`}><span className="vsn-color-swatch" style={{background:theme.accent}}/><span>{item.label}</span>{colorSchemePreference===item.id?<CheckCircle2 size={13}/>:null}</button>})}<label className={`vsn-custom-color-option ${colorSchemePreference==='custom'?'is-active':''}`}><input type="color" value={resolveUiTheme('custom',customAccent).accent} onChange={(event)=>onCustomAccentChange?.(event.currentTarget.value)}/><span className="vsn-color-swatch" style={{background:resolveUiTheme('custom',customAccent).accent}}/><span>Custom</span><code>{resolveUiTheme('custom',customAccent).accent}</code></label></div></div><p className="vsn-settings-help">Appearance and UI color are saved in this browser so each staff member can use a preferred workspace style without changing the storefront theme.</p></div></section>

    <section className="vsn-settings-card"><div className="vsn-settings-card-head"><div><strong>Shopify store</strong><span>These values come from Shopify and are not duplicated as editable VSN settings.</span></div><span className="vsn-settings-managed"><ShieldCheck size={13}/> Shopify managed</span></div><div className="vsn-settings-card-body"><div className="vsn-settings-store-grid">{storeRows.map((row)=><div key={row.label}><span>{row.label}</span><strong>{row.value}</strong>{row.href?<a className="vsn-settings-shopify-link" href={row.href} target="_top">Manage in Shopify <ExternalLink size={12}/></a>:null}</div>)}</div><p className="vsn-settings-help">These values are owned by Shopify. Use the relevant Manage in Shopify link, then reopen or refresh VSN Builder to read the updated value.</p></div></section>

    <section className="vsn-settings-card"><div className="vsn-settings-card-head"><div><strong>Storefront performance</strong><span>These controls use the same Enterprise Hardening settings consumed by the VSN storefront renderer.</span></div></div><div className="vsn-settings-card-body"><Toggle label="Lazy-load images" description="Defer eligible storefront images until they approach the viewport." checked={enterprise.lazyImages!==false} onChange={(lazyImages)=>setEnterprise(v=>({...v,lazyImages}))}/><Toggle label="Responsive images" description="Generate responsive image markup and source candidates where supported." checked={enterprise.responsiveImages!==false} onChange={(responsiveImages)=>setEnterprise(v=>({...v,responsiveImages}))}/><Toggle label="Critical CSS" description="Keep critical VSN layout CSS available early in the page lifecycle." checked={enterprise.criticalCss!==false} onChange={(criticalCss)=>setEnterprise(v=>({...v,criticalCss}))}/><Toggle label="CSS deduplication" description="Avoid repeated generated style rules in VSN storefront output." checked={enterprise.cssDeduplication!==false} onChange={(cssDeduplication)=>setEnterprise(v=>({...v,cssDeduplication}))}/><Toggle label="Font variant pruning" description="Load only used custom-font weights/styles when VSN can determine usage safely." checked={enterprise.fontSubset!==false} onChange={(fontSubset)=>setEnterprise(v=>({...v,fontSubset}))}/><Toggle label="Image format diagnostics" description="Report heavy or suboptimal image formats in System Health." checked={enterprise.imageFormatDiagnostics!==false} onChange={(imageFormatDiagnostics)=>setEnterprise(v=>({...v,imageFormatDiagnostics}))}/><Toggle label="Safe Mode" description="Disable generated custom JavaScript while preserving content and styles. Use this for recovery only." checked={enterprise.safeMode===true} onChange={(safeMode)=>setEnterprise(v=>({...v,safeMode}))}/></div></section>

    <section className="vsn-settings-card"><div className="vsn-settings-card-head"><div><strong>Application behavior</strong><span>Operational settings used by Dashboard telemetry and Motion Engine.</span></div></div><div className="vsn-settings-card-body"><Toggle label="Visitor analytics" description="Collect privacy-minimized VSN storefront session counts for the Dashboard visitor map. IP addresses are not stored." checked={app.visitorAnalytics!==false} onChange={(visitorAnalytics)=>setApp(v=>({...v,visitorAnalytics}))}/><p className="vsn-settings-help">Animation accessibility is configured in Motion Library and Page Motion Defaults, where it is stored with the actual animation timeline instead of as a disconnected app toggle.</p></div></section>

    <section className="vsn-settings-card"><div className="vsn-settings-card-head"><div><strong>Stock media integrations</strong><span>Server-only credentials for Stock Images, Stock Videos and Stock Audio workspaces. Credentials are encrypted before storage and never returned to the browser.</span></div></div><div className="vsn-settings-card-body"><StockImageIntegrationsSettings stock={stock} credentials={stockCredentials} usage={stockUsage} onCredentialChange={updateStockCredential} onProviderChange={updateStock} onTest={testStock} testingProvider={testingProvider} testing={stockTestFetcher.state!=="idle"}/><p className="vsn-settings-help">Paste credentials, then use <strong>Save changes</strong>. Each provider card includes the official documentation and credential-creation path. Usage counts are VSN-observed requests; provider quota/remaining values appear when the API exposes rate-limit headers.</p></div></section>

    <section className="vsn-settings-card"><div className="vsn-settings-card-head"><div><strong>Google Maps</strong><span>Global Google Maps API key used by VSN Map widgets on published storefront pages.</span></div><span className={`vsn-settings-managed ${googleMaps.configured?'is-connected':''}`}><MapPinned size={13}/>{googleMaps.configured?'Connected':'Not configured'}</span></div><div className="vsn-settings-card-body"><Toggle label="Enable Google Maps" description="Allow published VSN Map widgets to use the configured Maps Embed API key." checked={googleMaps.enabled!==false} onChange={(enabled)=>setGoogleMaps((current)=>({...current,enabled}))}/><label className="vsn-settings-secret-field"><span>Google Maps API key</span><div><input type="password" autoComplete="new-password" spellCheck={false} value={googleMapsApiKey} onChange={(event)=>setGoogleMapsApiKey(event.currentTarget.value)} placeholder={googleMaps.configured?googleMaps.maskedApiKey||'Saved API key':'Paste API key'}/></div><small>{googleMaps.configured?`Saved key: ${googleMaps.maskedApiKey}. Leave blank to keep it.`:'No Google Maps API key is saved yet.'}</small></label><div className="vsn-settings-doc-links"><a href="https://developers.google.com/maps/documentation/embed/get-api-key" target="_blank" rel="noreferrer">Create/restrict a Maps API key <ExternalLink size={12}/></a><a href="https://developers.google.com/maps/documentation/embed/embedding-map" target="_blank" rel="noreferrer">Maps Embed API documentation <ExternalLink size={12}/></a></div><p className="vsn-settings-help">The Map widget uses Google Maps Embed API on storefront pages. Restrict this browser-visible key to your storefront domains and only the required Maps API.</p></div></section>

    <section className="vsn-settings-card"><div className="vsn-settings-card-head"><div><strong>Frontend assets</strong><span>Manual recovery and synchronization tools. They do not replace normal automatic publishing.</span></div></div><div className="vsn-settings-card-body vsn-settings-actions"><assetFetcher.Form method="post"><input type="hidden" name="intent" value="rebuild-theme-assets"/><button type="submit" className="dashboard-secondary-action" disabled={rebuildingAssets}><RefreshCw size={14}/>{rebuildingAssets?'Rebuilding…':'Rebuild frontend assets'}</button></assetFetcher.Form><libraryFetcher.Form method="post"><input type="hidden" name="intent" value="sync-library-defaults"/><button type="submit" className="dashboard-secondary-action" disabled={syncingLibrary}><RefreshCw size={14}/>{syncingLibrary?'Checking…':'Sync Marketplace starters'}</button></libraryFetcher.Form></div></section>

    {isOwner ? <section className="vsn-settings-card vsn-settings-danger-card"><div className="vsn-settings-card-head"><div><strong>Danger zone</strong><span>Removing the app is a Shopify-level action and cannot be undone from VSN Builder.</span></div></div><div className="vsn-settings-card-body vsn-settings-danger-row"><div><strong>Uninstall VSN Builder</strong><p>Removes the app installation from this store. Shopify will revoke the app access token and clean up registered app integrations.</p></div><button type="button" className="vsn-danger-action" disabled={uninstallFetcher.state!=='idle'} onClick={uninstall}><Trash2 size={14}/>{uninstallFetcher.state!=='idle'?'Uninstalling…':'Uninstall app'}</button></div></section> : null}

  </div>;
}
