import { useEffect, useMemo, useState } from 'react';
import { useFetcher } from 'react-router';
import { MessageCircle, Headphones, Ticket, HelpCircle, PlayCircle, Users, Bug, Lightbulb, ArrowRight, Clock, CheckCircle, Plus, MessageSquare, X, Send, CreditCard, Wrench, LifeBuoy } from 'lucide-react';

const categories = { general: { label: 'General', icon: LifeBuoy }, technical: { label: 'Technical', icon: Wrench }, bug: { label: 'Bug', icon: Bug }, billing: { label: 'Billing', icon: CreditCard }, feature: { label: 'Feature request', icon: Lightbulb } };
const supportCards = [
  { key:'chat', icon: MessageCircle, title:'Live Chat', desc:'Chat with our support team when live assistance is available.', action:'Start Chat', color:'var(--vsn-green)', bg:'rgba(var(--vsn-accent-rgb),0.1)' },
  { key:'ticket', icon: Ticket, title:'Create Ticket', desc:'Submit a tracked support ticket and keep every reply in one thread.', action:'Open Ticket', color:'#5C6AC4', bg:'rgba(92,106,196,0.1)' },
  { key:'contact', icon: Headphones, title:'Contact Support', desc:'Get help with account, billing, builder or publishing questions.', action:'Contact Team', color:'#8B5CF6', bg:'rgba(139,92,246,0.1)' },
  { key:'faq', icon: HelpCircle, title:'FAQ', desc:'Browse common setup, publishing and troubleshooting questions.', action:'View FAQs', color:'#F59E0B', bg:'rgba(245,158,11,0.1)' },
  { key:'videos', icon: PlayCircle, title:'Video Tutorials', desc:'Step-by-step walkthroughs for builder workflows and features.', action:'View Tutorials', color:'#EF4444', bg:'rgba(239,68,68,0.1)' },
  { key:'community', icon: Users, title:'Community', desc:'Connect with other merchants and page-builder users.', action:'Community', color:'#06B6D4', bg:'rgba(6,182,212,0.1)' },
  { key:'bug', icon: Bug, title:'Report a Bug', desc:'Create a technical ticket with reproduction steps and error details.', action:'Report Bug', color:'#DC2626', bg:'rgba(220,38,38,0.1)' },
  { key:'feature', icon: Lightbulb, title:'Feature Request', desc:'Submit an improvement idea and keep it tracked as a support request.', action:'Request Feature', color:'#D97706', bg:'rgba(217,119,6,0.1)' },
];

function dateTime(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleString(); }

export default function Support({ darkMode, onToast, onNavigate, tickets = [], onTicketsChange, onNotificationCreated, userName, initialTicketId = null }) {
  const fetcher = useFetcher();
  const [showCreate, setShowCreate] = useState(false);
  const [selectedId, setSelectedId] = useState(initialTicketId || tickets[0]?.id || null);
  const [subject, setSubject] = useState(''); const [body, setBody] = useState(''); const [category, setCategory] = useState('general'); const [priority, setPriority] = useState('normal'); const [reply, setReply] = useState(''); const [pendingIntent, setPendingIntent] = useState('');
  const text = darkMode ? '#F9FAFB' : '#1A1F36'; const muted = darkMode ? '#9CA3AF' : '#6B7280'; const border = darkMode ? '#2D3748' : '#E5E7EB'; const card = { background: darkMode ? '#1A1F2E' : '#FFFFFF', borderRadius: 12, border: `1px solid ${border}` };
  const selected = useMemo(() => tickets.find((ticket) => ticket.id === selectedId) || null, [tickets, selectedId]); const busy = fetcher.state !== 'idle';
  const submit = (payload) => { setPendingIntent(payload.intent); fetcher.submit(payload, { method:'post' }); };

  useEffect(() => { if (!selectedId && tickets[0]?.id) setSelectedId(tickets[0].id); }, [tickets, selectedId]);
  useEffect(() => { if (initialTicketId && tickets.some((item) => item.id === initialTicketId)) setSelectedId(initialTicketId); }, [initialTicketId, tickets]);
  useEffect(() => {
    if (!pendingIntent || fetcher.state !== 'idle' || !fetcher.data) return;
    if (fetcher.data.success && fetcher.data.ticket) {
      const nextTicket = fetcher.data.ticket; const exists = tickets.some((ticket) => ticket.id === nextTicket.id); const nextTickets = exists ? tickets.map((ticket) => ticket.id === nextTicket.id ? nextTicket : ticket) : [nextTicket, ...tickets];
      onTicketsChange?.(nextTickets); setSelectedId(nextTicket.id);
      if (pendingIntent === 'support-create') { setShowCreate(false); setSubject(''); setBody(''); setCategory('general'); setPriority('normal'); if (fetcher.data.notification) onNotificationCreated?.(fetcher.data.notification); onToast?.({ type:'success', title:'Ticket created', message:`${nextTicket.ticketCode} has been submitted.` }); }
      if (pendingIntent === 'support-reply') { setReply(''); onToast?.({ type:'success', title:'Reply added', message:'Your reply has been added to the ticket.' }); }
    } else if (fetcher.data?.error) onToast?.({ type:'error', title:'Support request failed', message:fetcher.data.error });
    setPendingIntent('');
  }, [fetcher.state, fetcher.data, pendingIntent, tickets, onTicketsChange, onNotificationCreated, onToast]);

  const openCreate = (nextCategory='general', nextSubject='') => { setCategory(nextCategory); setSubject(nextSubject); setShowCreate(true); };
  const cardAction = (key) => {
    if (key === 'ticket') return openCreate(); if (key === 'bug') return openCreate('bug', 'Bug report: '); if (key === 'feature') return openCreate('feature', 'Feature request: '); if (key === 'faq') return onNavigate?.('documentation', { doc:'faq' });
    onToast?.({ type:'info', title:supportCards.find((item) => item.key === key)?.title || 'Support', message:'This support channel is available from the Support Center configuration when connected.' });
  };
  const createTicket = () => submit({ intent:'support-create', subject, body, category, priority });
  const sendReply = () => selected && submit({ intent:'support-reply', id:selected.id, body:reply });
  const setStatus = (status) => selected && submit({ intent:'support-status', id:selected.id, status });

  return (<div className="page-fade" style={{ padding:'28px 32px', maxWidth:1440, margin:'0 auto' }}>
    <div style={{ marginBottom:28, display:'flex', justifyContent:'space-between', alignItems:'flex-end', gap:16 }}><div><h1 style={{ margin:0, fontSize:22, fontWeight:800, color:text }}>Support Center</h1><p style={{ margin:'4px 0 0', fontSize:14, color:muted }}>Get help, report issues, access resources, and manage tracked support tickets.</p></div><button onClick={() => openCreate()} className="dashboard-primary-action"><Plus size={14}/>Create Ticket</button></div>
    <div style={{ background:'rgba(var(--vsn-accent-rgb),0.08)', border:'1px solid rgba(var(--vsn-accent-rgb),0.25)', borderRadius:10, padding:'12px 18px', marginBottom:28, display:'flex', alignItems:'center', gap:10 }}><CheckCircle size={16} color="var(--vsn-green)"/><span style={{ fontSize:13, color:text }}><strong>Support Center active</strong> · Tickets and replies are tracked per Shopify store.</span><div style={{ marginLeft:'auto', display:'flex', alignItems:'center', gap:6 }}><Clock size={13} color={muted}/><span style={{ fontSize:12, color:muted }}>{tickets.filter((item) => item.status === 'open').length} open ticket(s)</span></div></div>

    <div className="support-card-grid" style={{ display:'grid', gridTemplateColumns:'repeat(4, minmax(0,1fr))', gap:16, marginBottom:32 }}>
      {supportCards.map((item) => { const Icon=item.icon; return <button type="button" key={item.key} onClick={() => cardAction(item.key)} style={{ ...card, padding:22, cursor:'pointer', textAlign:'left', transition:'all .15s', color:text }} className="support-option-card"><div style={{ width:46, height:46, borderRadius:10, marginBottom:14, background:item.bg, display:'grid', placeItems:'center', color:item.color }}><Icon size={24}/></div><div style={{ fontSize:14, fontWeight:700, color:text, marginBottom:6 }}>{item.title}</div><div style={{ fontSize:12, color:muted, lineHeight:1.5, marginBottom:14 }}>{item.desc}</div><div style={{ display:'flex', alignItems:'center', gap:4, fontSize:12, fontWeight:600, color:item.color }}>{item.action}<ArrowRight size={12}/></div></button>; })}
    </div>

    <div style={{ display:'grid', gridTemplateColumns:'340px minmax(0,1fr)', gap:16, alignItems:'start' }} className="support-ticket-layout">
      <section style={{ ...card, overflow:'hidden' }}><div style={{ padding:'16px 18px', borderBottom:`1px solid ${border}`, display:'flex', alignItems:'center', justifyContent:'space-between' }}><strong style={{ fontSize:14, color:text }}>Recent Tickets</strong><span style={{ fontSize:11, color:muted }}>{tickets.length}</span></div><div style={{ maxHeight:620, overflow:'auto' }}>{tickets.length ? tickets.map((ticket) => <button key={ticket.id} onClick={() => setSelectedId(ticket.id)} className="support-ticket-row" style={{ width:'100%', border:0, borderBottom:`1px solid ${darkMode ? '#1F2937' : '#F3F4F6'}`, background:ticket.id===selectedId?(darkMode?'#222938':'#F8FAF4'):'transparent', padding:'14px 16px', textAlign:'left', cursor:'pointer' }}><div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', gap:8 }}><span style={{ fontFamily:'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize:11.5, fontWeight:700, color:'#5C6AC4' }}>{ticket.ticketCode}</span><span style={{ fontSize:10.5, fontWeight:700, color:ticket.status==='open'?'#D97706':'var(--vsn-green-dark)' }}>{ticket.status==='open'?'● Open':'✓ Closed'}</span></div><div style={{ marginTop:5, fontSize:12.5, fontWeight:650, color:text, lineHeight:1.4 }}>{ticket.subject}</div><div style={{ marginTop:5, fontSize:10.5, color:muted }}>{new Date(ticket.updatedAt).toLocaleDateString()}</div></button>) : <div style={{ padding:34, textAlign:'center', color:muted }}><Ticket size={26}/><div style={{ marginTop:9, fontSize:13, fontWeight:700, color:text }}>No tickets yet</div><div style={{ marginTop:4, fontSize:11.5 }}>Create a ticket when you need help.</div></div>}</div></section>

      <section style={{ ...card, minHeight:420, overflow:'hidden' }}>{selected ? <><div style={{ padding:'16px 18px', borderBottom:`1px solid ${border}`, display:'flex', gap:14, alignItems:'flex-start' }}><div style={{ minWidth:0, flex:1 }}><div style={{ display:'flex', alignItems:'center', gap:8 }}><span style={{ fontSize:11, fontWeight:700, color:'#5C6AC4' }}>{selected.ticketCode}</span><span style={{ fontSize:10.5, fontWeight:700, padding:'3px 7px', borderRadius:99, background:selected.status==='open'?'rgba(245,158,11,.10)':'rgba(var(--vsn-accent-rgb),.10)', color:selected.status==='open'?'#D97706':'var(--vsn-green-dark)' }}>{selected.status}</span></div><h2 style={{ margin:'6px 0 0', fontSize:15, color:text }}>{selected.subject}</h2><div style={{ marginTop:5, fontSize:11.5, color:muted }}>Opened {dateTime(selected.createdAt)} · {selected.priority} priority</div></div><button disabled={busy} onClick={() => setStatus(selected.status === 'open' ? 'closed' : 'open')} className="dashboard-secondary-action">{selected.status === 'open' ? 'Close ticket' : 'Reopen'}</button></div><div style={{ padding:18, display:'grid', gap:12, maxHeight:430, overflow:'auto', background:darkMode?'#151A25':'#FAFAFA' }}>{(selected.messages || []).map((message) => <div key={message.id} style={{ maxWidth:'82%', justifySelf:message.authorType==='merchant'?'end':'start', border:`1px solid ${border}`, background:message.authorType==='merchant'?(darkMode?'#202B1B':'#F7FBEF'):(darkMode?'#1A1F2E':'#fff'), borderRadius:10, padding:'10px 12px' }}><div style={{ display:'flex', gap:7, marginBottom:5, fontSize:10.5, color:muted }}><strong style={{ color:text }}>{message.authorName || (message.authorType === 'merchant' ? userName : 'VSN Support')}</strong><span>·</span><span>{dateTime(message.createdAt)}</span></div><div style={{ fontSize:12.5, lineHeight:1.55, color:text, whiteSpace:'pre-wrap' }}>{message.body}</div></div>)}</div><div style={{ padding:14, borderTop:`1px solid ${border}`, display:'flex', gap:9, alignItems:'flex-end' }}><textarea value={reply} onChange={(e) => setReply(e.target.value)} placeholder="Write a reply…" rows={3} className="dashboard-textarea"/><button disabled={busy || !reply.trim()} onClick={sendReply} className="dashboard-primary-action"><Send size={14}/>{busy && pendingIntent==='support-reply'?'Sending…':'Reply'}</button></div></> : <div style={{ minHeight:420, display:'grid', placeItems:'center', textAlign:'center', color:muted }}><div><MessageSquare size={30}/><div style={{ marginTop:10, fontSize:14, fontWeight:700, color:text }}>Select a ticket</div><div style={{ marginTop:4, fontSize:12 }}>Ticket details and replies will appear here.</div></div></div>}</section>
    </div>

    {showCreate ? <div className="dashboard-modal-backdrop" onMouseDown={(e) => { if (e.currentTarget === e.target && !busy) setShowCreate(false); }}><div className="dashboard-modal" style={{ ...card }}><div className="dashboard-modal-header"><div><strong>Create support ticket</strong><span>Describe the issue clearly so it can be tracked and answered.</span></div><button disabled={busy} onClick={() => setShowCreate(false)} className="dashboard-icon-button"><X size={16}/></button></div><div className="dashboard-modal-body"><label className="dashboard-field"><span>Subject</span><input value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="What do you need help with?"/></label><div className="dashboard-field-grid"><label className="dashboard-field"><span>Category</span><select value={category} onChange={(e) => setCategory(e.target.value)}>{Object.entries(categories).map(([key,value]) => <option key={key} value={key}>{value.label}</option>)}</select></label><label className="dashboard-field"><span>Priority</span><select value={priority} onChange={(e) => setPriority(e.target.value)}>{['low','normal','high','urgent'].map((value) => <option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select></label></div><label className="dashboard-field"><span>{category==='feature'?'Problem / desired outcome':category==='bug'?'Reproduction details':'Message'}</span><textarea value={body} onChange={(e) => setBody(e.target.value)} rows={7} placeholder={category==='bug'?'Include steps to reproduce, expected behavior, actual behavior, screen/feature and any visible error.':category==='feature'?'Describe the problem, who it affects, the desired workflow and what a successful result should look like.':'Include enough context for the support team to understand the request.'}/></label></div><div className="dashboard-modal-footer"><button disabled={busy} onClick={() => setShowCreate(false)} className="dashboard-secondary-action">Cancel</button><button disabled={busy || subject.trim().length < 3 || body.trim().length < 5} onClick={createTicket} className="dashboard-primary-action"><Ticket size={14}/>{busy && pendingIntent==='support-create'?'Submitting…':'Submit ticket'}</button></div></div></div> : null}
  </div>);
}
