import { useMemo, useState } from 'react';
import { Activity, Camera, Gauge, PlugZap, RefreshCw, ShieldCheck, TerminalSquare } from 'lucide-react';

function Card({children,darkMode=false,className=''}){return <section className={`rounded-xl border p-4 ${darkMode?'border-[#273142] bg-[#151b26]':'border-[#e3e3e3] bg-white'} ${className}`}>{children}</section>}
function Badge({tone='neutral',children}){const cls=tone==='pass'?'bg-emerald-50 text-emerald-700':tone==='fail'||tone==='high'?'bg-red-50 text-red-700':tone==='warn'||tone==='medium'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-700';return <span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase ${cls}`}>{children}</span>}
function Btn({children,onClick,disabled=false,primary=false}){return <button type="button" disabled={disabled} onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-semibold disabled:opacity-50 ${primary?'bg-[var(--vsn-green)] text-white':'border border-[#d1d5db] bg-white text-[#202223]'}`}>{children}</button>}
function bytes(value){const kb=Number(value||0)/1024;return kb<1024?`${kb.toFixed(1)} KB`:`${(kb/1024).toFixed(1)} MB`;}

export default function PlatformQualityPanel({data={},darkMode=false,fetcher,permissions={}}){
  const [subtab,setSubtab]=useState('visual');
  const [manifest,setManifest]=useState(JSON.stringify({schemaVersion:1,id:'my.plugin',name:'My Plugin',version:'1.0.0',compatibility:{min:'2.5.50',maxExclusive:'3.0.0'},permissions:['editor:controls'],widgets:[]},null,2));
  const result=fetcher?.data?.result;
  const migration=fetcher?.data?.migration;
  const tabs=[['visual','Visual Regression'],['performance','Performance Budget'],['extensions','Extension Sandbox'],['migrations','Migration Simulator'],['commands','Command Architecture']];
  const visual=data.visual||{rows:[],counts:{}}; const performance=data.performance||{rows:[],counts:{}}; const extensions=data.extensions||{plugins:[],allowedPermissions:[]}; const commands=data.commands||[];
  const worst=useMemo(()=>[...(performance.rows||[])].sort((a,b)=>(a.score||0)-(b.score||0)).slice(0,30),[performance.rows]);
  const submit=(payload)=>fetcher?.submit(payload,{method:'post'});
  return <div className="space-y-4">
    <Card darkMode={darkMode}><div className="flex flex-wrap items-center gap-2">{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>setSubtab(id)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${subtab===id?'bg-[var(--vsn-green)] text-white':darkMode?'bg-[#1f2937] text-[#e5e7eb]':'bg-[#f6f6f7] text-[#374151]'}`}>{label}</button>)}</div></Card>
    {subtab==='visual'?<>
      <div className="grid gap-3 sm:grid-cols-4"><Card darkMode={darkMode}><Camera size={18}/><b className="mt-2 block text-2xl">{visual.counts?.total||0}</b><span className="text-xs opacity-70">Pages tracked</span></Card><Card darkMode={darkMode}><b className="text-2xl">{visual.counts?.pass||0}</b><span className="mt-1 block text-xs opacity-70">Baseline match</span></Card><Card darkMode={darkMode}><b className="text-2xl">{visual.counts?.changed||0}</b><span className="mt-1 block text-xs opacity-70">Changed</span></Card><Card darkMode={darkMode}><b className="text-2xl">{visual.counts?.missing||0}</b><span className="mt-1 block text-xs opacity-70">Missing baseline</span></Card></div>
      <Card darkMode={darkMode}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Structural visual baselines</h3><p className="mt-1 text-xs opacity-70">Fast page-tree hash + node/type signature. Real pixel screenshots remain available through the Playwright runner.</p></div><Btn primary disabled={!permissions.runQa||fetcher?.state!=='idle'} onClick={()=>submit({intent:'capture-visual-baseline'})}>Capture current baselines</Btn></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th className="py-2">Page</th><th>Status</th><th>Nodes</th><th>Hash</th></tr></thead><tbody>{(visual.rows||[]).slice(0,80).map(row=><tr key={row.id} className="border-b border-black/5"><td className="py-2 font-medium">{row.title}</td><td><Badge tone={row.status==='pass'?'pass':row.status==='changed'?'warn':'neutral'}>{row.status}</Badge></td><td>{row.current?.nodes||0}</td><td className="font-mono text-[10px]">{row.current?.hash}</td></tr>)}</tbody></table></div><p className="mt-3 text-[11px] opacity-70">Pixel runner: <code>npm run qa:visual-regression</code> · requires authenticated editor URL/page ID.</p></Card>
    </>:null}
    {subtab==='performance'?<>
      <div className="grid gap-3 sm:grid-cols-4"><Card darkMode={darkMode}><Gauge size={18}/><b className="mt-2 block text-2xl">{performance.counts?.total||0}</b><span className="text-xs opacity-70">Pages</span></Card><Card darkMode={darkMode}><b className="text-2xl">{performance.counts?.pass||0}</b><span className="text-xs opacity-70">Pass</span></Card><Card darkMode={darkMode}><b className="text-2xl">{performance.counts?.warn||0}</b><span className="text-xs opacity-70">Warnings</span></Card><Card darkMode={darkMode}><b className="text-2xl">{performance.counts?.fail||0}</b><span className="text-xs opacity-70">Over budget</span></Card></div>
      <Card darkMode={darkMode}><h3 className="font-semibold">Page performance budget</h3><p className="mt-1 text-xs opacity-70">Pre-publish intelligence for DOM/content/media/custom-code/third-party pressure. It warns; it does not silently block publishing.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th className="py-2">Page</th><th>Score</th><th>Status</th><th>Nodes</th><th>Content</th><th>Media</th><th>Code</th><th>Origins</th></tr></thead><tbody>{worst.map(row=><tr key={row.id} className="border-b border-black/5"><td className="py-2 font-medium">{row.title}</td><td>{row.score}/100</td><td><Badge tone={row.status}>{row.status}</Badge></td><td>{row.nodes}</td><td>{bytes(row.contentBytes)}</td><td>{row.mediaRefs}</td><td>{bytes(row.customCodeBytes)}</td><td>{row.externalOrigins}</td></tr>)}</tbody></table></div></Card>
    </>:null}
    {subtab==='extensions'?<>
      <Card darkMode={darkMode}><div className="flex items-center gap-2"><PlugZap size={18}/><h3 className="font-semibold">Installed extension permission sandbox</h3></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{(extensions.plugins||[]).map(plugin=><div key={plugin.id} className={`rounded-lg border p-3 ${darkMode?'border-[#374151] bg-[#0f172a]':'border-[#e5e7eb] bg-[#fafafa]'}`}><div className="flex items-start justify-between gap-2"><div><b className="text-sm">{plugin.name}</b><div className="text-[10px] opacity-65">{plugin.id} · {plugin.widgets} widgets · {plugin.dataProviders} providers</div></div><Badge tone={plugin.permissions.some(p=>p.risk==='high')?'high':plugin.permissions.some(p=>p.risk==='medium')?'medium':'pass'}>{plugin.status}</Badge></div><div className="mt-2 flex flex-wrap gap-1">{plugin.permissions.map(p=><span key={p.permission} className="rounded bg-black/5 px-2 py-1 text-[10px]">{p.permission} · {p.risk}</span>)}</div>{plugin.networkOrigins?.length?<div className="mt-2 text-[10px]">Origins: {plugin.networkOrigins.join(', ')}</div>:null}</div>)}</div></Card>
      <Card darkMode={darkMode}><h3 className="font-semibold">Evaluate a manifest without installing it</h3><textarea value={manifest} onChange={e=>setManifest(e.target.value)} rows={10} className={`mt-3 w-full rounded-lg border p-3 font-mono text-xs ${darkMode?'border-[#374151] bg-[#0f172a] text-[#f8fafc]':'border-[#d1d5db] bg-white text-[#111827]'}`}/><div className="mt-3"><Btn primary disabled={!permissions.manageExtensions||fetcher?.state!=='idle'} onClick={()=>submit({intent:'evaluate-plugin-manifest',manifest})}>Evaluate permissions</Btn></div>{result?<div className={`mt-3 rounded-lg border p-3 text-xs ${result.ok?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-700'}`}><b>{result.ok?'Manifest accepted':'Manifest rejected'}</b><p className="mt-1">Risk: {result.risk?.level||'unknown'}</p>{result.errors?.length?<ul className="mt-2 list-disc pl-5">{result.errors.map((x,i)=><li key={i}>{x}</li>)}</ul>:null}</div>:null}</Card>
    </>:null}
    {subtab==='migrations'?<Card darkMode={darkMode}><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><RefreshCw size={18}/><h3 className="font-semibold">Release migration simulator</h3></div><p className="mt-1 text-xs opacity-70">Runs current page/library schema migrations in memory. No content is written.</p></div><Btn primary disabled={!permissions.simulateMigrations||fetcher?.state!=='idle'} onClick={()=>submit({intent:'simulate-migrations'})}>Run dry-run</Btn></div>{migration?<div className="mt-4"><div className="flex gap-2 text-xs"><Badge tone={migration.counts?.fail?'fail':'pass'}>{migration.counts?.fail?`${migration.counts.fail} failed`:'all passed'}</Badge><span>{migration.counts?.total} resources · {migration.counts?.changed} would change</span></div><div className="mt-3 max-h-[430px] overflow-auto">{migration.rows?.filter(r=>r.status==='fail'||r.changed).map(row=><div key={`${row.type}:${row.id}`} className="border-b py-2 text-xs"><b>{row.title}</b> · {row.type} · {row.status}{row.error?` · ${row.error}`:` · v${row.beforeVersion} → v${row.afterVersion}`}</div>)}</div></div>:null}</Card>:null}
    {subtab==='commands'?<Card darkMode={darkMode}><div className="flex items-center gap-2"><TerminalSquare size={18}/><h3 className="font-semibold">Transaction / Command Architecture</h3></div><p className="mt-1 text-xs opacity-70">P.2 platform mutations execute through a transactional command bus and write command IDs to the VSN audit trail.</p><div className="mt-4 space-y-2">{commands.length?commands.map(row=><div key={row.id} className={`rounded-lg border p-3 text-xs ${darkMode?'border-[#374151] bg-[#0f172a]':'border-[#e5e7eb] bg-[#fafafa]'}`}><div className="flex items-center justify-between gap-2"><b>{row.action}</b><span className="opacity-60">{row.createdAt}</span></div><div className="mt-1 opacity-70">{row.actor||'system'} · {row.role||'system'}{row.pageId?` · page ${row.pageId}`:''}</div></div>):<p className="text-xs opacity-65">No platform commands recorded yet.</p>}</div><div className="mt-4 flex items-center gap-2 text-xs"><ShieldCheck size={15}/><span>Database transaction + audit command record are one server-side contract.</span></div></Card>:null}
  </div>;
}
